Makefile
=> build: makefile lints and tidys

actors/builtin/storage_market/storage_market_actor.go
Break dep by projecting from unnecessarily imported sector commit info type. If more parts of the sector info are required later, we can add them too.
=> Break dependency of storage market actor on miner 

actors/builtin/multisig/multisig_actor.go, actors/builtin/multisig/multisig_actor_state.go
- required as ID's are not set until finality
=> refactor: replaces actorIDs with addresses

actors/runtime/runtime.go
No semantic change, just makes me happier.
=> Re-order runtime methods to make more sense to me.

actors/abi/sector.go, actors/builtin/network_parameters.go, actors/builtin/storage_miner/storage_miner_actor.go
To replace https://github.com/filecoin-project/specs/pull/845
=> add seal randomness

actors/builtin/multisig/multisig_actor_state.go
=> fix bigint math

actors/builtin/init/init_actor.go, actors/builtin/reward/reward_actor.go, actors/builtin/storage_market/storage_market_actor_state.go, actors/builtin/storage_miner/storage_miner_actor_state.go, actors/runtime/params.go, actors/runtime/runtime.go, actors/util/adt/map.go
As discussed with @whyrusleeping
=> Fix CBOR interfaces in runtime state access

actors/builtin/multisig/multisig_actor.go
@whyrusleeping this will fix the bug being hit in this integration work stream: https://github.com/filecoin-project/specs-actors/pull/46
=> bug: fix shadowing in multisig actor

actors/builtin/multisig/multisig_test.go, actors/serde/serialization.go, support/mock/mockrt.go
This should go in after `frrist/multisig-unit-test`
=> tests: add multisig approve tests

actors/builtin/shared.go, actors/builtin/storage_market/storage_market_actor.go, actors/builtin/storage_market/storage_market_actor_state.go, actors/builtin/storage_miner/storage_miner_actor.go, actors/builtin/storage_miner/storage_miner_actor_state.go, actors/builtin/storage_power/policy.go, actors/builtin/storage_power/storage_power_actor.go, actors/builtin/storage_power/storage_power_actor_state.go, actors/runtime/indices/indices.go, actors/runtime/runtime.go, actors/util/actor_util.go
Only minor semantic changes, like replacing some assertions with errors.
This is a prefactor to finishing of the power actor data and structure.
=> Cosmetic re-arrangements to miner state and shared code.

actors/abi/big/int.go, actors/builtin/storage_power/storage_power_actor.go, actors/builtin/storage_power/storage_power_actor_state.go, actors/util/adt/balancetable.go, actors/util/adt/map.go, actors/util/adt/store.go
This same structure will then be usable in the market actor.
=> Implement BalanceTable map specialization and use in power actor

actors/abi/bitfield.go, actors/builtin/methods.go, actors/builtin/payment_channel/payment_channel_actor.go, actors/builtin/payment_channel/payment_channel_actor_state.go, actors/runtime/indices/indices.go, actors/runtime/runtime.go, go.mod
Add methods for payment_channel actor
=> add payment channel actor methods

actors/builtin/storage_market/storage_market_actor_state.go, actors/builtin/storage_miner/storage_miner_actor.go, actors/builtin/storage_miner/storage_miner_actor_state.go, actors/builtin/storage_power/storage_power_actor.go, actors/crypto/randomness.go, actors/util/assert.go
=> Replace IMPL_FINISH with TODO.

actors/builtin/storage_market/cbor_gen.go, actors/builtin/storage_market/storage_market_actor.go, gen/gen.go
=> Return deal ids from publish storage deals

actors/abi/cbor_gen.go, actors/abi/sector.go, actors/builtin/storage_miner/cbor_gen.go, actors/builtin/storage_miner/storage_miner_actor.go, actors/builtin/storage_miner/storage_miner_actor_state.go, actors/builtin/storage_power/storage_power_actor_state.go, actors/runtime/runtime.go, actors/util/adt/store.go, gen/gen.go
This is based on #93 - merge that first.
=> Use HAMT for pre-committed sectors. CBOR-gen for miner actor state.

actors/builtin/multisig/multisig_test.go, actors/builtin/storage_power/storage_power_test.go, support/mock/mockrt.go
The actual bug being fixed: https://github.com/filecoin-project/specs-actors/compare/frrist/fix-send-mock?expand=1#diff-cd5bdafeb533402e215490cb65b89370R215
=> fix: expected message compare and tests

actors/builtin/storage_miner/storage_miner_actor.go, actors/builtin/storage_miner/storage_miner_actor_state.go
Simpler control flow, merged some repeated state reads/transactions into one.
=> Partial cleanup of the miner actor.

actors/builtin/payment_channel/cbor_gen.go, actors/builtin/payment_channel/payment_channel_actor.go, actors/builtin/payment_channel/payment_channel_actor_state.go
=> Replace paych lanes map with sorted array

actors/abi/big/int.go, actors/abi/big/int_test.go, actors/crypto/randomness.go
=> Big Int binary (un)marshal

actors/builtin/init/cbor_gen.go, actors/builtin/init/init_actor.go, actors/builtin/init/init_test.go, support/mock/mockrt.go
=> Remove network name from runtime in favour of Init constructor parameter

actors/abi/cbor_gen.go, actors/builtin/miner/cbor_gen.go, actors/builtin/paych/cbor_gen.go, gen/gen.go
This noise was confusing other changes.
=> Regenerate CBOR encoding after changes to structures

actors/util/adt/map.go
=> Set HAMT bitwidth=5 for all maps.

actors/builtin/market/cbor_gen.go, gen/gen.go
Was missing from code gen, noticed working here: https://github.com/filecoin-project/chain-validation/blob/master/chain/market.go#L25
=> add HandleExpiredDealsParams to gen.go

actors/builtin/methods.go, actors/builtin/miner/miner_actor.go, actors/builtin/miner/miner_state.go
Exported state methods for use in impls (we should do this in all of them).
=> Implement miner ChangePeerID method. Export state methods.

actors/builtin/miner/cbor_gen.go, actors/builtin/miner/miner_actor.go, actors/builtin/system/system_actor.go, gen/gen.go
It calls a few things in implicit messages, and the vm expects it to exist is state tree.
See #165
=> Define system actor

actors/builtin/miner/cbor_gen.go
forgot to run codegen on #182  :man_facepalming:. This PR runs the code gen required to generate marshaling methods for ChangePeerIDParams
=> gen: generate the cbor interfaces

actors/builtin/paych/paych_actor.go, actors/builtin/paych/paych_test.go, support/mock/mockrt.go
Remaining tests for payment channel Actor:
* More tests for UpdateChannelState, including lane Merges and Extra
* Collect
* Settle
Fix a copy-paste bug in Collect.
=> More payment channel Actor tests

actors/builtin/init/init_actor.go, actors/builtin/init/init_test.go
- add test to init actor for multisig creation
=> fix bug preventing creation of multisig actor

actors/builtin/market/market_actor.go
A send got moved within the state lock acquire so go-filecoin's runtime couldn't execute deal publish.  This PR moves the send outside of the lock aligning actor code with spec validation rules.
=> Move send above state lock

actors/builtin/reward/reward_actor.go, actors/builtin/reward/reward_test.go, support/mock/mockrt.go
This fix is blocking chain-validation progress and is a subset of #205
=> correct assertion in reward actor

actors/builtin/multisig/multisig_actor.go, actors/builtin/multisig/multisig_test.go
=> fix: prevent ms actor with 0 signers

actors/builtin/miner/cbor_gen.go, gen/gen.go
add code gen for CheckSectorProvenParams
=> generate CBOR marshal for CheckSectorProvenParams

actors/abi/big/int.go, actors/abi/primitives.go, actors/abi/sector.go, actors/abi/sector_test.go, actors/builtin/market/market_actor.go, actors/builtin/miner/policy.go, actors/builtin/paych/paych_actor.go, actors/builtin/power/policy.go, actors/util/adt/balancetable.go
Also add big.NewIntUnsigned to avoid possible loss converting through int64
=> Add string methods for sectorsize and other uints

actors/builtin/cron/cron_actor.go, actors/builtin/cron/cron_test.go, actors/builtin/market/market_actor.go, actors/builtin/market/market_test.go, actors/builtin/miner/miner_actor.go, actors/builtin/miner/policy.go
FYI @frrist @shannonwells @ingar
=> Accept nil as empty params for Send(); document interpretation of PoSt lookback.

actors/builtin/power/power_actor.go, actors/builtin/power/power_state.go
It's a bit late so i might not be thinking through this right, but we werent adjusting the total network power up or down on faults. This should roughly do the thing.
=> handle total network power in the presence of faults

actors/builtin/power/power_actor.go, actors/builtin/power/power_test.go
Test to ensure that cron-events from null rounds are executed.
Amendment to #243
=> power: add cron null round test

actors/builtin/miner/miner_state.go
This was requested by other implementers, apparently peer IDs are serializing as technically invalid cbor (random bytes are not valid utf-8, therefore not valid cbor).
Closes #263
=> move peer ID serialization to byte arrays

actors/abi/cbor_gen.go, actors/abi/sector.go, actors/builtin/miner/miner_actor.go, actors/builtin/miner/policy.go, actors/runtime/runtime.go, gen/gen.go, support/mock/mock_syscaller.go
=> first pass at updating abi/sector to for window and winning post

actors/builtin/miner/miner_actor.go, actors/builtin/miner/policy.go, actors/runtime/runtime.go, support/mock/mock_syscaller.go
Working to get tests in https://github.com/filecoin-project/go-filecoin/pull/3983 to pass. 
Will update and merge it once this one is merged.
=> update consensusFault method

actors/builtin/market/market_test.go, actors/builtin/miner/miner_internal_test.go, actors/builtin/miner/miner_state.go, actors/builtin/miner/miner_test.go, actors/builtin/power/power_test.go, support/mock/mockrt.go
Basic setup for miner actor tests.
=> Miner test harness

actors/builtin/miner/miner_actor.go
Remove adding new LockedFund in SectorExpiration.
The only operation in ExtendSectorExpiration is changing sector duration.
=> Remove adding LockedFund in ExtendSectorExpiration

actors/builtin/miner/miner_state_test.go
Needs a rebase on #312 once it lands in master.
=> Increase miner vesting test coverage

actors/builtin/miner/miner_state.go
I need to call this locally to compute how much collateral i need to send in, it would be great if each of those calls didnt trigger extra data being created
=> Add method to get vested funds without making mutations

actors/builtin/miner/miner_actor.go, actors/builtin/miner/miner_state.go
please ignore my being OCD about the err assignments.
Line 1008 is the fix, I think this is the only place this is needed
=> clear new sectors bitfield when assigning sectors

actors/builtin/power/policy.go
This is still not the final mainnet value, but a value for interim networks.
FYI @zixuanzh
=> Set ConsensusMinerMinPower to 10TiB

actors/builtin/miner/deadlines.go, actors/builtin/miner/miner_actor.go
The prior code erroneously checked whether the _current_ deadline had passed or was within its exclusion window, not the deadline that the declaration targets. 
Closes #342
=> Fix checking of fault/recovery declaration deadlines

actors/builtin/miner/miner_test.go, support/mock/mockrt.go
I had these half done from earlier, have finished them off now as part of getting the setup in place for testing window post and fault scenarios.
FYI @frrist
=> Unit tests for prove commit sector

actors/builtin/reward/reward_state_test.go
To prevent [this confusion](https://github.com/filecoin-project/specs-actors/pull/345#discussion_r420477068) from coming up in the future, I'm adding documentation to the test vectors for the reward function.
I'm also flagging that the **test vectors depend on SecondsPerEpoch=30**, which I understand from @anorth is now incorrect. When this is being fixed, please feel free to ping me to generate a new set of ground-truth `mintingTestVectors`.
=> document reward minting function tests

actors/builtin/miner/miner_actor.go, actors/builtin/miner/miner_state.go, actors/builtin/miner/miner_test.go, support/mock/mockrt.go
This test demonstrates a single window post. That's not much, but it means all the helpers and mock/expectations are now in place for testing the many and varied scenarios we want to. I expect some of the in-line code to be factored out of this test for re-use from higher level test "scripts".
=> First miner actor Window PoSt test

actors/builtin/reward/cbor_gen.go
I forgot to re-run cbor-gen in #366
=> cbor-gen for reward actor state

actors/builtin/miner/miner_actor.go
This PR allows for CC sectors to be upgraded to sectors with deals and extend the sector lifetime at the same time. This step is crucial in storing useful data on Filecoin as miners can first prove capacity to the network in the absence of storage demand and later upgrade their sectors when demand arrives. Currently, this will involve resealing and go through the same PublishStorageDeals, PreCommit, and ProveCommit workflow. There are plans to make it more efficient and cost effective post Mainnet launch. 
Currently, miners will have to put up new pledge collateral. We would like to reduce the pledge collateral required here but that will require us landing penalty calculation first and we can piggyback on the calculation there.
=> CC upgrade

actors/builtin/miner/policy.go
=> update finality number

actors/builtin/reward/reward_actor.go, go.mod, go.sum
There was a slight mismatch between what was designed and what was implemented, resulting in known unintended behavior. Here's the mathematical specification of the design,
=> Update CumsumRealized Calculation

actors/builtin/miner/deadlines.go
Consider leaving first Window PoSt proving deadline empty #389
=> Leaving first Window PoSt proving deadline empty

actors/builtin/miner/miner_actor.go
This PR is meant to address #402.  It follows the advice in the comment.  I am low context on this code so keep that in mind when reviewing.
Closes #402.
=> Count partitions between 0 and sinceDeadline

actors/builtin/miner/cbor_gen.go, actors/builtin/miner/miner_actor.go, actors/builtin/miner/miner_state.go, actors/builtin/miner/miner_state_test.go, actors/builtin/miner/miner_test.go, actors/builtin/power/cbor_gen.go, actors/builtin/power/power_actor.go, actors/builtin/shared.go, gen/gen.go, go.mod
=> add ChangeMultiaddrs to miner actor

actors/builtin/miner/miner_actor.go
Thanks @austinabell for [pointing out](https://github.com/austinabell/specs-actors/commit/23f9f7b4596fd5278948ea20997a31b84d6315f0) some of the unhandled errors.
=> Add explanatory comments and fix some unhandled errors.

README.md
We don't actually do what the README currently describes, hence this change.
cc @magik6k
=> Describe pragmatic versioning approach

actors/builtin/miner/miner_test.go
- Fixes incorrect building of runtime outside of the `t.Run()` blocks that use it, because this passes the wrong `testing.T` instance.
- Removes `rt.Reset()` and adds missing `rt.Verify()`.
The tests will pass after #482 lands, which cleans up empty sector expiration epochs.
=> Fix up testing patterns for extending sector expirations

actors/builtin/multisig/cbor_gen.go, actors/builtin/multisig/multisig_actor.go, actors/builtin/multisig/multisig_state.go, actors/builtin/multisig/multisig_test.go
To prevent devops199ing yourself by accident
closes #92
=> Enforce useable approval number

actors/builtin/multisig/cbor_gen.go, actors/builtin/multisig/multisig_actor.go, actors/builtin/multisig/multisig_test.go, actors/runtime/runtime.go, gen/gen.go, support/mock/builder.go, support/mock/mockrt.go
=> return exitcode and retval from Approve & Propose

actors/builtin/miner/policy.go
=> Set fault declaration cutoff to 10 epochs before challenge is available

actors/builtin/multisig/multisig_actor.go, actors/builtin/multisig/multisig_test.go
Closes https://github.com/filecoin-project/specs-actors/issues/497
=> Multisig: Do not allow duplicate signers

actors/builtin/multisig/multisig_actor.go, actors/builtin/multisig/multisig_test.go
=> Multisig: Explicitly decrease threshold in RemoveSigner

actors/builtin/multisig/multisig_actor.go, actors/builtin/multisig/multisig_state.go, actors/builtin/multisig/multisig_test.go
=> Multisig: Approve transaction if threshold already met

actors/builtin/miner/miner_test.go, support/testing/address.go
De-duplicate some code. More coming soon.
@acruikshank please land this for me if LGTY.
=> More concise miner test setup

actors/builtin/multisig/multisig_test.go
=> Multisig: Test that ONLY the proposer can cancel a transaction

actors/builtin/market/market_test.go
=> Test for publishing a deal after activating a previous deal with a start epoch in the future

actors/builtin/market/market_test.go
Closes #465  and introduces the utils to write tests for the market actor.
@anorth Let's get this in. Will be really helpful in writing tests for the other PRs.
=> Tests for Market Actor

actors/builtin/cron/cbor_gen.go, actors/builtin/market/cbor_gen.go, actors/builtin/market/market_actor.go, actors/builtin/market/market_state.go
Closes #531 
@anorth Needs tests. Will put in along with the tests for the other PRs as they will share the test utilities.
=> Keep track of locked funds

actors/builtin/market/market_actor.go, actors/builtin/market/market_state.go, actors/builtin/market/market_test.go, actors/builtin/market/types.go
Closes #529 
@anorth Should the scope of this PR expand to write tests for `OnMinerSectorsTerminate` too so we can test changes like these or do you want to wait out and roll it into the issue we have to write tests for the Market Actor.
=> Do not abort if deal is not found

actors/builtin/market/market_actor.go, actors/builtin/market/market_state.go, actors/builtin/market/types.go
Closes #462
@anorth 
Also, discovered a bug wherein we delete the deal proposal but not the deal state.
=> Do not slash expired deals and also delete deal state when deal proposal is deleted

actors/builtin/power/power_actor.go, actors/builtin/power/power_test.go
=> Defensive cron error handling

actors/builtin/miner/deadlines.go, actors/builtin/miner/miner_actor.go, actors/builtin/miner/miner_state.go
This patch set contains a set of cleanups/comments/questions from reading SubmitWindowedPoSt. None of these are critical, but they provide a nice way to ask questions.
=> SubmitWindowedPoSt cleanups

actors/abi/big/int.go, actors/abi/big/int_test.go, actors/builtin/market/market_actor.go, actors/builtin/market/market_state.go, actors/builtin/market/market_test.go, support/mock/builder.go, support/mock/mockrt.go
Closes #542 .
Tests for multiple calls to publish with different providers in the next PR.
=> Tests for PublishStorageDeals

actors/builtin/miner/miner_actor.go
Prefactor cleaning up `ConfirmSectorProofsValid` before making it more robust to individual sector failures.
Initial traversal over sector number now only does error prone operations over individual sectors and gathers precommits into a slice.  Upcoming robustness work will drop precommits that fail without failing `ConfirmSectorProofsValid`.  This restructure allows batching
1. Power and pledge update calls to power actor into one call
2. All state updates into one transaction (in a loop)
3. Fund accounting operations into one balance transfer per operation
This should close #476 and #475
=> Batch ConfirmSectorProofsValid updates

actors/builtin/market/market_test.go, support/mock/mockrt.go
@anorth Tagging you as this is a small continuation of the previous PR for market tests.
This PR introduces tests for `PublishStorageDeals` with different providers.
=> Market: Test Publish with different providers

actors/builtin/miner/miner_state.go
=> Deterministically update modified fault epochs in-order when removing faults

actors/builtin/miner/expirations.go, actors/builtin/miner/expirations_test.go, actors/builtin/miner/miner_actor.go, actors/builtin/miner/miner_state.go, actors/builtin/miner/miner_state_test.go
In the process of implementing #572, I wanted to batch sector expiration updates and got a bit carried away.
=> Batch sector operations

actors/builtin/miner/miner_actor.go, actors/builtin/miner/miner_test.go
Ignore the termination if:
1. The sector doesn't exist.
2. We're terminating it due to an expiration, but it hasn't actually expired.
fixes #513
TODO:
=> Handle already terminated sectors in termination logic

actors/builtin/power/power_actor.go
=> Charge gas for SubmitPoRepForBulkVerify

actors/builtin/market/market_actor.go, actors/builtin/market/market_test.go
=> Add balance should not be called with negative value

actors/builtin/methods.go, actors/builtin/miner/miner_actor.go, actors/builtin/miner/miner_test.go, actors/builtin/reward/cbor_gen.go, actors/builtin/reward/reward_actor.go, actors/builtin/reward/reward_state.go, actors/builtin/reward/reward_test.go
Closes #374.  
FYI @magik6k @arajasek see latest comment on that issue for tips on integrating into lotus `chain/gen`.  
FYI @Kubuxu these refactoring changes should be orthogonal to logic changes in minting function etc but one of us will have to handle conflicts.
=> Calculate first block reward on construction

actors/builtin/multisig/multisig_actor.go, actors/builtin/multisig/multisig_test.go
=> Multisig: Resolve address before comparing

actors/builtin/market/market_actor.go, actors/builtin/market/market_test.go
Closes #589 AND #603 .
Also, as discussed offline with @anorth , we don't need to check for negative balance in the `AddBalanceCall` as the Runtime will enforce it.
=> Market: Miner fixes and tests

actors/builtin/market/market_actor.go, actors/builtin/market/market_state.go
=> Market: Persist updates to state in CronTick.

actors/abi/big/int.go, actors/abi/big/int_test.go, actors/builtin/market/market_actor.go, actors/builtin/market/market_state.go, actors/builtin/market/market_test.go
Tests for the CronCallback.
Also Closes #613 .
Also Closes #574 .
=> Market: Tests for CronTick

actors/builtin/power/power_state.go
=> Export min power func

actors/builtin/miner/miner_state.go
The AMT caches on read internally so we can save quite a few loads by _not_ throwing the array away after every sector info load. This is especially important when loading ranges of sequential sectors (which should be a pretty common case).
=> Avoid reloading AMT for every sector loaded

actors/builtin/power/power_state.go
Resolves issue mentioned [here](https://github.com/filecoin-project/specs-actors/pull/634/files#r453532504)
=> Fix power check off by one

actors/builtin/reward/reward_actor.go, actors/builtin/reward/reward_state.go, actors/builtin/reward/reward_test.go
=> Clamp reward, test, update docs

actors/abi/big/int.go, actors/abi/big/int_test.go, actors/builtin/market/market_actor.go, actors/builtin/market/market_balances.go, actors/builtin/market/market_state.go, actors/builtin/market/market_test.go, actors/util/adt/balancetable.go, actors/util/adt/balancetable_test.go
=> Market: Refactor for performance

actors/builtin/miner/cbor_gen.go, actors/builtin/miner/deadline_assignment.go, actors/builtin/miner/deadline_assignment_test.go, actors/builtin/miner/deadline_state.go
See the code for a description of how this works.
fixes #685
TODO
=> Implement smarter deadline assignment algorithm

actors/abi/sector.go, actors/builtin/miner/miner_actor.go
Part of https://github.com/filecoin-project/specs-actors/issues/604
=> validate miner params

actors/builtin/verifreg/verified_registry_actor.go, actors/builtin/verifreg/verified_registry_state.go, actors/builtin/verifreg/verified_registry_test.go
For #278 AND #682 .
More tests in a followup PR.
=> VerifReg: Tests and de-duplicate reads 

actors/builtin/multisig/multisig_actor.go, actors/builtin/multisig/multisig_state.go
=> MultiSig: Remove duplicate reads

actors/builtin/power/power_actor.go, actors/builtin/power/power_state.go, actors/builtin/power/power_test.go
=> Power: Dedup HAMT reads

actors/builtin/market/market_actor.go, actors/builtin/market/market_balances.go, actors/builtin/market/market_test.go, actors/util/adt/balancetable.go, actors/util/adt/balancetable_test.go
=> Market: Remove Zero balance accounts

actors/builtin/verifreg/verified_registry_test.go
Closes #682 .
Tests for `UseBytes` and `RestoreBytes`.
=> VerifReg: finish tests

actors/builtin/miner/deadline_state.go
Cherry picked from https://github.com/filecoin-project/specs-actors/pull/750 to avoid any further merge conflicts.
(will be tested in #750)
=> Update live sectors when terminating sectors

actors/builtin/codes.go
(low priority drive-by change)
=> DRY up built-in actor CID logic

actors/util/adt/array.go
Cherry picked from https://github.com/filecoin-project/specs-actors/pull/750
=> Fast path iterating over deferred cbor objects

actors/builtin/miner/miner_actor.go
fixes #753
I'm punting on tests as I believe we need a framework for testing input bounds.
=> Fix deadline index check

actors/builtin/power/power_actor.go, actors/builtin/power/power_test.go
=> StoragePower: OnConsensusFault incorrectly zeroes out miner power

actors/builtin/market/market_actor.go, actors/builtin/market/market_state.go, actors/builtin/market/market_test.go
Closes #765 
Closes #766 .
Closes #767 .
Closes #768 .
Closes #771 .
=> Market: Audit Fixes

actors/builtin/miner/partition_state_test.go, go.mod, go.sum
=> Support max-sized partitions

actors/builtin/paych/paych_actor.go, actors/builtin/paych/paych_test.go
=> Payment: Remove actor for collect

actors/builtin/miner/miner_actor.go, actors/builtin/miner/miner_test.go
=> Allow up to the max sector number in precommit

actors/builtin/power/power_actor.go, actors/builtin/power/power_state.go, actors/builtin/power/power_test.go
For #811. 
@anorth The bulk of tests in the followup PR will be for the cron processing as that is the one missing deep tests.
=> Powert : Tests

actors/builtin/reward/cbor_gen.go, actors/builtin/reward/reward_actor.go, actors/builtin/reward/reward_state.go, actors/builtin/reward/reward_test.go
=> Track awarded block reward in actor state

actors/builtin/market/market_actor.go, actors/builtin/market/market_test.go, actors/builtin/market/policy.go, actors/builtin/miner/policy.go, actors/builtin/network.go
Closes #738  
WIP since all tests are broken.  Implementation already feels solid however.
=> Minimum Deal Provider Collateral

actors/builtin/miner/cbor_gen.go, actors/builtin/miner/miner_actor.go, actors/builtin/miner/miner_state.go, actors/builtin/miner/miner_state_test.go, go.mod, go.sum
~Depends on https://github.com/filecoin-project/go-bitfield/pull/43~
TODO
fixes #451
=> Prevent sector number reuse

actors/builtin/miner/deadline_state_test.go, actors/builtin/miner/expiration_queue.go, actors/builtin/miner/expiration_queue_test.go, actors/builtin/miner/partition_state.go
=> Make sure we don't generate empty expiration queue entries

actors/builtin/power/power_state.go, actors/builtin/reward/reward_state.go, actors/util/smoothing/alpha_beta_filter.go, actors/util/smoothing/testing.go
Closes #823 
@ZX any ideas for good tests that will demonstrate that we are in the right range of initial values?
=> Use correct initial filter estimates

actors/util/smoothing/alpha_beta_filter.go
Closes #854 
FYI @nicola for param change
=> Update alpha and beta to recommended values

actors/builtin/miner/cbor_gen.go, actors/builtin/miner/miner_actor.go, actors/builtin/miner/miner_internal_test.go, actors/builtin/miner/miner_state.go, actors/builtin/miner/miner_state_test.go, actors/builtin/miner/miner_test.go, actors/builtin/miner/monies.go, actors/builtin/miner/monies_test.go
Closes #822 
Currently WIP because we aren't correctly storing one br and twenty br in state to compute termination fees.
=> Multipliers become projection days for all fees related to BR

actors/builtin/market/market_actor.go, actors/builtin/market/market_balances.go, actors/builtin/market/market_state.go
=> Market actor cleanups

actors/builtin/multisig/multisig_actor.go
It's not clear that `requester` must be an ID address where as `params.to` can be either, so let's at least make the error clear
=> proposal requester must be ID addresses err msg

actors/builtin/reward/reward_actor.go, actors/builtin/reward/reward_test.go
=> AwardBlockReward validates params, better tests

actors/builtin/reward/reward_calc.py, actors/builtin/reward/reward_logic.go, actors/builtin/reward/reward_state.go
This only affects the BaselineExponent.
=> Truncate all constants instead of rounding

actors/builtin/miner/miner_actor.go, actors/builtin/miner/miner_test.go, actors/runtime/runtime.go, support/mock/mockrt.go
Ref @nicola's discussion on GetRandomnessFromBeacon and GetRandomnessFromTickets
@anorth edit:
Documenting the behaviour being implemented here before landing it.
- Seal: ticket chain
- PoRep: beacon chain
- Window PoSt: beacon chain
This ties the seal to a particular chain, but not the subsequent PoRep or PoSts.
=> distinguish between randomness from drand vs ticket chain randomness

actors/builtin/miner/miner_actor.go, actors/builtin/miner/miner_test.go
=> Miner: Handle a pending key change that has been replaced

actors/crypto/randomness.go, actors/runtime/runtime.go
These clarifications mostly inspired by @wadealexc's questions.
I also filed a number of [chain validation issues](https://github.com/filecoin-project/chain-validation/issues) for new tests.
=> Clarifications to runtime interface documentation

actors/builtin/miner/cbor_gen.go, actors/builtin/miner/miner_actor.go, actors/builtin/miner/miner_state.go, actors/builtin/miner/miner_state_test.go, actors/builtin/miner/miner_test.go
=> Miner: Efficiently expire pre-committed sectors

actors/builtin/paych/paych_actor.go, actors/builtin/paych/paych_test.go
=> Fix ignored exit codes in paych, and funky tests

actors/builtin/miner/deadline_state.go, actors/builtin/miner/miner_actor.go
=> Small cleanups

actors/builtin/verifreg/verified_registry_actor.go
Very small change, felt this was easiest way to note change
=> Update verifreg check to not unmarshal unnecessarily

actors/builtin/multisig/multisig_actor.go, actors/builtin/multisig/multisig_test.go
=> Document and test the fact that the proposal hash is optional

actors/builtin/market/market_actor.go, actors/builtin/market/market_state.go, actors/builtin/market/market_test.go, actors/crypto/randomness.go
=> Market: Randomize first cron tick post the startepoch for deal processing

actors/builtin/miner/miner_test.go, support/testing/pid.go
Closes #479 
- Simple ChangePeerID happy path test
- A few new sector commitment edge case tests
- Aggregate some test ideas from todo and new test ideas into linked issue
Worker changes already handled elsewhere
=> More Miner tests

actors/builtin/miner/miner_actor.go, actors/builtin/miner/miner_test.go, go.mod, go.sum, support/mock/mockrt.go
Brings in address length limits.
=> Update go-address library

actors/builtin/cbor_gen.go, actors/builtin/market/market_actor.go, actors/builtin/miner/cbor_gen.go, actors/builtin/miner/miner_actor.go, actors/builtin/miner/miner_state.go, actors/builtin/miner/miner_test.go, actors/builtin/power/cbor_gen.go, actors/builtin/power/power_actor.go, actors/builtin/shared.go, support/mock/mockrt.go
=> Miner: Multiple control addresses

actors/builtin/cbor_gen.go, actors/builtin/miner/cbor_gen.go, actors/builtin/paych/cbor_gen.go, actors/builtin/paych/paych_actor.go, actors/builtin/paych/paych_state.go, actors/builtin/paych/paych_test.go, actors/builtin/power/cbor_gen.go, actors/builtin/reward/cbor_gen.go, actors/puppet/cbor_gen.go, go.mod, go.sum
Still a bit WIP, but should be most of the way there.
=> use an AMT for lane tracking

actors/builtin/multisig/multisig_test.go, actors/builtin/verifreg/verified_registry_actor.go, actors/builtin/verifreg/verified_registry_test.go
For #730 AND Closes #556.
@anorth To review after  #912  goes in.
=> VerifReg: Resolve Verifier and Client Addresses

actors/builtin/miner/expiration_queue.go
I'm not sure if it's really worth merging this given that we'd need some major time travel to excersize this, but the old code was misleading.
fixes #957
=> Return an error if we try to re-reschedule expirations

actors/builtin/miner/miner_actor.go
=> No eligibility checks on prove commit

actors/builtin/miner/monies.go, actors/builtin/miner/monies_test.go
Closes #938 
FYI @zixuanzh @davidad
=> Clamp BR at zero when it dips negative

actors/builtin/miner/miner_actor.go, actors/builtin/miner/miner_test.go, actors/builtin/miner/policy.go
=> Miner: Limit control addresses

actors/builtin/miner/miner_actor.go, actors/builtin/miner/miner_test.go, actors/test/miner_scenario_test.go
=> Miner:  Do not send call to market.ActivateDeals if there are no deals

actors/builtin/miner/miner_actor.go, actors/builtin/miner/miner_test.go
=> Restrict AddLockedFunds caller to reward actor

actors/builtin/paych/paych_actor.go, actors/builtin/paych/paych_test.go
Closes #1063 
FYI @dirkmc @whyrusleeping
=> Vouchers disallowed after channel state settled

actors/builtin/miner/deadline_state_test.go, actors/builtin/miner/miner_test.go
This doesn't cover all possibilities, but I believe we've hit the point of diminishing returns.
fixes #849
=> Improve coverage of illegal arguments

actors/crypto/signature.go, actors/crypto/signature_test.go
Adding tests before factoring it out to go-shared-types
=> Test signature CBOR

actors/builtin/paych/paych_actor.go, actors/builtin/paych/paych_test.go
Fixes https://github.com/filecoin-project/specs-actors/issues/1120
=> paych - resolve voucher channel address to ID address

actors/states/election.go, actors/states/election_test.go
Closes #1128
FYI @nicola @arajasek
=> Remove election condition of initial pledge above consensus fault penalty

actors/builtin/multisig/multisig_state.go, actors/builtin/multisig/multisig_test.go
=> Fix truncating division in multisig vesting

actors/builtin/market/market_actor.go, actors/builtin/market/market_state.go, actors/builtin/market/policy.go
=> Export market policy functions

actors/migration/miner.go
The testnet chain state violates miner balance invariants -- we've heard about this for a while now.  These violations make our current migration code fail.  The problem starts somewhere between epoch 10k and 15k.
=> Handle inStates that break our assumptions

actors/builtin/miner/deadline_state.go
closes #1070
We would like to ensure invariant violations that occur in deadlines are caught and reported as soon as possible. This PR adds a check that the deadline's `LiveSectors` never exceeds its `TotalSectors` and that it never has `FaultyPower` less than zero any time a deadline is updated.
1. Add `Deadline.ValidateState`.
2. Call `ValidateState` in `Deadlines.UpdateDeadline` and exit on error.
cc @wadeAlexC
=> add deadline invariant check

actors/migration/top.go
Utilities for some sanity check tooling I'm trying to build.
=> Add helpers for measuring debt transfer safety

actors/migration/account.go, actors/migration/cron.go, actors/migration/init.go, actors/migration/market.go, actors/migration/miner.go, actors/migration/multisig.go, actors/migration/paych.go, actors/migration/power.go, actors/migration/reward.go, actors/migration/system.go, actors/migration/top.go, actors/migration/verifreg.go
A prefactor for #1171, to aid the miner's balance transfer needs.
=> Add balance and balance delta to migrator struct

actors/migration/nv3/migrators.go, actors/migration/nv3/miner.go, actors/migration/nv3/reward.go, actors/migration/nv3/top.go
This is the type signature needed by the upcoming #1180, which I'm landing ahead for Lotus integration.
FYI @acruikshank
=> Update migration type signatures for upcoming miner state migration

actors/migration/reward.go
=> Revert resetting reward actor baseline value, already happening on release/v0.9 at nv=3

actors/migration/miner_corrections.go, actors/migration/test/correct_cc_upgrade_then_fault_scenario_test.go, actors/migration/top.go, go.mod
Remove parallelism for thread safety
We'll bring it back after it is fixed up according to review comments on #1203
=> Remove concurrency for now

actors/builtin/miner/deadline_state_test.go, actors/builtin/miner/miner_test.go, actors/builtin/miner/testing.go, actors/states/check.go
=> Extract miner deadline state checks for re-use

.circleci/config.yml
=> use larger CI machines

actors/test/committed_capacity_scenario_test.go
closes #1184
We have observed that attempting to skip a cc upgraded sector causes an abort in SubmitWindowedPoSt in v0.9. This is related to but different from the cc upgrade then fault issues. It was unclear whether this problem was fixed by fixes to expiration queue logic. This PR demonstrates that it was.
1. Add scenario test case for skipping an upgraded sector that asserts success.
=> confirm upgraded sectors can be skipped with v2 actors

actors/builtin/miner/miner_actor.go, actors/builtin/miner/miner_state.go, actors/builtin/miner/miner_test.go, actors/builtin/miner/policy.go, actors/builtin/singletons.go
This is just part of an effort to remove ~all assertions (#1161), but a useful increment.
I think this subsumes #1195.
=> Replace some miner actor assertions with aborts.

.circleci/config.yml, Makefile, actors/migration/test/parallel_migration_test.go, actors/migration/top.go, support/ipld/store.go
Move migrations global to MigrateStateTree scope
=> Fix MigrateStateTree to be threadsafe

support/vm/invocation_context.go
=> modify vm method bug

actors/builtin/sector.go
This removes use of the `RegisteredPoStProof.RegisteredSealProof()` method, which we can then remove because that bijection shouldn't really exist.
=> [v0.9] Attach PoSt proof policy to the PoSt proof type instead of seal proof type.

actors/builtin/miner/miner_actor.go, actors/builtin/miner/miner_test.go
Fixes #1243.
In the issue I stated that a good fix would involve refactoring to push deadline state manipulation down. I opted not to do this here in order to make the version check easier, and avoid the possibility of introducing some other functional change not guarded by that check. In actors v3 we can remove the version check and refactor.
FYI @Stebalien
=> Fix ExtendSectorExpiration to update deadline expiration queue.

actors/builtin/multisig/multisig_actor.go, actors/builtin/multisig/multisig_test.go
=> Multisig LockBalance validates non-negative amount

actors/builtin/market/market_test.go, actors/builtin/multisig/multisig_test.go, support/mock/mockrt.go, support/mock/mockrt_state_test.go
As requested in #1028.
@acruikshank @ZenGround0 what do you think is the marginal value of adding the same thing to the scenario VM? It's not too hard, but may slightly impact performance. Are there other more valuable things to do first?
=> Mock runtime detects illegal modification of read-only state

actors/test/terminate_sectors_scenario_test.go, support/agent/cases_test.go, support/agent/miner_agent.go, support/agent/sim.go, support/ipld/store.go, support/testing/address.go, support/vm/invocation_context.go, support/vm/stats.go, support/vm/testing.go, support/vm/vm.go
work towards #993
We have pretty good unit testing to cover actor behavior, and now have some scenario tests to cover specific inter-actor processes. We have not had any way to run larger scale network processes without integrating the actor code into a test network. This PR leverages the scenario test VM to introduce a simulation framework that models miner behavior.
Currently the simulation can:
1. Create miners a configured rate.
2. Models these miner's behavior with a `MinerAgent` that precommits sectors randomly at a given rate, prove commits them within the correct window, and then PoSt them when necessary.
3. Pays block rewards
4. Runs cron each tick.
TODO:
1. Deals / CC upgrades
2. Per-miner configuration to simulate a mix of big and small miners
3. Disk backed store to support …
=> First pass at an agent simulation testing framework

support/ipld/cbor.go, support/mock/mockrt.go, support/vm/invocation_context.go
The same pattern as the mock runtime.
Closes #1028
=> Scenario VM detects illegal modification of read-only state

actors/builtin/miner/miner_actor.go
=> optimize ProveCommitSector use StateReadonly

actors/builtin/miner/deadline_state.go, actors/builtin/miner/deadline_state_test.go, actors/builtin/miner/miner_actor.go, actors/builtin/miner/sector_map.go, actors/builtin/miner/sector_map_test.go
Make sure to sort by value, not index.
=> fix iteration non-determinism

actors/builtin/miner/miner_actor.go
=> fix a log error

docs/post-mortem-jan-21.md
@Stebalien this is about ready but could use a quick look over before merging.
=> Post Mortem

actors/builtin/miner/bitfield_queue_test.go, actors/builtin/miner/miner_actor.go, actors/builtin/miner/miner_state.go, actors/builtin/miner/miner_state_test.go
This is broken out (2 of 2) of my work on #1241, batching pre-commits.
=> Batch writing precommit on-chain infos and expirations

actors/builtin/verifreg/verified_registry_actor.go
Minor typo in an error statement
=> Fix minor typo

actors/builtin/miner/miner_actor.go
Looks like the comments weren't updated from an earlier [commit](https://github.com/filecoin-project/specs-actors/commit/59d00ed5b462d272f61f644b83786d5b972a2b30), so I've updated them to match the current code.
=> Update outdated comments

actors/builtin/miner/partition_state.go, actors/test/commit_post_test.go, actors/test/common_test.go, support/vm/testing.go
This test brings together batched/aggregated sector onboarding all together, demonstrating the flow we expect growing miners to use.
=> Scenario test for batched pre-commit and aggregate prove-commit in sequence and interleaved

actors/builtin/miner/miner_actor.go, actors/builtin/miner/miner_commitment_test.go, actors/builtin/miner/miner_test.go, support/mock/mockrt.go
Technically, the balance invariant check would catch this. But that'll error with a very scary 1000 "something is very wrong" error code.
(TODO: test)
=> fix: make sure we have enough funds to pay the aggregate fee

actors/builtin/market/market_test.go
Sanity checking that publishing storage deals assigns cron processing to deals as expected with new offset changes.
=> Test deterministic offset

actors/migration/nv15/test/miner_migration_test.go, actors/test/miner_migration_test.go, go.mod, go.sum, support/vm6Util/utilV6.go
=> Draft: Migration test for miner actor

go.mod, go.sum, support/agent/blockstore_util.go, support/ipld/store.go
=> v4: Update to go-ipld-cbor v0.0.6
