- actors/abi/deal.go
- actors/abi/piece.go
- actors/builtin/account/account_actor.go
- actors/builtin/cron/cron_actor.go
- actors/builtin/init/init_actor.go
- actors/builtin/multisig/multisig_actor.go
- actors/builtin/reward/reward_actor.go
- actors/builtin/storage_market/storage_market_actor.go
- actors/builtin/storage_market/storage_market_actor_boilerplate.go
- actors/builtin/storage_miner/storage_miner_actor.go
- actors/builtin/storage_miner/storage_miner_actor_boilerplate.go
- actors/builtin/storage_miner/storage_miner_actor_state.go
- actors/builtin/storage_power/storage_power_actor.go
- actors/builtin/storage_power/storage_power_actor_boilerplate.go
- actors/runtime/params.go
- actors/runtime/runtime.go
- actors/runtime/runtime_util.go
- actors/util/actor_util.go
- go.mod
This is part of getting the exports to have a consistent type signature for method dispatch. These structures should be cbor-encoded for on-chain representation in a follow-up.
[We have already added params structs for the mutlisig actor, other actors are still to come]
> Replace all exported method return types with structures

- actors/runtime/runtime.go
This is sufficient for all current tracing in Lotus actors. We can extend it if necessary.
The Span interface may be implemented directly by the opencensus Span type.
> Add minimal tracing endpoint to Runtime interface

- actors/builtin/cron/cron_actor.go
- actors/builtin/init/init_actor.go
- actors/builtin/multisig/multisig_actor.go
- actors/builtin/reward/reward_actor.go
- actors/builtin/storage_market/storage_market_actor.go
- actors/builtin/storage_miner/storage_miner_actor.go
- actors/builtin/storage_power/storage_power_actor.go
- actors/runtime/exitcode/reserved.go
- actors/runtime/runtime.go
- actors/runtime/runtime_util.go
This is mostly a mechanical change, preserving the existing semantics, with the exception of the multisig actor. The final multisig approval will now succeed even if the message that is sent fails.
Closes #20
> Add exit code to Runtime.Send() and rationalize the interface down to one send method.

- Makefile
- initially if the generated cbor code didin't complie a developer would
need to manually remove it before running `make gen`, now that happens
automatically.
> build: Makefile correctly generates cbor

- actors/builtin/init/init_actor.go
- actors/builtin/reward/reward_actor.go
- actors/builtin/shared.go
- actors/builtin/storage_market/storage_market_actor.go
- actors/builtin/storage_miner/storage_miner_actor.go
- actors/builtin/storage_power/storage_power_actor.go
- actors/runtime/runtime.go
This breaks the dependency of runtime on builtin.
> Add network name to runtime. Move shared builtin code to builtin.

- actors/builtin/multisig/multisig_actor.go
- actors/builtin/multisig/multisig_test.go
- actors/runtime/exitcode/reserved.go
- actors/runtime/runtime.go
- actors/util/assert.go
- go.mod
- support/mock/builder.go
- support/mock/mockrt.go
The test exposed a bug in the constructor failing to initialize a bigint value.
This is based on #45, which must land first.
> First implementation of mock runtime and construction unit tests for the multisig actor

- actors/builtin/methods.go
- actors/builtin/storage_market/storage_market_actor.go
- actors/builtin/storage_miner/storage_miner_actor.go
- actors/builtin/storage_miner/storage_miner_actor_state.go
- actors/runtime/indices/indices.go
Simplify sector state with the following changes:
TODO:
cc @jzimmerman @sternhenri
> simplify sector state

- actors/abi/big/int.go
- actors/builtin/multisig/multisig_actor.go
- actors/builtin/multisig/multisig_actor_state.go
- actors/builtin/multisig/multisig_test.go
- actors/builtin/storage_power/storage_power_actor.go
- actors/builtin/storage_power/storage_power_actor_state.go
- actors/util/actor_util.go
- actors/util/adt/map.go
- support/mock/mockrt.go
Multisig and power actors correctly initialize empty maps at construction.
> Implement NewEmptyMap, Map.CollectKeys and fix ForEach.

- actors/builtin/reward/reward_actor.go
Interpreter transfers gasReward from BurntFundsActor to RewardActor before Reward is paid out,
- gasPenalty is first deducted from gasReward+BlockReward
- penalty is sent back to the BurtFundsActor
- the remaining reward is then dispensed/garnished for the miner
- if penalty exceeds total reward, all reward will be penalized and the remaining penalty is forgone
> update penalty deduction

- actors/abi/primitives.go
- actors/abi/sector.go
- actors/builtin/account/account_actor.go
- actors/builtin/cron/cron_actor.go
- actors/builtin/init/init_actor.go
- actors/builtin/methods.go
- actors/builtin/multisig/multisig_actor.go
- actors/builtin/multisig/multisig_test.go
- actors/builtin/reward/reward_actor.go
- actors/builtin/storage_market/storage_market_actor.go
- actors/builtin/storage_market/storage_market_actor_state.go
- actors/builtin/storage_miner/storage_miner_actor.go
- actors/builtin/storage_miner/storage_miner_actor_state.go
- actors/builtin/storage_power/storage_power_actor.go
- actors/builtin/storage_power/storage_power_actor_state.go
- actors/crypto/randomness.go
- actors/runtime/exitcode/common.go
- actors/runtime/indices/indices.go
- actors/runtime/runtime.go
- actors/serde/serialization.go
- actors/util/adt/store.go
**In this PR:**
- Handled a few rote TODOs, namely: 
- `abortstatemsg` -> `abort`
- `bytes` -> `[]byte`
- stale TODOs
- labeled TODOs with likely DRIs
@zixuanzh see if you can knock any others out or pick other DRIs if you think there is better?
Thereafter good to merge.
> label TODOs

- actors/builtin/reward/reward_actor.go
- actors/builtin/storage_market/storage_market_actor.go
- actors/builtin/storage_market/storage_market_actor_state.go
- actors/builtin/storage_power/storage_power_actor_state.go
- actors/runtime/indices/indices.go
per #60, in this PR,
- BigInt operations have been implemented in several places, removing IMPL_FINISH
- Implemented  BigInt in Reward vesting
- Reward vesting may still exist and linear should suffice unless research shows otherwise
- Tentatively, miners dont get consensus power for nominal power that they dont have pledge collateral for
> TODO fixes

- support/mock/mockrt.go
The mock runtime does not automatically track balance changes via message send. Currently this means test writers need to call `rt.SetBalance(/* expected balance after send */)` after a method performs a send operation to update actor balance. #90 has brought to our attention that this is not ergonomic for test writer. This PR updates the mock runtimes `Send()` operation to modify the `balance` value after a message is sent.
> test: mockrt updates balance on sends

- actors/abi/bitfield.go
- actors/builtin/storage_miner/policy.go
- actors/builtin/storage_power/policy.go
- actors/runtime/indices/indices.go
- actors/util/assert.go
In this PR,
- Commented out PARAM_FINISH but did not remove to keep track of parameters and functions that need to be set so that it can be run
- Implemented big int operation for slashing reward
- Proportion related calculation, specifically related to power, is left as zero, they will be fixed in a separate PR when the power table is removed as discussed
> remove param finish

- actors/builtin/cron/cron_test.go
- actors/builtin/multisig/multisig_test.go
- actors/builtin/storage_power/storage_power_test.go
- support/testing/address.go
- Add unit tests for the cron actor: constructor and epoch tick.
- Extract newIDAddr to testing utils package and refactor all tests to use it.
> test: add cron actor unit tests

- actors/abi/big/int.go
- actors/abi/big/int_test.go
Many data structs in Lotus/go-fil-markets have big int values that are treated as essentially optional -- they can be set or not. However, currently, the zero value for big.Int (i.e. nothing set, internal Int data member == nil) throws an error when marshalled to CBOR. This will cause several errors in existing lotus & go-fil-markets code that don't show until run (or tested). It also might require extensive code changes.
This PR changes the MarshalJSON & MarshalCBOR methods of big.Int to match big.Int from Lotus & tokenamount.Tokenamount from go-fil-markets, which both do not error when marshalling CBOR for an empty big.Int.
I am not sure this is the right solution -- rather it's a strawman to start a converation. Because the difference blocks, or at least makes difficult, moving much of …
> fix(abi/big): match CBOR Marshalling to impls

- actors/builtin/storage_miner/cbor_gen.go
- actors/builtin/storage_miner/policy.go
- actors/builtin/storage_miner/storage_miner_actor.go
- actors/builtin/storage_miner/storage_miner_actor_state.go
- removed unnecessary surprise challenge code. Only a constant number are challenged, and checked for.
- change electionPoSt eligibility to eligible unless surprise is missed (rather than unless is challenged)
- fix a couple mistakes
- remove no_surprise_challenge_period: fallback always occurs regardless of ePoSt
left TODO:
- power only after first post
- deal with ChallengedSectors stuff
> PoSt updates

- actors/builtin/reward/cbor_gen.go
- actors/builtin/reward/reward_actor.go
- actors/builtin/reward/reward_state.go
- actors/runtime/indices/indices.go
The reward actor now tracks the state of the available treasury balance, for sanity check and future use in epoch reward calculation.
> Implement a placeholder constant block reward function, removing dependence on pledge collateral.

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
- actors/builtin/power/cbor_gen.go
- actors/builtin/power/policy.go
- actors/builtin/power/power_actor.go
This also paves the way for a fault representation that doesn't need to unset individual fault bits.
@Kubuxu tagging you for review as a good intro to the places the update the miner actor with a sequence of batch fault declarations.
cc @zixuanzh
> Batchify a bunch of per-sector operations to reduce messages and state transactions.

- actors/abi/big/int.go
This allows MarshalBinary to be called on zero valued big.Ints without erroring in the same way MarshalCBOR can.
This might not be the most correct place to do this.  It might be better to do it directly on the Bytes method and remove the checks from MarshalBinary and MarhsalCBOR. This is the least invasive is it doesn't imply removing the error from the Bytes method avoiding the breaking change.
> MarshalBinary handles zero val

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
Export method params fields so they may be constructed outside of the specs-actors package. cc @acruikshank
> bug: export fields in miner method params

- actors/builtin/market/market_state.go
- actors/builtin/market/market_state_test.go
`market.State` was initializing `EscrowTable`, `LockedTable` fields as arrays, even though they are indexed by `address.Address`.  Also, the `States` field was left uninitialized.
Initialize EscrowTable, LockedTable as maps, States as array.
> Initialize Market State fields

- actors/util/adt/adt_test.go
- actors/util/adt/store.go
There is a lack of encoding in the specification. Please, consider adding tests for actor state serialisation.
Please, see https://github.com/filecoin-project/specs-actors/pull/150 as corresponding improvement.
> add test for address key encoding

- actors/builtin/market/market_actor.go
- actors/builtin/market/market_state.go
- actors/builtin/market/set_multimap.go
- actors/builtin/miner/miner_state.go
- actors/builtin/power/power_state.go
- actors/util/adt/store.go
Added uint64 key encoder, and restructured to reduce the number of accidental conversions between int64 and uint64 possible. 
Before this change, the maps keyed by DealID and SectorNumber were both wrong, after #124.
> Fix HAMT key encoding of unsigned integers

- actors/builtin/paych/cbor_gen.go
- actors/builtin/paych/paych_actor.go
- actors/builtin/paych/paych_state.go
- actors/builtin/paych/paych_test.go
Per discussion in [fil-specs channel](https://filecoinproject.slack.com/archives/CHMNDCK9P/p1581532533364500), lane and nonce are int64s. Since negative values aren't meaningful, rather than put checks for invalid values in the code, let's eliminate the issue entirely and make them unsigned. This is only for the payment channel actor.
> paych.Actor:  convert Lane and Nonce to uint64

- actors/abi/sector.go
The specs-actors `RegisteredProof` type, in its current form, [is missing some of the proofs](https://github.com/filecoin-project/rust-filecoin-proofs-api/blob/master/src/registry.rs#L9) supported by the current proofs library (and which are used by lotus and go-filecoin).
> extend RegisteredProof to include other, currently-in-use proofs

- actors/util/adt/adt_test.go
- actors/util/adt/balancetable.go
- actors/util/adt/balancetable_test.go
`BalanceTable.AddCreate()` was loading the table value into the incorrect value.
Write value into the correct place.
> Fix BalanceTable AddCreate typo

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
Updating PoSt to compute provingSet at appropriate time. 
The same `computeProvingSet` call should be used as part of computing electionPoSts, but without updating the `minerState.ProvingSet`after the call.
> implement computeProvingSet()

- actors/builtin/codes.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
- actors/builtin/power/power_actor.go
Addresses written into state must be ID address in order to match caller validation. But the miner checks that the worker account has an associated BLS key that will later be able to sign blocks, as a fail-fast mechanism.
Closes #57
> Fix miner actor's check of BLS key associated with worker account.

- actors/builtin/account/account_actor.go
- actors/builtin/account/account_test.go
- actors/builtin/market/market_actor.go
- actors/builtin/miner/cbor_gen.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/paych/paych_actor.go
- actors/builtin/power/power_actor.go
- actors/builtin/reward/reward_actor.go
- actors/runtime/runtime.go
- support/mock/mockrt.go
This makes the miner worker address much more ergonomic to set, avoiding the need for either yanking the account's ID address out of the state, or waiting for finality for it to be safe to use.
The miner and power escrow keys were very easy to mis-use beforehand. This makes it clear that the address under which all balances are held is the canonical ID address of the miner or client.
An alternative to this approach would be to send a message to the Init actor. This seems like a reasonable facility to special-case, with less actual execution cost as well as less gas to be paid, since we can expect this table to be cached.
FYI @icorderi
> Add address resolution call to runtime; resolve miner worker and power/market account-keeping addresses.

- actors/runtime/runtime.go
> Remove unused runtime method exposing the block winner address

- actors/abi/cbor_gen.go
- actors/abi/sector.go
- actors/builtin/miner/cbor_gen.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/policy.go
from https://github.com/filecoin-project/specs/issues/867
In this PR:
- Made `MaxSealTime` a variable dependent on proof type everywhere (including cron callbacks for precommitExpiry)
- Added `PreCommitChallengeDelay` as Lotus uses to determine time between `PreCommit` appears on chain and challenge is drawn for interactive PoRep.
- Collapsing of redundant parameters `MaxSealTime` and `PoRepMaxDelay`. (@jzimmerman to verify no missing of purpose)
> Seal TODOs

- actors/abi/sector.go
For more background, see [this thread](https://filecoinproject.slack.com/archives/CHMNDCK9P/p1582571498038300?thread_ts=1582571005.037100&cid=CHMNDCK9P).
A PoSt verifier needs to know, for each replica in a prover's proving set, the appropriate PoSt-specific `RegisteredProof` value. This value encodes proof version (e.g. "v1") and also sector size (e.g. 32GiB).
This changeset adds a deterministic mapping from PoSt to seal-specific `RegisteredProof` (and vice-versa). A PoSt verifier will acquire the seal-specific `RegisteredProof` value for each sector in the prover's sector set which they will map to PoSt-specific `RegisteredProof` for purpose of PoSt verification.
> add mappings between seal and PoSt-specific RegisteredProof values

- actors/abi/cbor_gen.go
- actors/abi/sector.go
- actors/builtin/miner/cbor_gen.go
- actors/builtin/miner/miner_actor.go
- actors/runtime/runtime.go
- support/mock/mock_syscaller.go
The existing PoSt verification types are lacking in a few ways:
1. The PoSt verifier needs some way to know the `RegisteredProof` that corresponds to a `PoStProof`
1. The PoSt verifier needs some value from which they can derive a 32-byte prover ID
1. Sector size is a function of `RegisteredProof`
This changeset:
1. Enables a storage miner's proving set to contain sectors sealed and proven using more than one `RegisteredProof`; it adds `RegisteredProof` to the `PoStProof` struct.
1. Adds `Prover ActorID` to the `PoStVerifyInfo` struct so that verifiers can map to a 32-byte prover id (for libfilecoin's `verify_post` call).
1. Drops the `sectorSize SectorSize` parameter from `VerifySeal` and `VerifyPoSt` calls
> plumb required values into PoSt verification-input

- actors/builtin/miner/miner_actor.go
Spec requires noop caller validation by runtime this adds it to control address get.
> Required caller validation in control address get

- actors/abi/sector.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/policy.go
See [this thread](https://filecoinproject.slack.com/archives/CHMNDCK9P/p1582657646068400?thread_ts=1582648075.057600&cid=CHMNDCK9P) for more information.
The libfilecoin `post_verify` function needs to know the prover's challenge count. Without that value, the verifier can't verify the provided proofs. 
This changeset adds a challenge count-computing method (which is a function of proving set) and plumbs its value to the `VerifyPoSt` method.
This changeset does not add an operation which can be used to generate ePoSt challenge count.
> add challenge count computing-method and plumb value to PoSt verification method

- actors/abi/sector.go
- actors/builtin/miner/policy.go
The [v23](https://github.com/filecoin-project/rust-fil-proofs/blob/master/filecoin-proofs/src/constants.rs#L11) version of libfilecoin moves to a new set of supported sector sizes. For more information about this change, read [this thread](https://filecoinproject.slack.com/archives/CEGB67XJ8/p1581971606377800?thread_ts=1581971606.377800).
This PR updates the `RegisteredProof` enum to use the latest and greatest sector sizes.
Note that I've repurposed some of the old `RegisteredProof` values.
> update RegisteredProof values to conform v23 supported sector sizes

- actors/builtin/miner/miner_actor.go
- actors/builtin/paych/cbor_gen.go
- actors/builtin/paych/paych_actor.go
- actors/builtin/paych/paych_test.go
As in #189, this PR has 3 commits, one for each of the following changes:
- Add a new method to the miner actor, `CheckSectorProven`, which succeeds if a given sector has been proven, fails otherwise
- Allow miner actor's `ProveCommitSector` to be called by anyone
- Add a `TimeLockMax` to vouchers in payment channels. Vouchers cannot be redeemed beyond the `TimeLockMax`.
> Changes to support a PoRep outsourcing market

- actors/builtin/cron/cbor_gen.go
- actors/builtin/market/cbor_gen.go
- actors/builtin/power/cbor_gen.go
- actors/builtin/power/power_actor.go
- actors/builtin/power/power_test.go
Not sure why this got changed, but theres no reason not to allow someone to create a miner on someone elses behalf. We use this in the faucet to help people set up their miners.
> readdr miner owner param to createminer call

- actors/crypto/signature.go
Add binary marshaling functions to signature types so that go-filecoin can continue using this type and serialize it without issue.
> Add binary (un)marshal to signature

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/policy.go
For more context, see [this thread](https://filecoinproject.slack.com/archives/CHMNDCK9P/p1582755841096200?thread_ts=1582735826.080900&cid=CHMNDCK9P).
Windowed PoSt challenge count is not a function of miner size, rather a network constant.
This PR replaces the windowed PoSt challenge count-computing method with a constant.
> replace ComputeWindowedPoStChallengeCount method with constant

- actors/crypto/signature.go
go-filecoin wants a bit more leniency in unmarshaling so that zero valued signatures can be encoded and decoded.
> Remove error when unmarshalling unknown signature

- actors/builtin/power/cbor_gen.go
- actors/builtin/power/policy.go
- actors/builtin/power/power_actor.go
- actors/runtime/runtime.go
- support/mock/mock_syscaller.go
Add third parameter to consensus fault reporting for the parent grinding witness.
Remove parameters that are derived from the block headers, return them from the syscall instead.
> Fix consensus fault reporting method params and syscall

- actors/builtin/reward/reward_actor.go
We're seeing an issue where we don't get rewards mapped for every block, trying to debug it I found this. I havent confirmed this was the issue though.
> handle errors in AwardBlockReward

- actors/builtin/power/power_actor.go
- actors/builtin/power/power_state.go
Cron-evens scheduled for epochs which turn out to be null blocks are never executed. To ensure all cron events are execute we need to keep track of the last epock tick and load all cron events from that point forwards to the current run-time epoch.
Resolves #241
> power: run all cron events since last epoch tick

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/policy.go
These sector fields need to be initialized to -1 otherwise it fails when we try to enumerate the sector set for post.
I also lowered the number of sectors we need down to 1, so simplify implementation work. This is going to change anyways, so no big deal here.
> fix sector creation, drop winpost candidate req

- actors/builtin/miner/miner_actor.go
The methods modifies are only called from `OnDeferredCronEvent` which already validates the caller (note: calling ValidateCaller more than once for a single transactions causes the go-filecoin rt to panic). Furthermore `commitWorkerKeyChange` wrongly expected its caller to be the Cron actor, this check has been removed and is handed in `OnDeferredCronEvent`.
> remove redundant caller asserion in miner actor

- actors/util/adt/store.go
I noticed you guys have an insufficiently long buffer for varints you are using for the hash keys. 
I don't know if this is intended but I did not want to assume a panic in this edge case without checking. I couldn't find any documentation referring to why this would be the case
> Fix varint buffer lengths to avoid edge case panics

- actors/builtin/miner/miner_actor.go
This method is missing a validation call which causes go-filecoin runtime to fail on change peer id messages.  
More importantly I believe that this is a case where we really want this call to be made by only an authorized worker.
> Validate that worker is caller to change peer id

- actors/builtin/paych/paych_actor.go
Edge case where the values are greater than the max i64 value, incorrect value will be used
> Remove conversion to bigint through a i64 value

- actors/builtin/power/power_state.go
Maybe this should be an issue but I don't see any possible reason why the claim pledge would be updated twice in this function. I assume this is a bug from updates that were made?
> Remove duplicate pledge update in spa state

- actors/builtin/power/power_state.go
amount is being added twice, which does not affect anything regarding consensus because the root is only updated after the first, but there are unnecessary values written to store (and of course unnecessary logic). 
With your implementation the call the second time is written to the underlying data storage, meaning you have a data leak of sorts having to store this updated state which may never be used.
> Remove duplicate balance add in power actor state

- actors/runtime/exitcode/reserved.go
- support/mock/mockrt.go
Identify two exit codes which indicate message send failure, meaning that the sender's callseqnum is not incremented. The VM needs to handle such messages, and produce a receipt, lest we require full tipset re-evaluation for clients to be able to identify which receipt is for which message in a tipset.
The new `SysErrSenderInvalid` and `SysErrSenderStateInvalid` together capture all message send failures, and should be used *only* to indicate that.
I'm open to suggestions of better terminology than "send failure" to describe these cases. I chose it over "application failure" because it's all about where the message come from, rather than what it applies to.
Closes #251
> Define two exclusive failed send codes

- actors/builtin/miner/miner_actor.go
- actors/builtin/power/power_actor.go
- actors/runtime/runtime.go
- support/mock/mockrt.go
When an actor is deleted we need to do something with its funds to preserve the money supply invariant. One option is to refuse to delete the actor (i.e. abort), but since our one use case for this comes from cron and slashing, we really need it to succeed.
Better is to designate where the funds should go. Ethereum's `selfdestruct` opcode does the same thing.
> Add beneficiary parameter to DeleteActor

- actors/runtime/exitcode/reserved.go
This code is needed for internal sends, where the immediate caller tries to transfer more than they have.
> Add exit code SysErrInsufficientFunds

- actors/builtin/reward/reward_state.go
- Removes unnecessary big.Int allocations
- Only initialize elapsed on linear vesting (not used for non-vesting)
- Panic on invalid vesting function instead of just returning 0
- Obviously doesn't matter now because `None` vesting function is hard coded, but just want to make sure the call will not succeed in future if an invalid function
The heap allocations and verbose checks were hard to look at. Let me know what you would want the doc comment or panic message to say, or if you want this to behave differently than this
> Update amount vested utility function

- actors/builtin/init/init_actor.go
- actors/builtin/init/init_actor_state.go
- actors/builtin/init/init_test.go
- actors/builtin/market/market_actor.go
- actors/builtin/market/market_state.go
- actors/builtin/market/market_test.go
- actors/builtin/market/set_multimap.go
- actors/builtin/market/types.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
- actors/builtin/multisig/multisig_actor.go
- actors/builtin/multisig/multisig_state.go
- actors/builtin/multisig/multisig_test.go
- actors/builtin/power/power_actor.go
- actors/builtin/power/power_state.go
- actors/builtin/power/power_test.go
- actors/builtin/reward/reward_actor.go
- actors/builtin/reward/reward_test.go
- actors/util/adt/array.go
- actors/util/adt/array_test.go
- actors/util/adt/balancetable.go
- actors/util/adt/balancetable_test.go
- actors/util/adt/map.go
- actors/util/adt/multimap.go
- actors/util/adt/set.go
- support/testing/address.go
- support/testing/adt.go
This is the first phase, where we just change the apis a bit to only flush when root is called, and actually load the objects up front when we instantiate the structures.
I put in a few helpers in an attempt to write less code, but expect things to change more in the next step where I try to combine multiple operations on the same structure in the same transaction.
> avoid flushing merkle structures on every single operation

- actors/builtin/multisig/cbor_gen.go
- actors/builtin/multisig/multisig_actor.go
- actors/builtin/multisig/multisig_test.go
- gen/gen.go
As written, multisig has an issue. When approving a message, approvers have no cryptographic method for confirming that they are truly signing a message related to the original proposal. Add a proposal hash field to the "Approve" message params. The field contains a BLAKE2B-256 hash of the CBOR bytes of the multisig wallet address, the proposer's address, and the fields in the multisig "Propose" params. When an approval occurs, the actor code compares the hash it receives with the data from the original transaction it received. If there's a match, the approval proceeds. If not, the code errors out.
> Add a proposal hash to multisig "Approve" message params

- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_state_test.go
Plan to continuing adding tests and rebasing on `wpost` branch as progress continues there.
More tests to add include:
> initial impl of miner state tests

- actors/builtin/methods.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/reward/reward_actor.go
- Rename AwardReward to AddLockedFund that can be called by any one to add locked fund as collateral.
- Caller can specify an amountToLock that needs to be less than or equal to the available balance.
- RewardActor calls this method for awarding block reward and adding locked fund.
> update AwardReward to AddLockedFund

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
No semantic change intended here, just cleanup. But I fixed some errors where the state object, rather than a pointer to it, was passed to a function.
> Detach helper functions from miner actor that don't need to be methods

- actors/builtin/multisig/multisig_actor.go
- actors/builtin/multisig/multisig_test.go
#248 added GetProposalHash as an actor method (but didn't export it) and made a direct call to blake2b, instead of the syscall, as a workaround to make the GetProposalHash method callable as a function from tests.
This fixes it to make it actually a function (not a method). It should not have been a method unless the intent was to export it.
(An alternative workaround would have been to use `rt.Call(...)` in tests to init the mock runtime appropriately)
FYI @droark
> Remove direct call to blake2b from multisig actor by extracting transaction digest to pure function.

- actors/builtin/power/cbor_gen.go
- actors/builtin/power/power_actor.go
- actors/builtin/power/power_state.go
- actors/builtin/power/power_test.go
Detection of missed PoSts is now done in the miner actor, and is per-partition rather than miner wide. 
This could have been removed with #286.
> Remove PoStDetectedFaultMiners from power actor state

- actors/builtin/market/market_state.go
Looking at the entries to this function, I don't think there's any reason why we should *fail* if it's called before a deal proposal has started, I think we can just return without doing anything.
I might be missing something, though.
This fixes https://github.com/filecoin-project/lotus/issues/1455
> Safely return from updatePendingDealState if deal.StartEpoch hasn't begun

- actors/builtin/miner/cbor_gen.go
- actors/builtin/miner/deadlines.go
- actors/builtin/miner/deadlines_test.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- support/mock/mockrt.go
- Tests for sector pre-commitment and cron scheduling
- Fixes incorrect cron scheduling when the first proving period was partial
- Removed RegisteredProof from sector pre-commit cron payload (unnecessary) 
- Improvements to the mock runtime for this and future tests (incl stack traces on errors)
- Test helpers for future tests (partially written elsewhere)
> Tests and fixes for miner actor pre-commits and cron

- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_state_test.go
fix: bug in miner LockedFunds and add test
- LockedFunds was not updated when AddLockedFunds was called.
fix: bug in UnlockUnvestedFunds and add test
- unlockAmount was incorrectly caluculated such that entries were
negative and never removed from vestingStore.
- vestingFunds was not updated when its entires changes.
> fix bugs in miner vesting

- actors/builtin/power/power_actor.go
- actors/builtin/power/power_state.go
- actors/builtin/power/power_test.go
This behaviour is worth paying attention to. We don't expect miner cron callbacks to abort, ever. Previously the signal was very loud when they did. Now the network will proceed, but it'll be easy to miss this unexpected and probably-major error.
(This PR doesn't fix the miner cron, which fails to handle being invoked after its scheduled round, if it was scheduled on a null).
> Power actor proceeds after failure of cron callback.

- actors/builtin/miner/cbor_gen.go
- actors/builtin/miner/deadlines.go
- actors/builtin/miner/deadlines_test.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_internal_test.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_test.go
Handling the possibility of the cron callback coming after the scheduled epoch means we can no longer infer the proving period from the current epoch. Instead, it's stored in state and updated for each new period. This does make some things more directly observable from the state, at least.
Apologies @magik6k that this may require tweaks to the wpost worker integration.
> Store proving period start in state explicitly and fix cron to handle invocation off expected schedule

- actors/abi/sector.go
A deterministic mapping from Window -> Winning PoSt exists in specs-actors today, but requires that we go Window -> Seal -> Winning. That's a little silly. 
This changeset expands the existing mapping-methods to allow Window -> Winning and Winning -> Window transformations w/out going through Seal.
> map from winning -> window, and window -> winning

- actors/builtin/cron/cron_state.go
Specifying these entries here will help us avoid accidental divergence in implementations.
> Specify cron genesis entries

- actors/builtin/power/power_actor.go
- actors/builtin/power/power_test.go
The power actor no longer holds collateral, or any balance. Value sent here would otherwise be lost.
> Power actor CreateMiner passes on value received to new actor

- actors/builtin/market/cbor_gen.go
- actors/builtin/market/market_actor.go
- actors/builtin/miner/miner_actor.go
> Remove unused SectorSize from VerifyDealsOnSectorProveCommitParams

- actors/builtin/miner/policy.go
I think this change is required to match a number [hardcoded in in rust-fil-proofs](https://github.com/filecoin-project/rust-fil-proofs/blob/13cdfbb204e7a7c161bcb4cf787b0d2154c57b12/filecoin-proofs/src/constants.rs#L95). Without this change, I'm pretty sure proofs will fail to validate since the wrong sector information will be passed.
The linked code is alarming in a few ways:
- it suggests that this number is specific to sector size, which is big news to me and invalidates the implemented Window PoSt code for sectors other than 32GiB
- is has a value of `2` for 512GiB sectors, which doesn't seem motivated by any technical reason but is pretty unworkable for practical networks.
cc @dignifiedquire @porcuquine
> Change WPoStPartitionSectors to 2349

- actors/abi/sector.go
- actors/builtin/miner/cbor_gen.go
- actors/builtin/miner/deadlines.go
- actors/builtin/miner/deadlines_test.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_state_test.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/policy.go
- actors/builtin/power/cbor_gen.go
- actors/builtin/power/power_actor.go
- actors/builtin/power/power_test.go
This is part of the way to #335. The registered proof types in all the sector states and messages are now redundant.
FYI @magik6k, @acruikshank
> Fix seal proof type in miner actor and parameterize WPoSt partition size by it

- actors/abi/sector.go
First fixed in #332 but then broken again by my typo in #336.
> Fix the 32GiB Window PoSt partition size again

- actors/builtin/miner/deadlines.go
- actors/builtin/miner/deadlines_test.go
- actors/builtin/miner/miner_actor.go
This provides a `PeriodElapsed()` predicate and fixes the other ones to indicate that no challenge window is open after a proving period has elapsed and before the proving period start has been updated to the next period.
Also changes assertions from using a too-high deadline index into errors.
> DeadlineInfo handles expired proving period

- actors/builtin/cron/cron_state.go
- actors/builtin/market/cbor_gen.go
- actors/builtin/market/market_actor.go
- actors/builtin/market/market_state.go
- actors/builtin/market/market_test.go
- actors/builtin/market/policy.go
- actors/builtin/market/set_multimap.go
- actors/builtin/market/types.go
- actors/builtin/methods.go
- gen/gen.go
- go.mod
- go.sum
This should accomplish the same thing, except now payments for storage deals only happen once every hundred blocks or so (not bucketed though, otherwise that would create hot spots)
> improve deal accounting performance

- actors/builtin/miner/miner_actor.go
I discovered this while looking for the "failed to load fault sectors" error you observed. I don't think this fixes that problem, though.
> Fix failure to detect faults of exactly-full top partition

- actors/puppet/puppet.go
Implement a method on the puppet actor that sends parameters that always fail to marshal to CBOR.
> puppet type and method for failed marshal to cbor

- actors/abi/epoch.go
- actors/builtin/market/policy.go
- actors/builtin/miner/policy.go
- actors/builtin/network.go
- actors/builtin/reward/reward_actor.go
- actors/builtin/reward/reward_state.go
Updating parameters for unincentivized testnet, we expect further updates before testnet incentives and mainnet launch and even after mainnet.
> Temporary param update

- actors/abi/sector.go
- actors/builtin/miner/policy.go
When [this branch](https://github.com/filecoin-project/filecoin-ffi/pull/83) merges, libfilcrypto will support 64GiB sectors.
This changeset adds support for 64GiB sectors.
> add support for 64GiB sectors

- actors/builtin/reward/reward_actor.go
- actors/builtin/reward/reward_state.go
- actors/builtin/reward/reward_state_test.go
* use correct epoch duration (from `actors/builtin/miner/policy.go`)
* accept fixed-point input (which @zixuanzh can now use to pass fractional network times) 
* remove the dependence of tests on network parameters, by accepting {`LambdaNum`,`LambdaDen`} as parameters
* introduce a wrapper function for non-test usage that supplies the hard-coded Lambda constants (and also conveniently performs `Mul` and `Rsh` in the right order)
> Minting function maintainability

- actors/builtin/miner/miner_state.go
This was found in production.
I haven't gone to effort to cement this with regression tests because this whole SectoStorageWeightDesc and back-and-forth with the power actor is technical debt holdover from when the power actor owned these calculations, and I intend to remove most of it.
Closes #359, https://github.com/filecoin-project/go-filecoin/issues/4094
> Fix nil verified deal weight

- actors/util/adt/array.go
This error showing up in logs is murdering my terminal. Its including an absolutely massive bitfield.
> dont include value in the error message for set errors

- actors/builtin/power/policy.go
We can patch this at runtime in each impl, but it'll be way less confusing for other operators if the code has the right value.
> Change min miner power from 10TiB to 1TiB for testnet-2

- actors/abi/primitives.go
- actors/builtin/reward/cbor_gen.go
- actors/builtin/reward/reward_actor.go
- actors/builtin/reward/reward_state.go
Update NetworkTime to be a fraction with an implicit denominator of (2^MintingInputFixedPoint) and fix integer division error when baseline reward is only minted when a unit of baseline power is met.
> Fractional network time

- actors/builtin/miner/cbor_gen.go
- actors/builtin/miner/policy.go
This is intended as a temporary change, because v26 proofs window PoSt takes
more than half an hour.
> Change window post deadline duration to 1hr.

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
Fixes the erroneous clearing of declared recoveries during the proving period cron (or other detect-faults hooks). See the linked issue for background.
I'm painfully aware that this behaviour doesn't have unit tests yet.
Fixes #387
> Don't clear recovery declarations for future deadlines on PP boundary cron

- actors/builtin/cbor_gen.go
- actors/builtin/methods.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- actors/builtin/power/cbor_gen.go
- actors/builtin/power/power_actor.go
- actors/builtin/power/power_state.go
- actors/builtin/shared.go
- actors/runtime/runtime.go
- actors/util/adt/multimap.go
- gen/gen.go
- go.mod
- go.sum
- support/mock/mockrt.go
being able to verify all the porep proofs in the same syscall will let us do some optimization that will let us get over the hump perf wise.
Currently, we spend >80% of our sync time running porep verifications. At the very least, we can run them in parallel with this change. Maybe we can even do faster vectorized things, or gpu acceleration. but any sort of speedup will require this change.
> rewire porep verification to support bulk verifies

- actors/builtin/init/init_actor.go
User messages shouldn't be creating verifiedRegistry, system or reward actors or unknown code cids.
This PR also flips the permission strategy to fail closed.  This gives us an advantage catching bugs introduced by rot.
Close #219
> Restrict exec permissions

- actors/builtin/miner/cbor_gen.go
- actors/builtin/miner/policy.go
We believe proofs are now fast enough again that a ~half-hour~ 40 minute deadline duration is reasonable.
See #373 where this was changed to an hour.
> Change WPoSt deadline duration to 40 minutes

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
closes #429
The sector expiration is recorded in the sector itself and as an entry in a bitfield at the expiration epoch. `ExtendSectorExpiration` updates the former but not the latter, meaning the sector will not actually be expired at the appropriate time.
1. Remove the sector expiry at the original expiration.
2. Add a new sector expiry at the new expiration.
3. Add tests for `ExtendSectorExpiration`.
> Move sector expiration in `ExtendSectorExpiration`.

- actors/builtin/miner/deadlines.go
- actors/builtin/miner/deadlines_test.go
Fixes the assignment of new sectors to deadlines to open new partitions in one of the least-full deadlines, rather than a simple round robin always starting from the first (which led the first deadline to get ~all the sectors in practice).
See discussion in the comments about efficiency trade-offs made.
Closes #409, closes #402.
> Load balance new sectors to less-full partitions

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- support/mock/mockrt.go
closes #406
In the first proving period, the miner actor may attempt to retrieve randomness from the future when it handles the proving period cron task. In this case it should retrieve the randomness from the current epoch minus a lookback.
1. Set the randomness epoch to be the min of of the proving period end and the current epoch - `ElectionLookback`. It is unclear whether this deserves a new constant or not. The thinking is that whatever would cause us to change `ElectionLookback` would drive us to change this value as well, so we might as well reuse it.
2. Add a test that runs `handleProvingPeriod` in scenarios where the miner would have required randomness from the future and another where it would get it from the proving period end.
3. Add the ability for the actor harness to …
> miner actor does not get randomness from future

- actors/builtin/reward/cbor_gen.go
- actors/builtin/reward/reward_actor.go
- go.sum
closes #289
Ticket count is no longer used in reward computations, but it was still in the params struct. This PR removes it. The reward actor test was already omitting ticket count.
1. Remove ticket count.
2. Regenerate reward actor cbor_gen to reflect the deletion.
> Remove unused ticketcount parameter from reward actor

- actors/abi/cbor_gen.go
- actors/abi/sector.go
- actors/builtin/market/cbor_gen.go
- actors/builtin/market/market_actor.go
- actors/builtin/miner/cbor_gen.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_state_test.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/policy.go
- actors/builtin/power/cbor_gen.go
- actors/builtin/power/power_actor.go
- actors/builtin/power/power_test.go
- actors/runtime/runtime.go
- support/mock/mockrt.go
As of https://github.com/filecoin-project/rust-filecoin-proofs-api/pull/24, the actual enumerated values of registered seal proofs are significant to the protocol. In order to emphasize the non-arbitrary nature of these types/values, and to simplify keeping them in lockstep through the repos, I would like to mirror the types as closely as possible. I consulted @laser and mentioned my intention to @anorth before undertaking this.
To support this work, we will need a third PR — this one in filecoin-ffi. Hopefully once `specs-actors` and `rust-filecoin-proofs-api` are in sync, the job of adapting between them will be simpler. So that code will need some refactoring, hopefully to something more straightforward than currently exists.
I will leave this PR in draft until the work in …
> Refactor RegisteredProof to agree with proofs API.

- actors/abi/bitfield.go
- actors/builtin/market/market_actor.go
- actors/builtin/market/market_state.go
- actors/builtin/market/market_test.go
- actors/builtin/methods.go
- actors/builtin/miner/deadlines_test.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/policy.go
- actors/builtin/paych/paych_test.go
- actors/builtin/power/policy.go
- actors/builtin/power/power_actor.go
- actors/builtin/reward/reward_actor.go
- support/mock/mockrt.go
Adding github issue links for all TODOs in the code.  I defaulted to filing an issue for every TODO even though some appear to be easy and maybe an issue is overkill.  If some TODOs are totally done let me know and I'll close down and remove from PR.
Please search for appearances of issue 411 in this patch and verify that this issue is correctly scoped to cover the 4 instances where it is linked.  It seemed ok but I don't understand the scaling problem well enough to know if we should file distinct issues for separate TODOs.
Closes #412
> Document issues for existing TODOs

- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_state_test.go
Re-use of a bitfield pointer in `ForEachFaultEpoch` led to accidental accumulation of faults from different epochs in `Miner.popExpiredFaults`. The same issue applies to iteration of sector expiries. As a contributing factor, `RemoveFaults` would leave empty bitfields in the `FaultEpochs` collection rather than deleting the associated key, and similar for sector expirations.
Fixes #448
FYI @coder-lb, @marco-storswift
> Fix bitfield re-use leading to incorrect fault reporting

- actors/builtin/miner/miner_actor.go
This reverts commit fb8781b093e434b1b7c26570f6be2af743e42199.
This commit introduced a number of problems, now described in the linked PR. Fixes #430.
We'll re-implement committed-capacity upgrades with a different approach (#485).
FYI @zixuanzh
> Revert "add cc upgrade to precommit (#398)"

- actors/abi/cbor_gen.go
- actors/builtin/market/cbor_gen.go
- actors/builtin/miner/cbor_gen.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/policy.go
- actors/builtin/power/cbor_gen.go
- actors/builtin/power/policy.go
- actors/builtin/power/power_actor.go
- actors/builtin/shared.go
The calculation of sector quality and power was once in the power actor, but has no need to be. Moving the calculations to the miner actor simplifies the interactions.
- Removed `SectorStorageWeightDesc` struct
- Moved quality and power calculation functions to miner, in terms of `SectorOnChainInfo`
- Use power quantities rather than weight desc in parameters to power-accounting methods
Closes #419
> Move sector quality and power calculations into miner actor

- actors/builtin/methods.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- actors/builtin/power/cbor_gen.go
- actors/builtin/power/power_actor.go
- gen/gen.go
Deletes redundant power actor exported methods that are left over from when much more logic lived in the power actor.
FYI @magik6k. Closes #487.
> Unify sector power accounting methods

- actors/builtin/methods.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/monies.go
- actors/builtin/power/cbor_gen.go
- actors/builtin/power/policy.go
- actors/builtin/power/power_actor.go
- actors/runtime/runtime.go
- gen/gen.go
- go.mod
- go.sum
- support/mock/builder.go
- support/mock/mockrt.go
The miner actor can compute pledge amounts, which simplifies some interactions with the power actor. This PR avoids calling the reward actor for every sector.
Note that there's more simplification and batching now possible than I tried to realise in this PR, and things will also change when the pledge calculation moves to PreCommitSector, as the pre-commit deposit.
Fixes #489. FYI @zixuanzh
> Move pledge calculation from power to miner actor

- actors/runtime/runtime.go
- support/mock/mockrt.go
It will be used in the current effort of setting sane values for gas.
Gas is split into compute gas and storage gas to allow better analisys
of computation time in relation to gas.
Both gas types are latter combined into one and this is charged for the
execution.
Virtual gas is added for observing how changes to gas numbers affect
the balance without affecting the stateroot of the chain.
> Add ChargeGas method to Runtime

- .circleci/config.yml
- Makefile
- actors/builtin/market/market_state.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_state_test.go
- actors/builtin/miner/miner_test.go
- actors/builtin/multisig/multisig_actor.go
- actors/builtin/multisig/multisig_test.go
- actors/builtin/power/power_actor.go
- actors/builtin/power/power_state.go
- actors/builtin/reward/reward_state.go
- go.sum
Enabling strict linting in CI
To start with I'm temporarily adding in an intentional err drop to reproduce lint failure.
Closes #456
> Stricter Linting

- .codecov.yml
Prevent a scary red cross when project coverage has in fact improved.
> Disable codecov 'patch' PR status, set more attainable range target.

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/policy.go
Finality is the minimum safe value to prevent leader-election grinding attacks.
> Set worker key change delay to finality

- actors/builtin/market/market_actor.go
- actors/builtin/market/policy.go
- actors/builtin/miner/policy.go
Miner operators need to compute the initial pledge for a sector before attempting to (prove-) commit it. The pledge calculation logic was previously buried inside power actor methods and so Lotus goes through some [gymnastics involving simulating side-effecting actor messages](https://github.com/filecoin-project/lotus/blob/741825a04ee11b5ef68f32a7aee3608fca99911e/node/impl/full/state.go#L685) to the market and power actor in order to get at the expected pledge amount.
#489 moved the pledge amount calculation from the power actor to the miner, so that method won't work any more. This PR rearranges the code to export some free functions with which a miner operator can make the calculations directly (after plucking some values like the LastEpochBlockReward and TotalPower from the state). …
> Restructure weight and power calculations to be callable from outside

- .circleci/config.yml
- Makefile
- actors/builtin/multisig/multisig_actor.go
I observed lint failures locally with `make` that were not happening on CircleCI.
The command invoked in [this build](https://circleci.com/gh/filecoin-project/specs-actors/5938) was
```
$HOME/.local/bin/golangci-lint run -v \
--concurrency 2 --new-from-rev origin/master
```
Note the lack of `--skip-dirs-use-default=false` and also a now-unwanted `--new-from-rev` (that was previously in place when linting first installed but many error remained)
Maybe the `args` from `lint-changes` was overriding the `--skip-dirs-use-default` somehow?
Note that to merge this I will override the branch protection rules, and then immediately change the rules to require `lint-all` instead of `lint-changes`.
> Fix up CircleCI lint configuration

- actors/builtin/miner/deadlines.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_internal_test.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/monies.go
- actors/builtin/miner/policy.go
partially addresses #437
closes #468
We have not been using the right calculation for fault penalties. This PR:
1. Moves the calculation logic into the monies.go file.
2. Extracts `ExpectedDayRewardForSector` as the basis for all penalty calculations.
3. Implents `pledgePenaltyForSectorDeclaredFault`, `pledgePenaltyForSectorUndeclaredFault`, and `InitialPledgeForPower` according to the latest understanding from slash the world.
4. Adds calls to get `epochReward` from reward actor and `totalPwr` from power actor to miner calls that now need them to compute penalties.
5. Modify penalty calls in miner actor to use the new logic.
6. Modify tests to expect new extra calls to reward and power actor.
Issue #437 talks of both fault fees and sector termination fees. This work only covers the …
> Correct declared and undeclared fault computations

- actors/builtin/miner/cbor_gen.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_state_test.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/policy.go
- actors/builtin/multisig/cbor_gen.go
Previously, the `SectorOnChainInfo` (which lives in chain state for the life of the sector) had the `SectorPreCommitInfo` embedded in it, I think primarily for expediency in initial implementation. Bytes of `SectorOnChainInfo` are expensive, because we expect 10s-100s of million of them for exabyte-scale network. The pre-commit info contains the `SealRandEpoch`, which is not relevant after the sector is proven, wasting a few (hundred mega-)bytes. 
I am about to add another pre-commit-only field, so decided to clean this up first.
This changes inlines the relevant sector pre-commit information into SectorOnChainInfo, dropping the `SealRandEpoch` and saving another byte on the CBOR nested struct delimiter.
(Aside: it should be possible to remove the SectorNumber from this struct too, but …
> Denormalize sector precommit info into sector on-chain info

- actors/builtin/multisig/multisig_actor.go
- actors/builtin/multisig/multisig_state.go
- actors/builtin/multisig/multisig_test.go
We currently allow the approved signers of a multisig to not be ID addresses. However, when we try to validate that a caller is an approved signer, we only have the ID address of the caller. This causes an issue when checking if a caller is an approved signer.
We probably *don't* want to enforce that approved signers must be ID addresses, since these signers might not be registered at the time of multisig creation.
This PR changes the `isSigner` method to (attempt to) resolve any non-ID addresses in the approved signers, and to replace a non-ID address if this resolution is successful.
> Resolve key addresses to ID addresses in multisig validation

- actors/builtin/market/cbor_gen.go
- actors/builtin/market/market_actor.go
- actors/builtin/methods.go
- actors/builtin/miner/cbor_gen.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_state_test.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/policy.go
- gen/gen.go
- support/mock/mockrt.go
closes #424
We need to collect a deposit from miners precommitting sectors to be return when the sectors are committed. It has been decided that this deposit should be equivalent to the initial pledge that is locked when the sector is proven.
Tying precommit deposit to initial pledge has a few consequences. Initial pledge is a function of time, so we've decided to move the activation time of the sector to precommit time. This means we can compute the precommit deposit as `IP(currEpoch)` and then simply transfer this amount to lock funds to cover the initial pledge. This will have a small (but predictable) effect on the values of initial pledge and quality adjusted power, but shouldn't affect the behavior of the system beyond that. Power will still be granted and deals will still be …
> compute initial pledge for precommit deposit

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/policy.go
- support/mock/mockrt.go
closes #279
When a miner is deleted due to a consensus fault, all of it's deals need to be properly terminated.
1. Extract the miner termination logic out of `ReportConsensusFault` into a new `terminateMiner` method.
2. Call `requestTerminateAllDeals` from within that method.
3. Add a method to call `ReportConsensusFault` within the miner test actor harness.
4. Add logic to expect a `VerifyConsensusFault` and `DeleteActor` to the mock runtime.
5. Add the ability to specify deal IDs when creating sectors for miner tests so that we can observe the deal termination logic.
6. Add happy path test for `ReportConsensusFault` that confirms that it sends a `OnMinerSectorsTerminate` message to the storage market actor whose params contain every deal id referenced by all the miner's sectors.
1. …
> Terminate all miner deals when a consensus fault is detected

- actors/builtin/reward/cbor_gen.go
- actors/builtin/reward/reward_actor.go
It is necessary as we transition toward Poisson Sortition for the leader
election.
Q: How well does the reward actor handle over issuing rewards? We've currently set max `WinCount` of `15` in lotus but there can be also multiple blocks in a tipset.
> Add WinCount to reward actor

- actors/builtin/miner/cbor_gen.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_state_test.go
- actors/builtin/miner/miner_test.go
- support/mock/mockrt.go
closes #415
We need to enforce that a miner's locked funds exceeds the sum of their initial pledges to ensure the miner has enough funds to over potential fees. To do this we need to track the sum of initial pledges (and maintain that sum). We will check lock funds against initial pledges before a miner proves a sector and before the miner withdraws funds.
The bulk of this PR breaks out into its 5 initial commits:
1. Add `InitialPledges` to `miner.State` and add to it every time a sector is proven.
2. Add `InitialPledge' to 'SectorOnChainInfo' and set it to the sector's initial pledge when proven.
3. Use the sector's `InitialPledge` to subtract from `miner.State.InitialPledges` when sectors are terminated.
4. Add a check in `ProveCommitSector` to ensure locked funds are sufficient …
> Enforce locked funds do not fall below initial pledges

- actors/abi/sector.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/policy.go
closes  #454
Extending a sector's expiration more than a year or extending a sector past the maximum lifetime for its seal proof type decreases security (in ways unknown to the implementer).
1. Introduce `sealProof.SectorMaximumLifetime` method to limit the total lifetime of a sector after multiple extensions (currently always returns 5 years).
2. Introduce `MaxSectorExpirationExtension` as the maximum single shot expiration.
3. Augment `validateExpiration()` to check that `MaxSectorExpirationExtension` and `sealProof.SectorMaximumLifetime` are not exceeded.
4. Test.
> validateExpiration() checks current extension and total sector lifetime are not too long

- actors/builtin/miner/miner_internal_test.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_state_test.go
- actors/builtin/miner/miner_test.go
Use proving period start as entropy for setting offset in quantization boundaries for vesting.
Closes #301
> Quantize vesting with offset 

- actors/builtin/multisig/multisig_actor.go
- actors/builtin/multisig/multisig_test.go
Closes #473 
@anorth On second thoughts, replacing the `AbortMsg` pattern in the plumbing methods looks like a larger refactor that we can defer to later. Do we have an issue for it or should I create one ?
> Multisig: Use correct error codes

- actors/builtin/multisig/multisig_test.go
Followup to https://github.com/filecoin-project/specs-actors/pull/524/files#r445244817.
@anorth There's potentially a lot of other calls for other methods where we can do this but this is a start.
> Multisig Tests: Remove verifies that are not required

- actors/builtin/miner/cbor_gen.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_test.go
- support/mock/mockrt.go
Adds a `ReplaceSector` parameter to sector pre-commit, allowing a sector with deals to replace a committed-capacity sector. There are some restrictions on the replacing/replacement pair to ensure total pledge is not reduced. Termination of the replaced sector is deferred until the end of the proving period (not yet implemented).
This draft is FYI @zixuanzh @magik6k. I won't seek real review until writing a bunch of tests.
Closes #485.
> Implement replacement of committed-capacity sector by a new one

- actors/builtin/market/cbor_gen.go
- actors/builtin/market/deal.go
- actors/builtin/market/market_actor.go
- actors/builtin/market/market_state.go
- actors/builtin/market/market_test.go
- actors/util/adt/store.go
I think that this works, but it has one caveat that i think is okay.
If a miner publishes a deal, seals the sector, publishes the prove commit, and terminates the sector *all before the deal start date* the miner could then resubmit the deal. I think that this is fine because the miner isnt paid for the deal until the deal start date anyways, so theres no way to get any extra money out of this.
Closes #364
> track pending deal proposals to ensure deals can't be duplicately published

- actors/builtin/methods.go
- actors/builtin/power/cbor_gen.go
- actors/builtin/power/power_actor.go
- gen/gen.go
This method isn't used anywhere, and doesn't really do what the user would expect.
Later, we should add a method on the miner itself that:
1. Sets it's power to 0.
2. Deletes the miner actor.
> Remove DeleteMiner method

- actors/abi/sector.go
- actors/builtin/reward/reward_actor.go
- actors/builtin/reward/reward_state.go
This unit is only used in reward actor state and calculations (though a similar concept exists for deal weights).
FYI @zixuanzh
> Move spacetime type from abi to reward actor

- actors/abi/bitfield.go
- actors/abi/bitfield_test.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_test.go
- go.mod
- go.sum
Replaces #568
Fixes #460
* Removes BitFieldUnion (we can now use bitfield.MultiMerge).
* Optimizes contains functions to avoid creating new bitfields, or iterating over the bitfields any more than necessary.
* Adds tests for the contains functions.
Note: This removes an abi method: BitFieldUnion. This will require updating lotus.
> Update and optimize bitfield operations

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- support/mock/mockrt.go
closes #410
The `Skipped` field in `SubmitWindowedPoSt` is currently ignored. This field is important because it allows miners to signal which sectors have faulted late without losing the entire PoSt. This PR adds the functionality to penalize skipped faults and add them to declared faults so that the proof verification will not fail.
1. Introduce `processSkippedFaults` call into `SubmitWindowedPoSt` to handle the `Skipped` parameter.
2. Add logic to handle intersection with recoveries.
3. Add logic to add skipped faults to `Faults` and the current `FaultEpoch`.
4. Add logic to compute an undeclared fault penalty for the skipped faults, unlock that amount and burn it.
5. Add logic to compute power delta for unlocked faults and notify power actor of the change.
6. Test.
> Skipped Faults

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
Closes #431 
Prove commits are validated independently up front.  If any fails validation then it is quietly dropped and we move onto the next prove commit.  After validating we terminate early if all prove commits have been dropped before moving onto batch update.
Keeping WIP because this is based off of #577 which is still in review
> Robustify Bulk PoRep

- actors/builtin/power/power_actor.go
- actors/builtin/power/power_test.go
- actors/runtime/runtime.go
- support/mock/mockrt.go
closes #564
The actors will sometimes encounter problems for which aborting and losing state is not an option. Silently accepting the situation is not a good option either. A logging hook that can be integrated into the implementations native logging system provides a good in-between.
1. Add a logging method to Runtime with four log levels (WARN, INFO, WARN, and ERROR).
2. Add logging for purposely unhandled errors in power actor.
3. Modify MockRt implement the additional message and support testing of logging.
> add logging through runtime for power actor

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/monies.go
- actors/builtin/miner/monies_test.go
closes #561
Undetected faults have likely lived in an undetected state much longer than declared faults. To compensate, these late undetected faults should be charged 2x the undeclared fault penalty. This includes skipped recoveries as well.
1. Add logic in `processMissingPoStFaults` to separate faults older than one dead line from newer undetected faults.
2. Charge the new late undeclared penalty (2xSP) for these.
3. Alter `processSkippedFaults` to charge late undeclared penalty for skipped recoveries.
4. Add test logic to test declared recoveries and undeclared faults in `handleProvingPeriod`.
5. Add tests for the new behavior.
> older undetected faults penalized 2x SP

- actors/builtin/cron/cbor_gen.go
- actors/builtin/market/cbor_gen.go
- actors/builtin/power/cbor_gen.go
- actors/builtin/power/power_actor.go
- actors/builtin/power/power_state.go
- actors/builtin/power/power_test.go
Closes #266 
Closes #565 
This makes total power accounting work for small networks where no miner has the minimum needed consensus power.  It also makes `OnConsensusFault` do its power changes through `AddClaim` removing the accounting error from #565.  
The approach is very simple.  It wasn't 100% clear if this simple approach meets the issue requirements, so I want feedback on this high level plan.  We keep two more top level state counters in the power actor for the sum of all qa and raw claim power.  We then modify the `CurrentTotalPower` call to check whether the total number of miners above the minimum power is above some threshold (set to 3 before this pr).  If it's above we do things as before ignoring all claims from miners below the minimum threshold.  If its below we use the …
> Small Network Power Accounting

- actors/builtin/market/market_actor.go
- actors/builtin/market/market_state.go
- actors/builtin/market/policy.go
Closes #614 
Closes #622 
Closes #623 
Closes #624 .
* We now time out deals if they are scheduled for cron tick but they haven't been activated.
* Delete deal state correctly when deal is deleted.
* Calculate the remaining amount to return to client after slashing correctly.
* Simplify calculation of payment for storage.
* Ensure transfer amount isn't negative.
* A deal can be slashed before it's start epoch.
@whyrusleeping Tests will be in a separate PR I am creating for Cron Tick Tests.
> Market: Bug fixes in deal timeouts, deal deletion, payment transfers and slashing

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- actors/builtin/power/power_actor.go
Termination fees are supposed to be paid out of unlocked funds. We have been paying these fees without first unlocking them. This PR unlocks the funds before sending them to the burnt actor.
1. Unlock termination fees before burning them
2. Test that we have unlocked the fees.
3. Lint some whitespace issues from a previous commit.
Since a sector's initial pledge is the undeclared fault fee (SP) and the termination fee is (at max) the late undeclared fault fee (2*SP), there is no guarantee that the miner will have enough locked funds to pay the expected termination fee. In the case where the miner does not have sufficient funds:
1. The method will not abort.
2. All locked funds will be burnt
3. Unlocked available funds will not be touched.
This is consistent with other methods that charge …
> unlock termination fees before burning

- .golangci.yml
When building master on my local MacBook Pro, lint failed with the new plugin.
```
[~/p/f/specs-actors](anorth/nomaprange)$ make
go build ./...
golangci-lint run ./...
ERRO Unable to load custom analyzer nomaprange:.nomaprange.so, plugin: not implemented
ERRO Running error: no such linter "nomaprange"
make: *** [lint] Error 3
```
Unfortunately I don't have time to debug this right now, will return to it after #599.
FYI @Kubuxu thank you, sorry I didn't have time to investigate right away.
> Disable nomaprange linter plugin, failing on some systems

- actors/builtin/market/market_actor.go
> Market: Use ReadOnly transaction for ComputeDataCommitment

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/policy.go
partially addresses #416
If a miner attempts to put too many (8k) deals in a sector, the `PreCommitSector` will fail because the `DealID`slice in the `SectorOnChainInfo` won't marshal into CBOR. Having this many deals in a sector would require an average deal size that is far too low even for TB sectors, anyway.
We will limit the deals in a sector so that average deal size must be above 128MiB. Specifically, this is no more than 256 deals for 32GiB sectors and 512GiB sectors. For sector sizes less than 128MiB we will allow 1 deal.
1. Make the default StackedDRG32GiB the default seal proof type in tests with the option to change it.
2. Add `dealPerSectorLimit` function to policy.
3. Impose limit on deals per sector in `PrecommitSector`.
4. Test.
> limit deals in sectors

- actors/builtin/miner/cbor_gen.go
- actors/builtin/miner/policy.go
closes #637
PoSt proofs are sped up, so we we can reduce the PoSt Challenge window from 40 minutes to 30 minutes.
1. Change the `WPoStChallengeWindow` constant to represent 30 minutes worth of epochs. This affects the size of `deadlines.Due`, which forces a change in the miner's cbor encoding.
This parameter is already covered in various ways in the tests.
> change WPoStChallengeWindow to 30 mins of epochs

- actors/builtin/miner/policy.go
closes #605
Increase `FaultDeclarationCutoff` to challenge lookback + 50.
> increase FaultDeclarationCutoff to 50 per red team instructions

- actors/builtin/miner/miner_test.go
- actors/builtin/miner/policy.go
closes #598
Security concerns dictate we need a longer delay between pre- and prove-commit
1. Change `PreCommitChallengeDelay` to 150
2. Fix a test using some dodgy timing logic which broke because the commit got pushed into the next proving period.
> increase PreCommitChallengeDelay to 150

- actors/builtin/power/cbor_gen.go
- actors/builtin/power/power_actor.go
- actors/builtin/power/power_state.go
- actors/builtin/power/power_test.go
closes #413
Currently consensus processes may conspire so that a miner actor will end up scheduling a cron task in the power actor for an epoch that precedes the power actors last cron tick. If this happens the task will not be run and the data structure holding it will never be removed from power actor state.
1. Rename `power.State.LastCronTick` to `power.State.FirstCronEpoch` and alter its value to be the first epoch _after_ the last cron (or 0).
2. Add logic to move set `FirstCronEpoch` back if a task is set to an epoch at or before the last Cron tick.
3. Test that this allows tasks run in the past to execute on the next tick and that these tasks are garbage collected.
> process power actor cron tasks set in the past

- actors/builtin/miner/bitfield_queue_test.go
- actors/builtin/miner/expiration_queue.go
- actors/builtin/miner/expiration_queue_test.go
- go.mod
- go.sum
`ExpirationSet` and `ExpirationQueue` need testing.
1. `PopUntil` inaccurately returned `FaultyPower` as `ActivePower`
2. `RemoveSectors` double counted (or erroneously single counted from early sectors) `OnTimePledge` when removing it from an ExpirationSet
> add tests for expiration set and queue 

- actors/builtin/miner/bitfield_queue_test.go
- actors/builtin/miner/expiration_queue_internal_test.go
- actors/builtin/miner/expiration_queue_test.go
- actors/builtin/miner/quantize.go
This is a pure move, though required creation of a `NewQuantSpec` constructor function.
> Move queue tests to miner_test package

- actors/builtin/miner/expiration_queue.go
- actors/builtin/miner/expiration_queue_test.go
This version:
1. Removes on-time sectors first. These sectors can be anywhere in the queue.
2. Removes early sectors second. These sectors can only appear at the beginning (first 14 days/entries) in the queue.
Previously, when removing a bunch of on-time sectors, this function would have:
* State access linear in the length of the queue.
* A Runtime of (length of queue) * (number of sectors to remove).
> Optimize sector removal from expiration queue

- actors/abi/sector.go
- actors/builtin/init/init_actor.go
- actors/builtin/market/deal.go
- actors/builtin/market/market_actor.go
- actors/builtin/market/market_test.go
- actors/builtin/miner/deadlines_test.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_internal_test.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_state_test.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/policy.go
- actors/builtin/power/power_test.go
- go.mod
- go.sum
- support/mock/exports.go
- support/testing/cid.go
Filecoin VM assumes that all CIDs accessible from the state tree, other than ones with the `mh.SHA2_256_TRUNC254_PADDED`/`mh.POSEIDON_BLS12_381_A1_FC1` multihashes, are part of the state tree, and that every VM has access to them.
Getting unexpected CIDs into the state tree is currently a chain-halting bug, this PR should fix all instances of this problem, and make it harder to anciently introduce again
> Check input cids

- actors/builtin/multisig/multisig_actor.go
- actors/builtin/paych/paych_actor.go
- actors/builtin/paych/paych_test.go
I'm not sure if anything can actually go wrong in either of these cases, but this seems like something we shouldn't allow.
Q: ~Assert non-negative instead of positive?~
A: yes (done)
> Assert that payments are non-negative

- actors/builtin/miner/bitfield_queue_test.go
- actors/builtin/miner/partition_state.go
- actors/builtin/miner/partition_state_test.go
Partition inherits some testing from miner actor but has none of its own. Quite a bit of logic happens here, so some unit tests are in order.
1. Add tests for all exported methods of `Partition`.
1. `TerminateSectors` was adding removed power to `LivePower` rather than subtracting it. Fixed here.
Otherwise everything seems to be working.
> Partition testing

- actors/builtin/miner/deadline_state.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/sectors.go
This refactor:
1. Introduces a new "sectors" type to make it easy to operate on the sectors array multiple times without reloading it. The plan is to use this elsewhere as well, possibly passing it into deadline operations that need to access the sectors array.
2. Pushes fault declaration down into a method on the deadline. If this approach is acceptable, it can be extended to other methods.
At the moment, this refactor just demonstrates some ideas. If this looks like the way we want to go, I can extend it to all deadline operations.
> Refactor to push operations into deadline object

- actors/builtin/reward/reward_logic.go
Requested for lotus integration.
Convenience function of baseline given epoch.  It does as many multiplications as the epoch you want the baseline for so its not as fast as it could be but from tests I think its still on the order of seconds for epochs in the 9 years category so should be fine.
If we want something faster the right way is to read reward actor state to jump ahead.  Also it can be computed ahead / memoized in the consumer if it comes to that.
> Convenience baselineforepoch

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/partition_state.go
I also discovered the incorrect `LivePower` update fixed in #740.
This results on one additional but not-so-redudant write of the deadline partitions root in the deadline cron. We could resolve it by smashing together the different jobs of the cron handler, or with patterns to let us hold more in the air easily, but I'm not worried about it in the grand scheme of things right now.
I think these errors would be less likely as we push logic into the state/deadline. I opted for the direct fix here rather than larger refactor so I can focus on more tests.
> Restore CC upgrade test; fix power and pledge errors in deadline cron

- actors/builtin/market/market_actor.go
- actors/builtin/market/market_balances.go
- actors/builtin/market/market_test.go
- actors/util/adt/balancetable.go
- actors/util/adt/balancetable_test.go
This reverts commit cb5fd859feeea4d48c0c0561317ac331e96d8c6a.
We will want some of the changes back, but the specific mechanism of removing zero balances probably differently.
FYI @aarshkshah1992 this was causing failures in devnets.
> Revert "Market: Remove Zero balance accounts (#719)"

- actors/builtin/miner/bitfield_queue.go
- actors/builtin/miner/bitfield_queue_test.go
- actors/builtin/miner/cbor_gen.go
- actors/builtin/miner/deadline_state.go
- actors/builtin/miner/deadline_state_test.go
- actors/builtin/miner/miner_actor.go
Currently, this is only implemented for partitions with no faulty sectors.
TODO:
* https://github.com/filecoin-project/specs-actors/issues/756
> Implement partition compaction

- actors/abi/cid.go
- actors/builtin/market/deal.go
- support/mock/mockrt.go
- support/testing/cid.go
This is an alternative to https://github.com/filecoin-project/specs-actors/pull/783 which doesn't actually change the state structure.
Instead, this PR:
1. Adds proper support for inline CIDs (but doesn't actually crate them) so we can benchmark them without having to keep this patch lying around out-of-tree.
2. Centralizes the CID builder logic so we can change it easily.
> Central CID builder

- actors/builtin/market/market_actor.go
- actors/builtin/market/market_balances.go
- actors/builtin/market/market_test.go
- actors/util/adt/balancetable.go
- actors/util/adt/balancetable_test.go
This is motivated by #784. I think this is a much more robust way of cleaning up empty accounts.
Minor conflicts with #775, but please let this land first.
> Balance table treats absent entries as zero, never stores zeros

- actors/builtin/market/market_test.go
- actors/builtin/market/policy.go
closes #735
Deal lifetime must be at least 180 days and no more than 366 days (one leap year). Set this bound and fix the tests..
> set minimum deal duration to 180 days and fix tests

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/monies.go
- actors/builtin/miner/policy.go
closes #522
Initial pledge actually does need to be calculated at prove commit time, and precommit deposit does not need to be as large as initial pledge.
1. Introduce `PreCommitDepositForWeight` function in monies that depends on `ExpectedDayRewardForPower` but not on `InitialPledgeForPower` and delete the `precommitDeposit` function in miner_actor. Use the new function to compute a sectors `PreCommjitDeposit` in `PreCommitSector`.
2. Retrieve `baselinePower`, `epochReward`, `pwrTotal` and `circulatingSupply` at the beginning of `ConfirmSectorProofsValid` because we'll need them to compute initial pledge for sectors.
3. Use the `InitialPledgeForPower` function to compute the initial pledge for each sector. Set this in the `SectorOnChainInfo`. Also use it to compute the total pledge.
4. …
> recalculate sector intial pledge

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/policy.go
closes #734
We need to enforce both a minimum and a maximum sector lifetime.
1. Introduce `MinSectorExpiration` of `180*EpochsInDay` to miner policy.
2. Add check the sector meets minimum expiration criteria in miner actor `validateExpiration`.
3. Fix miner actor tests so that sectors that are supposed to be valid expire after at least 180 days.
4. Add test for minimum sector bound.
> set minimum sector expiration to 180 days

- actors/builtin/miner/miner_actor.go
The intent of the fault expiration epoch is to line up with an end-of-deadline cron, which happens at the end of the last epoch in a deadline. Confusion led me to instead schedule it for the first epoch of the next deadline, which would have the practical effect of delaying processing for one more proving period.
We haven't yet recovered enough tests to exercise this.
FYI @nicola
> Fix off-by-one in fault expiration epoch calculation

- actors/builtin/miner/cbor_gen.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_state_test.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/monies.go
- actors/builtin/miner/monies_test.go
closes #701 
Termination fees are a function of expected day reward (BR) evaluated at activation. We had been using the simple relationship between `InitialPledge` and BR to derive BR(start). That simple relationship has gone away, so we now need to store BR in sector info and use it in the terminate sector penalty calculation.
1. Add `ExpectedDayReward` field to `SectorOnChainInfo`.
2. Set this field in `ConfirmSectorProofsValid` when sector is activated.
3. Add `dayReward` as a parameter to `PledgePenaltyForTermination` and use it instead of dividing initial pledge by `IniitialPledgeFactor` (which is no longer correct).
4. Restore test to test TerminateSector to confirm the fee calculation is working.
Restoring the terminate sector test exposed a bug in miner.TerminateSectors. It was …
> Store BR in sector info and use it in sector termination penalty calculation

- actors/builtin/miner/deadline_state.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_test.go
- actors/builtin/shared.go
- actors/runtime/exitcode/exitcode.go
- actors/runtime/exitcode/exitcode_test.go
- actors/runtime/exitcode/reserved.go
This will make it easier to push state transformations down into the miner's state object.
I've also pushed some error messages down a layer to simplify/remove error wrapping.
fixes #597
> Allow errors to carry exit codes

- actors/builtin/miner/bitfield_queue.go
A test for this fix is in #838 but that's going to be a larger refactor.
> Don't add empty early termination records

- actors/builtin/cron/cron_test.go
- actors/builtin/init/init_actor.go
- actors/builtin/init/init_test.go
- actors/builtin/market/market_actor.go
- actors/builtin/market/market_state.go
- actors/builtin/market/market_test.go
- actors/builtin/multisig/multisig_actor.go
- actors/builtin/multisig/multisig_state.go
- actors/builtin/paych/paych_actor.go
- actors/builtin/paych/paych_test.go
- actors/builtin/power/power_actor.go
- actors/builtin/power/power_state.go
- actors/builtin/power/power_test.go
- actors/builtin/reward/reward_actor.go
- actors/builtin/verifreg/verified_registry_actor.go
- actors/builtin/verifreg/verified_registry_test.go
While auditing for #596 I fixed up easy/spurious missing coverage spots and fixed some exit codes.
- Use builtin.RequireNoErr() in some "impossible" error cases.
- Define some better exit codes using the new exitcode.Wrapf.
> Clean-ups while auditing code coverage.

- actors/builtin/miner/deadline_state.go
- actors/builtin/miner/deadline_state_test.go
- actors/builtin/miner/expiration_queue_test.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/partition_state.go
- actors/builtin/miner/sectors.go
This refactor pushes state changes down into the state & deadline objects, out of the miner actor itself.
This PR should be reviewed commit by commit.
> Move deadline mutations into deadline methods

- actors/builtin/miner/bitfield_queue_test.go
- actors/builtin/miner/bitfield_test.go
- actors/builtin/miner/deadline_state.go
- actors/builtin/miner/deadline_state_test.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/partition_state_test.go
1. Skip processing posts for completely faulty sectors.
2. When we reschedule sector expirations due to faults, update the per-deadline
bitfield.
Note: We're being a bit sloppy in step 2.
1. We're relying on faulty power to determine if we added any new faults. This works, but maybe we should return a boolean?
2. Technically, if the newly faulty sectors would have expired before the "max faulty" deadline, we won't reschedule their expiration. However, we'll still _record_ this expiration in the deadline's bitfield. Given the fact that this bitfield is best-effort anyways (e.g., we don't remove bits from it after recovering sectors), this should be fine. At worst, we'll try to pop expirations from a partition that has no expirations at that epoch.
> Update deadline expiration bitfield when rescheduling expirations due to faults

- actors/builtin/miner/deadline_state_test.go
We still need to improve our error-case testing (invalid sector numbers, invalid deadlines/partitions, etc.), but this should cover the rest of the non-error cases.
This patch covers:
* Retracted recoveries.
* Popping early terminations in multiple stages.
> Finish up deadline state testing

- actors/builtin/miner/cbor_gen.go
- actors/builtin/miner/deadline_state.go
- actors/builtin/miner/deadline_state_test.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/partition_state.go
- actors/builtin/miner/partition_state_test.go
The tests in #844 revealed that we're charging the ongoing fault fee for _all_ faulty power every deadline, rather than charging for the faulty power for that deadline. Moving the `FaultyPower` memo from miner to deadline state prompted me to check that we're maintaining it on each relevant operation, and realise that sector termination was ignoring the faulty state of some power, incorrectly subtracting it again.
> Don't pay all fees every deadline and fix termination faulty power

- actors/builtin/init/init_actor.go
- actors/builtin/market/market_actor.go
- actors/builtin/market/market_test.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/multisig/multisig_actor.go
- actors/builtin/paych/paych_actor.go
- actors/builtin/power/power_actor.go
- actors/builtin/reward/reward_actor.go
- actors/builtin/verifreg/verified_registry_actor.go
- actors/puppet/puppet.go
- actors/runtime/runtime.go
- support/mock/mockrt.go
This return value was a source of a couple of prior bugs, masked by Go's type checking semantics. I didn't find any more while making this change, so this is to prevent future ones.
Closes #616 
FYI @arajasek for integration, but I'll hold of landing this until after incentivized testnet starts.
> Remove return value plumbing from runtime state transaction

- actors/builtin/miner/miner_test.go
work towards #829
We had skipped many miner tests to simplify the miner state refactor. This PR brings some of them back
1. Modify to `actorHarness.submitPoSt` so that it chooses sectors for validation from sectors that are not skipped and not previously faulty.
2. Restore "skipped faults are penalized and adjust power adjusted"
3. Restore "skipped all sectors in a deadline may be skipped"
4. Restore "skipped recoveries are penalized and do not recover power"
5. Restore "skipping a fault from the wrong partition is an error"
6. Delete "detects faults from previous missed posts" from `TestSubmitPoSt` because that behavior now occurs in cron.
> recover skipped fault tests

- actors/builtin/miner/deadline_state.go
- actors/builtin/miner/deadline_state_test.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/partition_state.go
- actors/builtin/miner/partition_state_test.go
- actors/builtin/miner/sector_map.go
- actors/builtin/miner/sector_map_test.go
- actors/builtin/miner/sectors.go
- actors/builtin/miner/sectors_test.go
This patch introduces a new abstraction for walking sectors, but this one is
much simpler and reusable.
This patch also splits up sector expiration rescheduling into a state and a
deadline function (and pushes the partition invariants down into the partition
itself).
fixes #686
> Remove WalkSectors abstraction

- actors/builtin/miner/deadline_state.go
- actors/builtin/miner/expiration_queue.go
- actors/builtin/miner/expiration_queue_test.go
- actors/builtin/miner/partition_state.go
- actors/builtin/miner/partition_state_test.go
This PR validates that terminated sectors belong to the appropriate partition. This is already technically validated by the expiration queue, but I'd prefer to make it implicit.
> Enforce termination logic invariants in Partition object

- actors/builtin/miner/miner_test.go
- actors/builtin/power/power_test.go
- support/mock/mockrt.go
work towards #829
The miner state refactor broke a lot of tests. This PR brings some of them back.
1. Restore `handleProvingPeriod` cron tests that detected faults.
2. Restore `DeclareFaults` tests.
3. Restore `ExtendSectorExpiration` tests.
4. Fix surprisingly ubiquitous misspelling of `ExpectAbortContainsMessage`
5. Fix problem in `MockRT` where effectively equal messages and message expectations would appear unequal.
> more miner tests restored

- actors/builtin/miner/deadline_state.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/partition_state.go
- actors/builtin/miner/partition_state_test.go
Move fault handling logic into partition methods. This way, partition invariants can be enforced and tested on partition objects themselves.
Based on #875.
fixes #773.
> Move fault handling logic into partition methods

- actors/builtin/miner/deadline_state_test.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/partition_state_test.go
- actors/builtin/miner/sectors_test.go
This way, we can use these assertions from the miner state tests.
Based on #876. This is an entirely mechanical refactor paving the way for some state tests.
> Remove runtime from partition/deadline state assertions

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
work towards #829
The ReportConsensusFaults tests had been skipped for the miner state refactor. This PR restores that test and fixes a bug
1. Fix bug in `miner.requestTerminateDeals` that puts it in an infinite send loop if deals are present.
2. Remove skipped "faulty committed capacity sector not replaced". The case is covered in the test before it.
3. Restore report consensus fault test.
4. Add report consensus fault test for the case where sectors containing more than 8k deals are being terminating (resulting in multiple sends to the market actor's `OnMinerSectorsTerminate`.
> restore report consensus fault test, and fix terminate sectors bug

- actors/abi/big/int.go
- actors/abi/big/int_test.go
> Enforce BigIntMaxSerializedLen when marshalling CBOR

- actors/builtin/reward/reward_actor.go
- actors/builtin/reward/reward_test.go
> Reward Actor: Do not abort on sending funds to the miner

- actors/builtin/miner/expiration_queue.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
* Avoid taking a reference to the loop variable.
* Sum power/pledge on sector extension.
* Test extending sectors from multiple partitions. This test is unfortunately slow (5s), we can probably speed up the sector adding logic.
fixes #864, #865.
> Sum pledge/power on sector extension and fix go gotcha

- actors/builtin/miner/bitfield_test.go
- actors/builtin/miner/deadlines.go
- actors/builtin/miner/deadlines_test.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_state_test.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/sector_map_test.go
This also adds a test for sector assignment which should test this quantization.
fixes #739
> Quantize sector expiration queues per-deadline

- actors/builtin/miner/cbor_gen.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/policy.go
- actors/crypto/randomness.go
merge after #679 
This prevents posts from being replayed on distant forks and helps to protect filecoin against long range attacks.
cc @magik6k as this implies miner changes
> Commit windowed post submissions to a particular chain

- actors/builtin/miner/sector_map.go
This hint shouldn't actually make a difference in practice, but @anorth pointed out that it's inaccurate and could, in theory, cause the compiler to allocate fewer buckets than it otherwise would, causing more allocations.
In the interest of simplicity and clarity (1 was a lower bound, not a true hint), I'm removing it.
see https://github.com/filecoin-project/specs-actors/pull/861#discussion_r464137297
> Avoid pre-allocating with inaccurate hints

- actors/abi/bitfield.go
- actors/abi/bitfield_test.go
- actors/builtin/miner/bitfield_queue.go
- actors/builtin/miner/bitfield_queue_test.go
- actors/builtin/miner/bitfield_test.go
- actors/builtin/miner/cbor_gen.go
- actors/builtin/miner/deadline_state.go
- actors/builtin/miner/deadline_state_test.go
- actors/builtin/miner/expiration_queue.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_state_test.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/partition_state.go
- actors/builtin/miner/partition_state_test.go
- actors/builtin/miner/sector_map.go
- actors/builtin/miner/sector_map_test.go
- actors/builtin/miner/sectors.go
- actors/builtin/miner/termination.go
- actors/builtin/miner/termination_test.go
- go.mod
- go.sum
Unfortunately, by-pointer bitfields meant we needed to check for nil bitfields in function parameters. Given the fact that we rarely do this, it's safer to just use bitfields by-value.
Note: "zero"/uninitialized bitfields are still valid for reading. However, updating a zero-value/uninitialized bitfield will cause a panic.
Part of https://github.com/filecoin-project/specs-actors/issues/895
Depends on https://github.com/filecoin-project/go-bitfield/pull/44
> Switch to by-value bitfields

- actors/abi/cid.go
Unlike #783, this doesn't enable inline CIDs directly. However, it does make it possible to test changes to the CID Builder.
> Support inline CIDs for testing

- actors/builtin/miner/cbor_gen.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/policy.go
- actors/crypto/randomness.go
This prevents posts from being replayed on distant forks and helps to protect filecoin against long range attacks.
Replaces #680, which I accidentally merged into the wrong branch.
cc @magik6k @whyrusleeping
> Commit windowed post submissions to a particular chain.

- actors/builtin/init/init_actor_state.go
- actors/builtin/init/init_test.go
The init actor's `State.ResolveAddress` returns a sentinel `ErrAddressNotFound` if the resolution fails. This is a more fragile pattern than distinguishing between an actual state error and a negative lookup statically.
Lotus appears to have six instances of testing for `ErrAddressNotFound`. Hopefully that corresponds to all the cases where the behaviour should differ, but after this we'll have to be explicit about any cases where it doesn't.
This is a proposal, I won't merge it unless Lotus team are in favour. FYI @magik6k .
> Add boolean found return value to init state address resolution

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- support/mock/mockrt.go
closes #795
It's probably not possible for prove commit to occur past a valid sector's lifetime, but if it does, it will trigger panics in the power math, causing all the other sectors to fail. This PR check that the sector lifetime is less than equal to zero and skips the sector if so.
1. Use current epoch + MaxSealDuration for activation time when validating in precommit.
2. Add check that sector duration meets or exceeds minimum in prove commit, and skip sector if not.
3. Test
> avoid prove commit aborts when sector lifetime <= 0

- actors/builtin/reward/reward_actor.go
I can't think of a reason why this should be called three times like this
> Remove duplication of balance retrieval in reward actor

- actors/builtin/multisig/multisig_actor.go
- actors/builtin/multisig/multisig_test.go
- actors/builtin/shared.go
For #730.
@anorth We should move the `resolveToIdAddr` func to a common location so the `Verifreg` and `PaymentChannel` actors can use it too.
> Multisig: State should ONLY have ID address -> create accounts if they do NOT exist

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
Closes #547 .
@anorth Do we need to write a test for each of the functions we've touched by setting the caller as the owner and ensuring things work ? Looks like adding a lot of testing code to test a simple change. Let me know.
> Miner: Allow owner key to act as miner

- actors/builtin/account/account_actor.go
- actors/builtin/account/account_test.go
- support/mock/mockrt.go
`*Address` implements `CBORMarshaler` now, not `Address`. I was planning on handling this in the lotus runtime and just auto-referencing/dereferencing, but that's not worth the additional complexity.
> Return Address by-pointer.

- actors/builtin/miner/cbor_gen.go
- actors/builtin/miner/deadline_state.go
- actors/builtin/miner/deadline_state_test.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_state_test.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/monies.go
- actors/builtin/miner/monies_test.go
- actors/builtin/miner/partition_state.go
- actors/builtin/miner/partition_state_test.go
closes #532
Termination fees for a sector increase  with time (up to a limit), so a miner that needed to terminate a sector could replace with a younger sector and terminate for a smaller fee. This PR addresses that issue by taking the replacement into account when charging a termination fee.
1. Add `ReplacedSectorAge` and `ReplacedDayReward` to `SectorOnChainInfo` to use in our termination fee calculation.
2. Set the parameters above in `ConfirmSectorProofsValid`.
3. Alter the `PledgePenaltyForTermination` to take the the parameters above as arguments and use them to charge for the old sector's lifetime at its expected day rate up to the 70 day limit.
4. Test.
> increase sector termination fee for replaced capacity sectors

- actors/builtin/market/deal.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/policy.go
- actors/builtin/multisig/multisig_state.go
- actors/builtin/paych/paych_actor.go
- actors/builtin/paych/policy.go
- actors/builtin/verifreg/verified_registry_actor.go
* Limit the size of the peer ID to 128 bytes.
* Limit the total size of all multiaddrs combined to 1024 bytes, and forbid empty multiaddrs.
* Require at most one window post and require that it (if present) match the miner's declared proof type. This should be fine (?) given that we don't currently support changing proof types at runtime anyways.
* Cleanup expiration validation.
* Validate "max sector number" in a couple of places. Honestly, this isn't strictly speaking necessary, but it's nice to do.
* Log if we somehow end up trying to confirm more sector proofs than we should.
* Verify that we don't allow extending sector expirations after their expiration.
* Limit payment channel secrets to 256 bytes. Really, they shouldn't ever be more than 32.
* Limit seal proofs to 1KiB.
> Check parameters

- actors/builtin/power/cbor_gen.go
- actors/builtin/power/power_actor.go
- actors/builtin/power/power_state.go
Closes #906 .
@anorth I am not sure if further simplification is possible. 
We need to keep the `FirstCronEpoch` around because it allows us to schedule past epochs in call to `EnrollCronEvent`.
Let me know if you have any ideas.
> Power: Don't track last epoch for cron

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/monies.go
Computes a per-byte initial pledge cap so that a 32GiB sector is fractionally under 1 FIL.
- Pre-commit deposit remains BR(20)
- Termination fee is unchanged; still includes BR(20) plus the approximation of rewards earned.
The cap is a `var`, and evaluated only when a pledge calculation is made, so Lotus can override this, e.g. effectively disabling it by setting a higher value.
This PR is against the `release/v0.9` branch, not `master`. After merge, a new release can be made from this branch head.
> Cap 32GiB sector initial pledge to 1FIL for Space Race (hotfix)

- actors/builtin/miner/cbor_gen.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/policy.go
This change gets rid of the variable ChainCommitRand parameter and fixes it to be `DeadlineOpen - WPoStChallengeLookback`.
This makes it easy for lotus to extract randomness from the chain at the beginning of the challenge window such that:
1. The randomness is stable and won't change due to reverts. The WPoStChallengeLookback should ensure this.
2. No WPoSt message will become _invalid_ before the challenge window ends.
Before, if lotus picked a commit epoch that was too far in the past, it ran the risk of not being able to submit the proof in time. However, if it picked a recent epoch, it ran the risk of a revert changing the chain.
> Change the WPoSt commit randomness lookback to match the proof challenge epoch

- actors/builtin/market/market_actor.go
- actors/builtin/market/market_test.go
I don't _believe_ this can be abused, but we might as well check it.
> Detect and reject duplicate deal IDs on verify.

- actors/builtin/miner/miner_test.go
- actors/builtin/miner/policy.go
There is on need to have pledgeVestingSpec, since the InitialPledgeRequest is for and only for the effective power.
> PledgeVestingSpec is not used any more

- actors/builtin/paych/cbor_gen.go
- actors/builtin/paych/paych_actor.go
- actors/builtin/paych/paych_test.go
- gen/gen.go
This field is an arbitrary saved method invocation so we need to pass the parameters as the method parameters, instead of wrapping them.
Note: this means that the party redeeming the payment channel voucher cannot submit an additional "proof" parameter. But that shouldn't be necessary.
Fixes #971
> Fix Extra field in payment channel vouchers

- actors/builtin/miner/cbor_gen.go
- actors/builtin/miner/deadline_state.go
- actors/builtin/miner/deadline_state_test.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_state_test.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/partition_state.go
- actors/builtin/miner/partition_state_test.go
- actors/builtin/miner/sectors.go
- support/mock/mockrt.go
This will need a lot of tests, and the existing tests are now all broken.
Every partition gets a new `Unproven` bitfield for sectors that have yet to be proven and an `UnprovenPower` field store power to be proven and activated when the partition is next proven.
Crucially, new faulty power from unproven sectors is never removed from the miner, because it was never activated. Furthermore, unproven power is _added_ to the miner when it's proved the first time. To achieve this, many methods have gained `poweDelta` return values.
When marked faulty, unproven sectors are removed from the unproven bitfield and added to the faulty bitfield. They now join the normal fault flow.
Unproven sectors may be terminated (early) like any other sector.
On WindowPoSt, skipped unproven sectors are added to …
> Delay power until first window PoSt

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/policy.go
Closes #672
fyi @nicola not changing any numbers yet but splitting out so we can.  Should we be changing either of these from 10,000?  If so this PR would be a natural place.
> Split seal delays into randomness lookback and max porep duration

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
Closes #965 
A miner cannot pre-commit, withdraw funds or recover sectors after a consensus fault.  @nicola @anorth I think we are mostly all aligned here after discussion on issue.  The one remaining thing to hash out is whether these are the correct methods to be disallowing.  I kept the same set that we do IP requirement / fee debt checking on.  However in the issue @nicola mentioned ProveCommit which isn't included here and didn't mention WithdrawBalance which is included here.
> Disallow miner actions after consensus fault

- actors/builtin/multisig/cbor_gen.go
- actors/builtin/multisig/multisig_actor.go
- actors/builtin/multisig/multisig_test.go
Closes #511.
@anorth Turns out we were missing tests related to the vesting/locking of funds. Have added them in this PR. Please take a look.
> Multisig: Allow configurable vesting Start

- actors/test/miner_scenario_test.go
- support/vm/invocation_context.go
- support/vm/testing.go
- support/vm/vm.go
We want to have confidence that the flow from creating a miner through committing a sector, all the way through submitting a PoSt work. This test does that at a high level. It confirms that All the method invocations involved in that flow and all their sub-invocations succeed. It does this without getting into the details of what the logic does or specifying inputs and outputs which should be handled by various unit tests.
1. Add `TestCommitPoStFlow` with happy path and a few error cases.
2. Fix bug in VM that returns the wrong current balance.
3. Fix bug in construction of market actor in testing setup.
4. Add functions to advance time by miner deadlines and get current epoch.
Error cases are forthcoming.
> miner create->PoSt scenario test

- actors/builtin/miner/miner_test.go
When a committed capacity sector is replaced by two new sectors, both new sectors should succeed, but the old sector should only be replaced once.
Most of this test is copy/paste, but reduplicating the logic is probably more trouble than it's worth.
> Test replacing a committed capacity sector twice.

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- actors/builtin/reward/cbor_gen.go
- actors/builtin/reward/reward_actor.go
- actors/builtin/reward/reward_state.go
- actors/builtin/reward/reward_test.go
I think using the instantaneous version was an oversight, since all other penalties use the smoothed version.
Removed the now-unused instantaneous version from the return struct to prevent accidental use.
> Remove ThisEpochReward from ThisEpochRewardReturn, and use smoothed value for conesnsus fault penalty

- actors/runtime/exitcode/reserved.go
- support/mock/mockrt.go
`SysErrSerialization` is already unused in Lotus. https://github.com/filecoin-project/lotus/pull/3184 removes use of `SysErrInvalidParameters`.
Serialization is logically part of actor code, not VM code, so we use `ErrSerialization` instead.
FYI @raulk
> Rename deprecated exit codes SysErrSerialization and SysErrInvalidParameters

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_test.go
* Moves most logic into helper functions.
* Avoids loading deadlines, vesting table, etc. unnecessarily.
* Loads the vesting table at most twice. Once to unlock vested funds, once to unlock unvested funds for penalties.
fixes #983
> Refactor deadline handling

- actors/builtin/miner/cbor_gen.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_state_test.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/monies.go
- support/vm/testing.go
After a proposal from @wadeAlexC and brief discussion with @acruikshank and @anorth I wanted to see how this refactor looks.  This is to help make the discussion concrete -- we're not necessarily going to merge this.
Pros: the simplification is real, both in the actor code, the mental model and in the reduction of separate cases to test.  By doing all fee debt repayment lazily very little new code needs to be added.
Cons: one upside that's come to light with the current strategy of applying initial pledge to fee payment up front is that dead miners that have incurred fees always pay all of their initial pledge requirement to burnt funds without intervention.  After this refactor it is possible for a miner that is no longer worth maintaining to be abandoned with lots of fee debt and lots …
> IP accounting refactor

- actors/builtin/power/power_state.go
- actors/builtin/power/power_test.go
- actors/test/commit_post_test.go
- actors/test/committed_capacity_scenario_test.go
- support/vm/invocation_context.go
- support/vm/testing.go
- support/vm/vm.go
We want to integration test more of the actor code, and a capacity upgrade for a sector containing deals is a good way to hit a lot of different actor functionality including the verified registry and market actor
1. Add `TestReplaceCommittedCapacitySectorWithDealLadenSector`
2. Move scenario tests into their own files named after flow under test instead of primary actor.
3. Add public `GetClaim` method to `power.State` to permit retrieval power.
4. Various small changes to test vm to ease testing.
5. Additions to vm testing to advance till a sectors proving period and methods to inspect power state.
cc @wadeAlexC
> miner capacity upgrade scenario test

- actors/builtin/miner/deadline_state.go
- actors/builtin/miner/partition_state.go
- actors/builtin/miner/partition_state_test.go
Implicitly relying on faulty power being non-zero could potentially bite us in the future.
fixes #1040
> Explicitly specify whether or not faults were added in RecordSkippedFaults

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
closes #1021 
work unaddressed in #1035
We currently require a precommit deposit for cc upgrades greater or equal to the initial pledge of the replaced sector. We do not put any requirements on the cc upgrade's initial pledge. This is backwards. PCD should have no bound and initial pledge should have a lower bound of the replaced sector's IP.
1. Remove lower bound for PCD for cc upgrades.
2. Add lower bound for initial pledge for cc upgrades.
3. Fix tests to reflect this.
> remove requirement for pcd>=replaced.pcd and add one for initialPledge

- actors/abi/big/int.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- actors/test/commit_post_test.go
- support/vm/invocation_context.go
The miner actor harness previously reported an amount of verified deal weight even when a sector has no deals, which confused me a lot when debugging some pre-commit deposit calculations. It now records non-zero deal weight only if the sector has a deal.
The weight reported was an odd amount: the sector size. I fixed this to be a product of sector size and duration, and discovered #1038.
I also removed an unnecessary call to the market actor to compute deal weight for no deals.
> Skip requesting deal weight for no deals; fix confusing deal weight in tests

- actors/abi/sector.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
Re-arranged to group the information for each proof type together, but retained the existing accessor methods to reduce churn. 
Closes #1044. FYI @nicola
> Reorganize seal proof metadata

- actors/test/committed_capacity_scenario_test.go
- support/vm/testing.go
follow up to #1030
CC upgrades have a happy-path scenario test. We want to check some of the unhappy scenarios as well.
1. Add test for when a miner fails to prove a sector containing verified deals that the bytes are returned to registry when deals are deactivated.
2. Add test for when a miner misses first PoSt for cc upgrade sector that power for both sectors is removed.
3. Add test for when a miner skips a CC upgrade sector in first PoSt that sector is faulted and power is unchanged.
> add some unhappy scenarios for cc upgrade

- actors/abi/sector.go
- actors/builtin/market/market_test.go
- actors/builtin/market/policy.go
- actors/builtin/miner/expiration_queue.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/monies.go
- actors/builtin/miner/partition_state_test.go
- actors/builtin/miner/policy.go
- actors/builtin/miner/sectors.go
- actors/builtin/network.go
- actors/builtin/power/policy.go
- actors/builtin/power/power_test.go
- actors/builtin/shared.go
We are auditing the parameters, making sure that they have the correct values and the correct description. We are writing in front on all of them the `Filecoin Parameter:` prefix so that they will be easy to search in the future.
Closes #699
Moved here: https://github.com/filecoin-project/specs-actors/issues/793
Parameters that I am not seeing:
- AddressedSectorsMax
- WPoStPeriodDeadlines ([notes](https://hackmd.io/478poL-pQdq_qRKFEHTLTw?view))
- ChainFinality
- [RegisteredSealProof.SectorMaximumLifetime()](https://github.com/filecoin-project/specs-actors/blob/60a2ae96d2e656e2c4536a8f1ee905834e758912/actors/abi/sector.go#L206-L211) (SDR)
- MaxSealDuration
- ConsensusMinerMinMiners
- InitialPledgeFactor
- AddressedPartitionsMax
- MinDealDuration
- MaxDealDuration
- DealUpdatesInterval
- …
> Specs Actors Params Audit 

- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_state_test.go
- actors/builtin/power/power_state.go
Closes #887
- Election eligibility depends on the power state check for minimum power
- Fix obo in that power state check (zero power should not be eligible)
- Test
> Restrict election eligibility on min power

- actors/abi/sector.go
- actors/builtin/miner/policy.go
From @anorth's [comment in slack](https://filecoinproject.slack.com/archives/C015KQQLQQ1/p1598870159002300):
> @zenground0 some quick fixes following the param  audit PR
> - the number 1_262_277 in sector.go is wrong for 30s epochs. I thought I'd fixed it, but must be lost in rebases
> - the PR changed finality to 1400 - I think I just missed this. Plz change it back to 900 and we can continue discussion in https://github.com/filecoin-project/specs-actors/pull/702
For epochs in year I maintained consistency by dividing `SECONDS_PER_YEAR` from `reward/reward_calc.py` by 30.
> Fix finality and epochs per year

- .gitignore
- actors/builtin/market/cbor_gen.go
- actors/builtin/market/market_actor.go
- actors/builtin/market/market_test.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- gen/gen.go
closes #1038 
That the total spacetime of a sector's deals does not exceed the spacetime of the sector is an invariant of the system. We assert this in `QAPowerForWeight` to avoid a nonsensical result. Our market actor deal verification ensures that a miner cannot publish a deal for a sector that exceeds the sector's time bounds (either estimated at precommit, or actual at prove commit). The syscall to compute the unsealed CID must fail if the space of all deals exceeds the sector size (else it would be forced to compute with negative padding), so sector commitment will fail at `ProveCommitSector` if deal space is too large.
It is still possible for a miner to violate the deal spacetime invariant in precommit, however by publishing deals that are too large prior to calling …
> confirm deal space does not exceed sector size in precommit.

- actors/builtin/methods.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
closes #982
closes #806
Cron calls are costly. We don't need to be adding them for worker key updates. Instead we can check for worker updates in existing cron calls at deadline end and and provide an additional actor call if more precision is required.
1. Add `miner.ConfirmUpdateWorkerKey` method to immediately enact a worker key change if one is ready to be enacted.
2. Modify `ChangeWorkerAddress` to skip enrolling a cron job to enact the worker change.
3. Modify `ChangeWorkerAddress` to cancel an existing change if a change exists and the worker address is the same as the original.
4. Process PendingWorkerKeys in `provingPeriodUpdate` by check if the effective time has past and updating worker address if so.
5. Remove code related to `commitWorkerKeyChange` cron call.
6. test
cc …
> Remove change worker cron and add confirm update worker key method

- actors/abi/primitives.go
- actors/builtin/miner/miner_actor.go
It should never be larger than this.
> Limit chain-commit randomness length to 32 bytes.

- actors/builtin/market/market_actor.go
- actors/builtin/market/market_test.go
- actors/builtin/market/policy.go
- actors/builtin/multisig/multisig_actor.go
- actors/builtin/multisig/multisig_state.go
- actors/builtin/multisig/multisig_test.go
- actors/builtin/multisig/policy.go
* Restrict deal label size to 256 bytes.
* Restrict number of multisig signers to 256 (~16KiB max).
fixes https://github.com/filecoin-project/specs-actors/issues/897
> Bound size of state

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/policy.go
The total number of operations is implicitly specified in the partition limits, but we might as well limit the number of declarations as well. Otherwise, a miner could force the chain to perform additional work handling inefficiently encoded messages.
part of #416
> Explicitly limit the number of declarations in miner methods

- actors/builtin/power/power_actor.go
- actors/test/cron_catches_expiries_scenario_test.go
closes #909
Sectors replaced by cc upgrades should terminate at the end of their proving deadline. This works unless the sector is replaced at the end of its proving period deadline (i.e. it is replaced and expected to be terminated in the same epoch). This due to the ordering of cron events triggered in power actor. The sector is flagged for termination in batch proof verifies, but that is run after `handleProvingPeriod` that actually processes all the pending terminations. Swapping the order of batch proof verifies and deferred cron events are triggered corrects the problem.
1. Swap order of `processBatchProofVerifies()` and `processDeferredCronEvents()` calls in power actor `OnEpochTickEnd`.
2. Add scenario test that demonstrates the problem and its correction.
cc @wadeAlexC
> swap order of batch proof verifies and deferred cron events

- actors/builtin/market/market_actor.go
- actors/builtin/market/market_test.go
- actors/test/market_withdrawl_test.go
- support/vm/invocation_context.go
- support/vm/vm.go
closes #1075
Although nothing specifically prevents it in actor code, validating caller types more than once in a method is prohibited and causes an abort in Lotus. This double validation occurs in `market.Actor.WithdrawBalance`. The call to `ValidateImmediateCallerType` is unnecessary, so we should remove it.
1. Simulate multiple validation calls abort in scenario test vm.
2. Add scenario test for adding and withdrawing collateral to demonstrate the problem.
3. Delete `ValidateImmediateCallerType` in `market.Actor.WithrdrawBalance`.
> remove ValidateImmediateCallerType from market WithdrawBalance

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_internal_test.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_state_test.go
- actors/builtin/miner/miner_test.go
closes #946
Previously, a new miner's first (partial) proving period was special in that we did not run the proving period cron until the end of the first proving period after the miner's creation. This creates an undesirable situation where a miner can pre-commit and prove-commit sectors before they are in a proving period. They cannot however PoSt for these sectors or gain power from them, but they would not be faulted for failing to PoSt when a PoSt is due.
This PR eliminates the special period between miner's creation and the first proving period. This is done by initializing miner state with a `ProvingPeriodStart` that precedes the current epoch and setting the `CurrentDeadline` to the index appropriate to the current epoch. We then set the next proving period cron for the last epoch …
> allow/require PoSt in miner's first proving period

- actors/abi/big/int.go
- actors/abi/big/int_test.go
- actors/builtin/reward/reward_logic.go
- actors/builtin/reward/reward_logic_test.go
- actors/util/smoothing/alpha_beta_filter.go
- actors/util/smoothing/alpha_beta_filter_test.go
Avoid having to push through the abstraction every time. This was prompted by version/migration concerns.
This follows the docs recommendations about copying. Please lmk if you think this should take a `*big.Int` instead.
> Add big.NewFromGo constructor

- actors/builtin/methods.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
closes #1072
If a miner goes into fee debt, the worker can pay it off by adding balance and then pre-committing a sector, recovering a fault. If the worker doesn't have a sector to precommit or a recovered fault they must wait for the deadline end for the debt to be paid. This PR adds a `RepayDebt` method to trigger that mechanism immediately.
1. Add `miner.RepayDebt` that calls `miner.State.RepayPartialDebtInPriorityOrder` and burns the appropriate funds and notifies of any pledge change due to fee payment from vesting funds.
2. Add unit tests for new method.
> add method to repay debt

- actors/abi/sector.go
- actors/builtin/miner/miner_state_test.go
- actors/builtin/power/cbor_gen.go
- actors/builtin/power/policy.go
- actors/builtin/power/power_actor.go
- actors/builtin/power/power_state.go
- actors/builtin/power/power_test.go
closes #1027
The security of a miner's eligibility for election is affected by the total power the miner has on the network, but also on the miner's sector size. This PR modifies all consensus power threshold calculations to be a function of miner sector size (proof type) and sets the value for 64GiB sectors to twice the previous minimum which is still appropriate for 32GiB sectors.
1. Add `ConsensusMinerMinPower` to seal proof info.
2. Set values for the above: 32GiB is unchanged, 64GiB is 2x, all the rest (unused in production) are zero.
3. Add `SealProofType` to power actor's `Claim` type.
4. Initialize above to miner `SealProofType` to miner's proof type when miner is created. Copy it for each claim update.
5. Use above to derive minimum power in `power.State.addToClaim` and …
> adjust min miner size for 64 g

- actors/abi/sector.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_state_test.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/partition_state_test.go
- actors/builtin/power/power_state.go
- actors/builtin/power/power_test.go
Separates the conceptually fixed associations between proof types from the policy about how they are used (that could conceivably change in a protocol upgrade).
This is in preparation for integrating https://github.com/filecoin-project/go-state-types/pull/1, which moves the values and metadata to a new repository.
> Separate seal proof type metadata from policy

- actors/builtin/methods.go
- actors/builtin/miner/cbor_gen.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- actors/builtin/power/power_actor.go
- actors/test/commit_post_test.go
- actors/test/committed_capacity_scenario_test.go
- actors/test/cron_catches_expiries_scenario_test.go
1. Adds ChainCommitEpoch back to the SubmitWindowPoSt params.
2. Reverts the method number changes for SubmitPoRepForBulkVerify and CurrentTotalPower.
> Revert some API changes to make the network upgrade easier

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
closes #1008
A miner should only be penalized (and reported rewarded) once for a consensus fault. The most straightforward way to do this is to prevent any consensus fault reports for a miner until the miner's existing consensus fault penalization period has expired.
1. Abort `ReportConsensusFault` if current epoch < `miner.Info.ConsensusFaultElapsed`.
2. Test that this prevents duplicate consensus fault reports.
> abort consensus fault reports when miner is already under fault

- actors/builtin/miner/policy.go
closes #1012
`MaxPreCommitRandomnessLookback` and `MaxProveCommitDuration` had been placeholder values. We now have numbers that we think are secure and usable. This PR updates the constants to these values.
1. Change `MaxPreCommitRandomnessLookback`
2. Change `MaxProveCommitDuration`
> update MaxPreCommitRandomnessLookback and MaxProveCommitDuration

- actors/builtin/power/power_actor.go
- actors/builtin/power/power_state.go
- actors/builtin/power/power_test.go
- actors/util/adt/map.go
closes #1056
When a miner's cron tasks fail, the miner is in a bad state and could potentially put power in a progressively worse state as time progresses. Zeroing out miner power helps, but it is not enough. This PR deletes the miner claim altogether when cron fails and makes the existence of a claim a requirement for most interactions between the miner and the power actor.
1. On failure in `processDeferredCronEvents` delete miner's claim altogether.
2. In `UpdatePledgeTotal` and `SubmitPoRepForBulkVerify`, abort if miner has no claim.
3. In `processBatchProofVerifies` and `processDeferredCronEvents` skip and log actions for miner's that have no claim.
4. Fix existing power tests that mostly broke because miner was never initialized.
5. Add tests for new functionality.
6. Skip …
> delete miner claim after cron failure

- actors/builtin/market/market_actor.go
- actors/builtin/market/market_test.go
- actors/builtin/market/policy.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_internal_test.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/monies.go
- actors/builtin/miner/monies_test.go
- actors/builtin/miner/policy.go
- actors/runtime/runtime.go
- support/mock/mockrt.go
This is an inline upgrade for Space Race, adjusting some crypto-economic parameters to reduce penalties and deal collateral. From version `1` the actor code will behave differently, but no existing state will be migrated.
This PR is against the release/v0.9 branch. The changes are to be subsequently cherry-picked to master, where we can drop the handling of network v0 (which will be handled by major release versioning).
- Adds `NetworkVersion()` call to Runtime
- v1: Reduce reward vesting cliff to zero
- v1: Reduce undeclared fault penalty to 3BR
- v1: Halve the sector age penalised in termination fee
- v1: Reduce min provider deal collateral to 1% of share, based on _raw_ power
FYI @whyrusleeping @magik6k @Stebalien
> Reduce vesting cliff, penalties, min deal collateral on network v1

- README.md
pkg.go.dev provides slightly better DX to browsing github when refering to the API
> docs: add pkg.go.dev badge to README

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/monies.go
This was implemented on the 0.9 branch for Space Race in #997, and is to be preserved for mainnet.
This is a cherry-pick, followed by a fix to a test with a now-broken assumption.
> Implement cap of 1 FIL / 32GiB cap on initial pledge

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
This was useful when there were many miner actor methods which accumulated things by this key, but now that's all pushed down into deadline and partition state objects.
> Remove PartitionKey type

- actors/builtin/market/market_actor.go
- actors/builtin/market/market_test.go
- actors/builtin/market/policy.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_internal_test.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/monies.go
- actors/builtin/miner/monies_test.go
- actors/builtin/miner/policy.go
- actors/runtime/runtime.go
- actors/runtime/types.go
- support/mock/builder.go
- support/mock/mockrt.go
- support/vm/invocation_context.go
- support/vm/vm.go
This is #1104, interpreted for v2.
- Add network version to runtime
- Implement reduced sector penalties and reward vesting cliff
- Reduce deal min provider collateral
- Fix tests missing expectations about rewards vesting after only 1 proving period
This version does not implement the `if rt.NetworkVersion() >= 1` tests because actors v2 is never intended to run on any before 2. To evaluate network versions 0 and 1, use `release/v0.9`. This demonstrates that those inline upgrades do not accumulate over time.
Based on c6ce28641f59c44af1594058f92bac67edb17664 from release/v0.9.
FYI @Stebalien @arajasek @magik6k
> Reduce vesting cliff, penalties, min deal collateral.

- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_state_test.go
- actors/states/election.go
- actors/states/election_test.go
The miner election eligibility predicates need to be split into one that operates on the parent state, and one at the Winning PoSt lookback.
- Move the predicates into a new `states` package intended for use from outside the actors themselves
- In `MinerEligibleForElection` change the consensus min power check to a non-zero claim check
- Add `MinerEligibleForElectionAtPoStLookback` which checks for consensus min power
- Rework tests to not use the mock runtime or other higher level stuff
Closes #1102
FYI @nicola @whyrusleeping @magik6k
> Rework election eligibilty predicates

- actors/builtin/methods.go
- actors/builtin/multisig/cbor_gen.go
- actors/builtin/multisig/multisig_actor.go
- actors/builtin/multisig/multisig_state.go
- actors/builtin/multisig/multisig_test.go
- gen/gen.go
In actors v2, a multisig's vesting start epoch can be set at construction, but in testnet it is always set to the epoch of construction. This PR adds a `LockBalance` method which allows the same vesting initialization for a multisig that was not initially configured with a locked amount. The vesting can only be configured via proposal from the multisig itself
This allows integration partners using the testnet to test out multisig vesting workflows etc prior to a full upgrade to v2.
~We can deploy this into the testnet as a backwards compatible change **if the  Lotus VM rejects method `9` for a multisig actor before the upgrade epoch**.~
Edit: Lotus does not yet prevent actors aborting with system exit codes, so I've added a test of the network version, and abort with `SysErrInvalidMethod` …
> Add LockBalance method to set vesting schedule on non-vesting multisig (v0.9)

- actors/builtin/miner/expiration_queue.go
- actors/builtin/miner/expiration_queue_test.go
closes #1064
The expiration set stores important state that affects power and pledge accounting. It is important that the accounting that happens in the expiration set and expiration queue, is correct. This PR adds validation of several expiration set invariants to all operations that alter expiration sets. 
1. Add `ExpirationSet.ValidateState` method.
2. Call `ValidateState` after every operation that modifies expiration set state.
3. Fix a test that broke due to an invalid setup (it recovered a sector that had not been faulted).
cc @wadeAlexC
> Add assertion that expiration set is valid

- actors/builtin/miner/expiration_queue.go
- actors/builtin/miner/expiration_queue_internal_test.go
- actors/builtin/miner/expiration_queue_test.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_test.go
closes #1100
All sectors live within an expiration set within an expiration queue within a partition within a deadline. This expiration set is the set at the sectors `Expiration` field. When we reschedule expirations (say for a CC upgrade or a fault), we move it into a different set to trigger an earlier expiration. We do not change the sector's `Expiration` field, so the new set can not necessarily be determined from the sector's on chain info.
Whenever we perform an operation that affects sector expirations, we group the sectors by expiration and operate on the set _en mass_. If sectors have been rescheduled, we end up altering expiration set stats for sectors that are no longer there, and failing to update the stats for the sets to which they have moved. In the case of declaring a …
> prevent faults from double subtracting cc upgrade power

- actors/test/commit_post_test.go
- actors/test/committed_capacity_scenario_test.go
- actors/test/common_test.go
- actors/test/cron_catches_expiries_scenario_test.go
- actors/test/market_withdrawal_test.go
- actors/test/power_scenario_test.go
- actors/test/terminate_sectors_scenario_test.go
- support/vm/testing.go
closes #810
We want to scenario test market actor methods. It turns out that a scenario involving adding deals then terminating them all is one stop shopping for all the market methods. Specifically this test hits:
* `market.AddBalance`
* `market.WithdrawBalance`
* `market.PublishStorageDeals`
* `market.VerifyDealsForActivation`
* `market.ActivateDeals`
* `market.OnMinerSectorsTerminate`
* `market.ComputeDataCommitment`
* `market.CronTick`
1. Add `terminate_sectors_secnario_test.go`.
2. Various test helper functionality to support this test.
> terminate sectors scenario test

- actors/builtin/init/init_test.go
- actors/builtin/init/testing.go
- actors/builtin/testing.go
- actors/builtin/verifreg/testing.go
- actors/builtin/verifreg/verified_registry_test.go
- actors/states/check.go
This is prototyping a pattern I think we can adopt for all actor states, with state checks we can invoke in every unit and scenario test, and as a post-migration check.
More work:
- Add checks for each actor (for miner, extract deadline/partition checks from existing unit tests)
- Add top-level state tree traversal to check all actors (blocked on top-level state tree)
- Add cross-actor and aggregate state checks, e.g. miners with power
- Invoke full-state check in scenario tests and migration
FYI @acruikshank
> Add state check functions for verifreg and init

- actors/builtin/power/power_state.go
- actors/builtin/power/power_test.go
- actors/builtin/sector.go
closes #1153
We're lowering the consensus minimum power requirement for miners from 100TiB quality adjusted power to 10TiB raw power.
1. Change 32GiB consensus min to 10TiB and 64GiB consensus min to 20TiB.
2. Use raw power to alter consensus stats in `power.UpdateClaim` and `power.State.MinerNominalPowerMeetsConsensusMinimum`.
3. Adjust and skip tests to reflect the fact that we're using raw power
`states.MinerEligibleForElection` will only return true if the miner's `QualityAdjPower` is greater than zero. This is unused in actor code, but is presumably used in block validation in Lotus. Are we merely lowering the consensus min or attempting to drop the requirement that miners have QA power altogether? If the latter, this should probably be changed.
cc @momack2
> lower consensus minimum power and use raw vs. qa power for requirement

- actors/builtin/reward/cbor_gen.go
- actors/builtin/reward/reward_actor.go
- actors/builtin/reward/reward_state.go
- actors/builtin/reward/reward_test.go
- actors/migration/reward.go
- support/vm/testing.go
closes #1048
We want to rename `Reward.State.TotalMined` to `Reward.State.TotalStoragePowerReward` to make more clear that the reward actor is distributing rewards for maintaining storage power.
1. rename TotalMined to TotalStoragePowerReward
> rename TotalMined to TotalStoragePowerReward

- actors/builtin/multisig/multisig_actor.go
- actors/builtin/multisig/multisig_test.go
closes #1047
A multisig actor should always require at least 1 approval. By starting with more than one signer and then removing signers while decreasing approvals, it is possible to drop the number of approvals to zero or even negative. The PR makes dropping approvals below 1 an illegal argument exception (for the `Decrease` parameter.
1. Raise error when attempting to drop approval count below 1.
2. Test error check.
> prevent multisig from decreasing approvals below 1

- actors/builtin/miner/partition_state.go
closes #1068
If we miscalculate a partition, we would like to know that as soon as possible. Partitions have several invariants we can check to detect problems in the actor code. This PR adds that validation and uses it in all Partition methods that alter state.
1. Add `Partition.ValidatePowerState`, `Partition.ValidateBFState`, and `Partition.ValidateState` that calls the first two.
2. Call `ValidateState` in every partition method that alters state and error out if invalid.
cc @wadeAlexC
> add invariant checks to partitions

- actors/migration/top.go
We need a function for computing all the funds in an input state tree to do invariant checks.
> InBalance func

- actors/migration/top.go
Caught this while running first validation checks -- we were storing the new burnt funds actor with the old account actor code cid.
> Use new codeID for bf

- actors/builtin/market/market_test.go
- actors/builtin/miner/miner_test.go
- actors/builtin/multisig/multisig_test.go
- actors/builtin/power/power_test.go
- actors/builtin/verifreg/verified_registry_test.go
- support/mock/mockrt.go
This PR changes the exit code for caller validation failures in the MOCK runtime from `ErrForbidden` to `SysErrForbidden`, which is the [documented exit code](https://github.com/filecoin-project/go-state-types/blob/964d6c679cfcddaaf01e56ae4b6093f76ad071e0/exitcode/reserved.go#L39-L40) and code in use in lotus currently.
> fix: mock runtime validate caller exit code

- actors/builtin/multisig/multisig_test.go
- Remove redundant computations of proposal hash data
- Remove redundant `rt.Verify()` after harness methods already called it
> Clean up multisig tests

- actors/builtin/multisig/multisig_state.go
- actors/builtin/multisig/multisig_test.go
Multisig actors can now have a locked amount that exceeds their balance. But even in that state, we wish to allow messages which send no funds (e.g. proposals to call methods on the multisig itself to manipulate the signers).
> Always allow transactions that send zero

- actors/migration/nv3/migrators.go
- actors/migration/nv3/miner.go
- actors/migration/nv3/reward.go
- actors/migration/nv3/top.go
We are considering performing another small upgrade on the release/v0.9 branch, ahead of the larger upgrade/migration to v2. We're still working out exactly what we can/should include, but probably:
- repair miners broken by #1100 
- reduce some Window PoSt penalties (spec coming in another issue)
- update reward baseline parameters (previously implemented in /v2)
This PR adds the entry point and stubs for the state migration part.
FYI @acruikshank we'll probably put the code for #1177 here.
> Entry point and stubs for state migration in v0.9.

- actors/builtin/reward/reward_actor.go
- actors/builtin/reward/reward_logic.go
- actors/builtin/reward/reward_logic_test.go
- actors/builtin/reward/reward_state.go
- actors/builtin/reward/reward_test.go
- actors/migration/nv3/reward.go
This was previously implemented in #1135 for actors v2 (please cross-check compatibility). We're now planning a smaller migration to come ahead of that, involving a small state migration but no state schema changes, so we can bring this forward.
After merge:
FYI @zixuanzh
> Change reward actor baseline parameters to 2.5EiB/100% as in-place upgrade.

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_internal_test.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/monies.go
Honest miners are sometimes disproportionately penalized for operational failures and network congestion by the high undeclared-fault penalty (aka SP) for missed Window PoSts. This change reduces those costs without sacrificing much of the incentive to maintain reliable storage.
Summary:
* Remove fee incurred when a sector is successfully recovered.
* Remove fee incurred by sectors faulted when a Window PoSt is missed.
* Update Sector Fault Fee (FF) to 3.51 days of expected block reward, for ongoing faults.
As a result of this, declaring faults in advance confers no advantage compared with skipping them at Window PoSt. The DeclareFaults method remains, but may be removed in the future.
This change is a demonstration of upcoming [FIP-0002](https://github.com/filecoin-project/FIPs/blob/maste …
> [v0.9] Remove penalties on recovery and on missed PoSt (FIP-0002)

- actors/migration/nv3/correct_cc_then_fault_scenario_test.go
- actors/migration/nv3/miner.go
- support/vm/invocation_context.go
- support/vm/testing.go
- support/vm/vm.go
The cc upgrade then fault correction migration has a lot of steps and we're not terribly confident that it will work (in fact, it didn't in the state it was in when this test was started). This scenario test simulates the message invocation and runtime operations, but otherwise runs the actual actor and migration code involved in producing the error and then correcting it.
1. Introduce `support/vm` from v2
2. Make miner changes to support migrations (expose state root and create a new vm with predefined state root).
3. Introduce `TestMigrationCorrectsCCThenFaultIssue` to put a miner in a bad state by upgrading a sector then faulting the original, run a migration, and then demonstrate the miner is operational with the correct power.
> Cc upgrade correction migration scenario test

- actors/builtin/account/account_actor.go
- actors/builtin/cron/cron_actor.go
- actors/builtin/exported/actors.go
- actors/builtin/exported/actors_test.go
- actors/builtin/init/init_actor.go
- actors/builtin/market/market_actor.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/multisig/multisig_actor.go
- actors/builtin/paych/paych_actor.go
- actors/builtin/power/power_actor.go
- actors/builtin/reward/reward_actor.go
- actors/builtin/singletons.go
- actors/builtin/system/system_actor.go
- actors/builtin/verifreg/verified_registry_actor.go
- actors/runtime/invokee.go
- actors/runtime/types.go
- go.mod
- go.sum
- support/vm/invocation_context.go
- support/vm/testing.go
- support/vm/vm.go
This simplifies supporting multiple versions of actors in lotus.
* We can now determine if an actor is a "singleton" actor, without having to call `builtin.IsSingleton` for all imported versions of the actors module.
* We can now introduce a `Register(actors ...exports.BuiltinActors())` to register all actors in the lotus vm. Previously, the per-actors-version `BuiltinActor` concrete type prevented this.
Depends on https://github.com/filecoin-project/go-state-types/pull/13
> Bundle actor information along with actors themselves

- actors/builtin/account/account_actor.go
- actors/builtin/cron/cron_actor.go
- actors/builtin/exported/actors.go
- actors/builtin/exported/actors_test.go
- actors/builtin/init/init_actor.go
- actors/builtin/market/market_actor.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/multisig/multisig_actor.go
- actors/builtin/paych/paych_actor.go
- actors/builtin/power/power_actor.go
- actors/builtin/reward/reward_actor.go
- actors/builtin/singletons.go
- actors/builtin/system/system_actor.go
- actors/builtin/verifreg/verified_registry_actor.go
- actors/runtime/invokee.go
- actors/runtime/runtime.go
- go.mod
- go.sum
This simplifies supporting multiple versions of actors in lotus.
* We can now determine if an actor is a "singleton" actor, without having to call `builtin.IsSingleton` for all imported versions of the actors module.
* We can now introduce a `Register(actors ...exports.BuiltinActors())` to register all actors in the lotus vm. Previously, the per-actors-version `BuiltinActor` concrete type prevented this.
Implements https://github.com/filecoin-project/go-state-types/pull/13
Backport of https://github.com/filecoin-project/specs-actors/pull/1191
> Introduce VMActor abstraction

- actors/builtin/market/policy.go
- actors/builtin/miner/monies.go
- actors/builtin/miner/policy.go
- actors/builtin/miner/vesting_state.go
- actors/builtin/reward/reward_logic.go
- actors/builtin/verifreg/verified_registry_state.go
The `PARAM_FINISH` tags are no longer serving a useful purpose. The tagged parameters are no more or less likely to change than other parameters. Significant changes will likely come through FIPs, and trivial ones will be low impact.
Consider this PR a final check that the values are appropriate.
> Remove PARAM_FINISH tags

- actors/builtin/miner/deadline_state.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_internal_test.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/monies.go
- actors/builtin/miner/monies_test.go
- actors/builtin/miner/partition_state.go
- actors/test/commit_post_test.go
- actors/test/committed_capacity_scenario_test.go
This is #1181 adapted to the v2 code on master.
Honest miners are sometimes disproportionately penalized for operational failures and network congestion by the high undeclared-fault penalty (aka SP) for missed Window PoSts. This change reduces those costs without sacrificing much of the incentive to maintain reliable storage.
Summary:
* Remove fee incurred when a sector is successfully recovered.
* Remove fee incurred by sectors faulted when a Window PoSt is missed.
* Update Sector Fault Fee (FF) to 3.51 days of expected block reward, for ongoing faults.
As a result of this:
- Declaring faults in advance is irrational compared with skipping them at Window PoSt. The DeclareFaults method remains, but miners should avoid calling it. The rationality may change in the future. 
- There are no …
> [v2] Remove penalties on recovery and on missed PoSt

- actors/builtin/miner/miner_test.go
- support/mock/builder.go
More validation for the changes from #1181 (FIP-0002). I have already done this on `master` but wanted to check this has the same behaviour. There are many fewer tests on this branch, so it's not a big change.
> Update miner tests to use NV=3 Window PoSt fee reductions

- actors/builtin/init/init_test.go
- actors/builtin/miner/deadline_state_test.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/partition_state_test.go
- actors/builtin/miner/testing.go
- actors/builtin/testing.go
- actors/builtin/testing_test.go
- actors/builtin/verifreg/verified_registry_test.go
- actors/states/check.go
Extracted from the great checks that @Stebalien wrote in the unit test. I made slight refactors, and removed a check that required an on-time sector's expiration queue epoch to match it's declared epoch (it could instead have been moved up for CC replacement).
Part of #1165. There's more work to do here, which I'll chain off this PR.
> Extract miner partition state checks for re-use

- support/vm/invocation_context.go
- support/vm/testing.go
- support/vm/vm.go
We would like to have a test vm that works with v0.9 actors embedded in the v0.9 branch. This will allow us to run scenario tests that build state with 0.9 actors, migrate and then run with future actors. This PR will have no effect on the actor code itself.
1. Add test vm (`VM`, `InvocationContext` and some setup code).
> add test vm to 0.9 to be used to test future migrations

- actors/migration/miner_corrections.go
1. The proving period invariant being asserted is not actually an invariant because when we create miners their proving period starts are in the future.  We can add back the deadline invariant assertion here upon request since they should still always hold but would prefer if we test for them in the invariant checks instead.
2. Validation checks uncovered that we are not zeroing out recovering power.
> Migration Fixes

- actors/builtin/account/account_test.go
- actors/builtin/account/testing.go
- actors/builtin/cron/cron_test.go
- actors/builtin/cron/testing.go
- actors/builtin/market/market_test.go
- actors/builtin/market/testing.go
work towards #1165
For performance reasons, our actor state is represented over multiple data structures and values. We need to ensure these many views on state always stay consistent. This PR adds checks for the Account, Cron, and Market actors that traverse these data structures ensuring consistency and uses them to check the state after every successful unit test.
1. Create `CheckStateInvariants` function for `Account`, `Cron` and `Market` actors.
2. Add a call to this at the end of every actor test function that succeeds that fails the test if there is an inconsistency.
> state invariant tests for account, cron and market

- actors/builtin/methods.go
- actors/builtin/miner/cbor_gen.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_test.go
A miner operator may wish to change the owner address associated with a miner, e.g. due to compromise or for key rotation. 
This is a one-way operation that cannot be undone if the operator sets an address they do not actually control. To reduce risk of error, the method confirms effective ownership of the new address with a two-step process:
1. Existing owner proposes a new owner address
2. The new owner address confirms the proposal
The operator (or someone) must have access to the new address's private key in order to send the second message.
Closes #1176
FYI @magik6k @arajasek
> Add miner ChangeOwnerAddress method

- actors/builtin/market/market_test.go
- actors/builtin/market/testing.go
The market tests included a case that called functions with descending current epoch, which is not a case we generally handle. It expected an assertion failure: we'll attempt to remove the assertion in #1161.
- Removed test case
- Removed parallelism from the cases in `TestCronTickDealSlashing`, which may have been contributing to CI memory pressure (#1211)
- Tweaked error messages in state checks
It's a bit worrying that this case passed at all, rather than merely being flaky.
> Remove invalid market test

- actors/builtin/multisig/multisig_actor.go
- actors/builtin/multisig/multisig_state.go
- actors/builtin/multisig/multisig_test.go
When a multisig's signers are changed, especially through `SwapSigner`, if both a removed and added address are controlled by the same external entity, that entity might get to approve a pending transaction twice: once with a removed address and once with a new one. Whether or not this is a problem depends whether the desired behaviour treats the addresses as entities themselves, or as a handle to (possibly shared) other entities.
To avoid potential mis-use, this PR purges all approvals of pending transactions by removed signers.
- If a transaction's only approval (by its proposer) is removed, the transaction is deleted.
- If a transaction's proposer is removed but another signer has approved, the next approving signer becomes the "proposer", meaning they have the ability to cancel the …
> Multisig purges approvals from removed signers

- actors/builtin/miner/miner_state.go
While V2 actors always starts the proving period in the past, v1 set it into the future and scheduled the first cron callback one epoch before the proving period start.
Without this change, if a miner is created less than one proving period before the upgrade epoch, the miner will fail to prove their deadline 0 after the upgrade.
Alternatively, we could move the proving period start and attempt to re-schedule the initial cron callback, but some miners could end up with no time to actually submit a proof.
> Check if the proving period has started before advancing the deadline

- actors/builtin/miner/miner_state.go
- actors/migration/miner_corrections.go
The migration logic assumes that proving periods are never set in the future, and miners that haven't started their first proving period will not have experienced any faults that need correcting.
> Skip miner for miners who's proving periods haven't started

- actors/builtin/miner/testing.go
further work towards #1165
We want to run invariant checks on miner state after tests that we couldn't run on chain for performance reasons. This PR adds tests invariants hold for miner info.
1 Add `CheckMinerInfo`.
2. Call it from `CheckStateInvariants` so it will be invoked on almost all the miner tests.
> add miner info invariant checks

- actors/builtin/reward/reward_actor.go
- actors/builtin/reward/reward_test.go
As part of red team / cryptoecon requirements for upcoming upgrade the miner penalty as computed in the node and passed on to the reward actor is scaled up by a factor of three before being passed on to the miner actor for deduction.
> Multiply miner penalty by 3x

- actors/migration/reward.go
Fixing a bug.  NewEstimate does a left shift on constructor inputs so we should just directly set fields.  Thanks @arajasek for reporting, @davidad for finding the fix.
> Direct construct filter to prevent double left shift

- actors/builtin/miner/miner_test.go
- actors/builtin/miner/testing.go
- actors/migration/test/correct_cc_upgrade_then_fault_scenario_test.go
- actors/states/check.go
continued work on #1166
Many invariants of miner state remain untested by our slow checks. This PR adds several more, and should complete coverage.
1. Check miner balances (balance, locked funds, precommit deposit, initial pledge, fee debt) for consistency.
2. Assert sum of vesting table is locked funds and ensure locked fund entries are quantized.
3. Check precommit data structure for consistency.
4. Check that sector numbers of all on chain sectors have been allocated.
5. Check that deadline index is less than 48.
6. Modify test calls to pass in actor balance.
> Finish miner state checks

- actors/builtin/multisig/multisig_state.go
- actors/builtin/multisig/multisig_test.go
- actors/builtin/multisig/testing.go
work towards #1165
We want to have tests for all actor state invariants, and we have yet to do this for Multisig. This PR adds a check that multisig state is internally consistent and runs that check in all unit tests.
The invariants tested are:
* `len(st.Signers) <= SignersMax`
* `len(st.Signers) > 0`
* `NextTxnID > max(keys(PendingTxns))`
* `txn.Approved ⊆ st.Signers` for all txns.
Some almost-invariants that cannot be asserted:
* `st.InitialBalance >= 0`. see #1223
* `txn.To is ID`. The multisig actor does not enforce this. There might be good reason for this since a fork between the proposal and execution causing the txn to be sent to the wrong account.
* `txn.Value is non-negative`. The multisig does not enforce this. It will cause the send to be invalid though.
* `len(txn.Approved) …
> multisig invariant tests

- actors/builtin/paych/paych_test.go
- actors/builtin/paych/testing.go
work towards #1165
We want detailed test to check the internal consistency of actor state. This PR adds an invariant state check for the payment channel actor. Invariants checked:
* `From` and `To` are ID Addresses
* `SettlingAt >= MinSettleHeight`
* Every `lane.Reedemed` is greater than zero.
* `ToSend <= actor.Balance`
I'd like to test an invariant between `lane.Redeemed` and `ToSend` or balance but one doesn't appear to exist (see #1065).
1. Create `paych.CheckStateInvariants`.
2. Call it in every paych unit test that successfully calls a method.
> paych invariants

- actors/states/check.go
Adds cron, market and account invariant checks to the full state invariant check function.
@acruikshank I am planning to use the same `priorEpoch` value as an argument to the main state invariant check function.  This will be the epoch of the last set of state transitions that have run on the input state, the last such one being the cron from `priorEpoch`.  I just passed this in directly to the market invariant tests.  Please let me know if I got that wrong and there should be a +1.
> Hook up invariants to main call

- actors/builtin/miner/testing.go
- actors/builtin/multisig/testing.go
Calls to `Bitfield.IsSet` accounted for ~85% of the time to validate state. It's slow for a freshly-loaded bitfield. I replaced them all with map lookups.
Also added a poorly-documented multisig invariant. Note that this invariant was actually broken for three genesis msigs, but is expected to be restored in the Refuel migration (today).
> Speed up state checks by removing Bitfield.IsSet

- actors/migration/account.go
- actors/migration/cron.go
- actors/migration/init.go
- actors/migration/market.go
- actors/migration/miner.go
- actors/migration/multisig.go
- actors/migration/paych.go
- actors/migration/power.go
- actors/migration/reward.go
- actors/migration/system.go
- actors/migration/top.go
- actors/migration/verifreg.go
Ideally, these would just be pure functions. But this, at least, forces a copy which prevents us from sharing state across invocations.
> make migrations threadsafe

- actors/builtin/account/account_test.go
- actors/builtin/account/testing.go
- actors/builtin/miner/testing.go
- actors/builtin/power/power_state.go
- actors/builtin/power/power_test.go
- actors/builtin/power/testing.go
- actors/migration/power.go
- actors/migration/test/correct_cc_upgrade_then_fault_scenario_test.go
- actors/states/check.go
- actors/test/commit_post_test.go
- support/vm/vm.go
work towards #1165 and #1166 
We would like to be able to check the internal consistency of the storage power actor's state. This PR adds `CheckStateInvariants` for power state and calls it for all unit tests that are not expected to fail. 
1. Add `CheckStateInvariants`
2. Add test harness `checkState` and call it in all relevant unit tests.
3. Add a call to `CheckStateInvariants` to `states.CheckStateInvariants`.
4. Add `CheckMinersAgainstPower` to check cross actor state
5. Run `CheckStateInvariants` in scenario tests including correct_cc_upgrade migration test.
6. Fix issue with power migration where a miner's corrected claim would not update power state in a consistent way.
7. Change account invariant check to only require a public key if actor is non-singleton. (when I rebased in the …
> power actor invariant tests

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/policy.go
- go.mod
- go.sum
The 1024 value at network version 4 is erroneously low. The expected actual size for 32GiB sectors is 1920.
> Increase MaxProveCommitSize to 10KiB from network version 5

- actors/builtin/miner/deadline_state_test.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/partition_state_test.go
- actors/builtin/miner/testing.go
- actors/builtin/testing.go
- actors/migration/test/correct_cc_upgrade_then_fault_scenario_test.go
- actors/states/check.go
State validation checks are typically used in tests or by manual operation on network state. If there's an error because some part of state is unreadable (e.g. corrupted bitfield or HAMT node), then we want to know this but don't want it to prevent getting any other information about unrelated state. So treating these errors in the standard Go way by propagating them immediately isn't so helpful.
This change re-arranges the miner state checks to avoid returning errors at all. Errors from low-level functions are translated into messages and, in a few cases, dependent checks are skipped. Part of #1244.
If we like it, we should propagate this pattern to all the other state checks.
While doing this, I discovered that the checks for deadline and partition expiration queue consistency were …
> Make miner state checks robust to errors.

- actors/builtin/miner/miner_test.go
Miner tests almost all apply some rewards to a miner actor from which penalties will be paid, both because this is the usual, expected case and also makes the delta easy to explicitly test. However, they didn't previously support part of the penalty coming from unlocked balance (after the vesting funds are exhausted).
This PR:
- Introduces a `bigRewards` number to use as a constant value for rewards that are used only as a target for penalties, replacing a bunch of ad-hoc constants
- Adds `penaltyFromUnlocked` to the cron config, supporting some or all penalty being paid from unlocked funds
This is intended as a prefactor to #1249. Once rebased upon this PR, most of the delta to miner tests can disappear. Only that part related to the changed vesting schedule remains.
This PR changes …
> Clean up vesting reward use in miner tests

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/monies.go
- actors/builtin/miner/policy.go
- go.mod
- go.sum
> Vest a portion of block reward immediately (FIP-0004)

- actors/builtin/market/testing.go
- actors/builtin/miner/testing.go
- actors/states/check.go
work towards #1166
**This PR only affects tests.**
We have many consistency checks for miner state and many checks for market state. We would like to add checks that miner and market state are consistent between each other. This PR adds checks that activated deals are referenced within a sector being proving by the deal provider, and that the deal state times line up with those of the sector.
1. Add summary info for deal states in `MarketSummary`
2. Add deal info for sectors in `MinerSummary`
3. Implement `CheckDealStatesAgainstSectors` to check consistency between the above.
> add miner/market cross check

- actors/builtin/multisig/multisig_actor.go
- actors/test/multisig_delete_self_test.go
- support/vm/vm.go
@whyrusleeping reported a multisig error when removing a signer earlier today.  @acruikshank and I have traced this down to a classic blockchain re-entrancy bug related to the recent purge-removed-signers change.
This PR is WIP
* in v5 y > 1 out of x approval does NOT fail on removeSigner
* in v5 1 out of x approval does fail on removeSigner
* in v5 1 out x does fail on swapSigner
* in v6 1 out x approval does NOT fail on removeSigner
* in v6 1 out of x approval does NOT fail on swapSigner
> Multisig Signer cannot remove self

- actors/builtin/miner/testing.go
- actors/builtin/sector.go
This removes use of the RegisteredPoStProof.RegisteredSealProof() method, which we can then remove because that bijection shouldn't really exist.
See also #1268
> [v2] Attach PoSt proof policy to the PoSt proof type instead of seal proof type.

- actors/builtin/power/power_actor.go
- actors/builtin/power/power_state.go
- actors/builtin/power/power_test.go
- go.mod
- go.sum
- support/mock/builder.go
closes #1228 and #1232
We now have invariant tests for the power actor and these have exposed some edge cases that can break invariants:
1. Adding a miner whose zero power claim exceeds the `ConsensusMinerMinPower` does not update `MinerAboveMinPowerCount`, so the count of claims above the threshold does not match the count.
2. Deleting a miner's claim (currently only done when a miner cron fails) updates most power stats, but does not decrement `MinerCount` so the claims table size no longer matches `MinerCount`.
This PR addresses both issues
1. Update `go-state-types` to get some new network versions.
2. Call `updateStatsForNewMiner` in `power.CreateMiner`. This is a new method on state that currently only deals with incrementing `MinerAboveMinPowerCount`.
3. Decrement `MinerCount` when …
> add minor version 7 fixes to keep power stats edge cases from breaking invariants

- Makefile
- actors/migration/nv4/account.go
- actors/migration/nv4/cron.go
- actors/migration/nv4/init.go
- actors/migration/nv4/market.go
- actors/migration/nv4/miner.go
- actors/migration/nv4/miner_corrections.go
- actors/migration/nv4/multisig.go
- actors/migration/nv4/paych.go
- actors/migration/nv4/power.go
- actors/migration/nv4/reward.go
- actors/migration/nv4/system.go
- actors/migration/nv4/test/correct_cc_upgrade_then_fault_scenario_test.go
- actors/migration/nv4/test/parallel_migration_test.go
- actors/migration/nv4/top.go
- actors/migration/nv4/util.go
- actors/migration/nv4/verifreg.go
This makes room for another migration for network version 7 without a new major version.
> Repackage the migration to network version 4 as migration/nv4

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- go.sum
closes #1258
Many miner methods attempt to move funds from the vesting table to available balance. While this helps keep the available balance accurate, it can be expensive to run and means that most operations will fail to find any balance to unlock. This is particularly true for PreCommitSector and ConfirmSectorProofsValid, so this PR stops these methods from attempting to unlock funds starting network version 7.
1. Have PreCommitSector only call `UnlockVestedFunds` if network version is less than 7.
2. Have ConfirmSectorProofsValid only call `UnlockVestedFunds` if network version is less than 7.
3. Modify miner tests and add tests to assert that the behavior is correct before and after version 7.
> Remove vesting from PreCommitSector and ConfirmSectorProofsValid

- actors/builtin/miner/deadline_state.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
Fixes #1182.
A truly distinguishing test for this would involved submitting PoSt for two partitions, only one of them being a duplicate. I satisfied myself with inspection of the abort messages instead.
> Reject Window PoSt for already-proven partition

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state_test.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/partition_state_test.go
- actors/builtin/miner/policy.go
- actors/builtin/miner/sectors_test.go
- actors/builtin/power/power_test.go
- actors/builtin/sector.go
- actors/migration/nv4/test/correct_cc_upgrade_then_fault_scenario_test.go
- actors/migration/nv7/test/correct_power_accounting_test.go
- actors/runtime/runtime.go
- actors/states/election_test.go
- actors/test/commit_post_test.go
- actors/test/committed_capacity_scenario_test.go
- actors/test/cron_catches_expiries_scenario_test.go
- actors/test/power_scenario_test.go
- actors/test/terminate_sectors_scenario_test.go
- go.mod
- go.sum
> Replace V1 seal proof types with V1_1 in a two-stage upgrade.

- actors/builtin/account/account_test.go
- actors/builtin/account/testing.go
- actors/builtin/cron/cron_test.go
- actors/builtin/cron/testing.go
- actors/builtin/init/init_test.go
- actors/builtin/init/testing.go
- actors/builtin/market/market_test.go
- actors/builtin/market/testing.go
- actors/builtin/multisig/multisig_test.go
- actors/builtin/multisig/testing.go
- actors/builtin/paych/paych_test.go
- actors/builtin/paych/testing.go
- actors/builtin/power/power_test.go
- actors/builtin/power/testing.go
- actors/builtin/reward/testing.go
- actors/builtin/verifreg/testing.go
- actors/builtin/verifreg/verified_registry_test.go
- actors/states/check.go
Instead of returning an error that prevents the validation completing at all, all errors are now accumulated as messages. In some cases this might lead to a bit of an overload, but I think that's better than getting nothing.
I was unable to run a full mainnet state validation with `ent` because Lotus has not yet upgraded to consume the changes that preceded this. It could be worth trying to break the ent->Lotus dependency some day.
Closes #1244.
> Remove error returns from state validation functions

- actors/builtin/power/power_actor.go
- actors/builtin/power/power_test.go
Gas rebalancing [here](https://github.com/filecoin-project/FIPs/issues/31) puts PoRep gas charges 4x lower to account for speedup in default proofs implementation.  @Kubuxu has requested we include this in actors v2.3.x.  Iit is high impact and a simple change hence this PR.
> Porep Gas charge reduced 4x past v7

- actors/builtin/power/power_actor.go
- actors/builtin/power/power_test.go
This reverts commit d84628a278c877bd7ff3a0eadca42fc06105b899.
Due to cryptoeconomic requirements we will not be able to ship this adjustment
in next network version.
@ZenGround0 sorry for making you write this on short time and now reverting it,
and also causing another release having to be pushed.
> Revert "Porep Gas charge reduced 4x past v7 (#1301)"

- support/agent/cases_test.go
- support/agent/math.go
- support/agent/miner_agent.go
- support/agent/sim.go
- support/vm/invocation_context.go
To better simulate all actor processes we need to simulate miner behavior when storage faults. This PR adds a mechanism to simulate and track faults which either result in declared fault messages or sectors being skipped when PoSts are submitted. Similarly, miners can recover their faults, so the simulation can now add a probability that a fault will be recovered resulting in a declare fault recovered message.
This PR also:
1. Introduces a `math.go` file with a new `RateIterator` to contain some of the stochastic machinery used by the simulation.
2. Introduces the `RateIterator` struct that will call a function some number of times each tick based on a rate and the Poisson distribution.
> Simulate faults and recoveries

- support/agent/cases_test.go
- support/agent/deal_client_agent.go
- support/agent/math.go
- support/agent/miner_agent.go
- support/agent/miner_generator.go
- support/agent/sim.go
- support/vm/invocation_context.go
- support/vm/vm.go
In order to create a more accurate and complete simulation, this PR adds `DealClientAgent`s that interact with `MinerAgent`s to create and publish deals. This PR does a few other things along the way:
1. It moves `MinerGenerator` into its own file.
2. It modifies the sim to allow agents to chose a `DealProvider` allowing clients to communicate to miners to make deals.
3. It better simulates the circulating supply function in the VM runtime. since this is now used when calculating deal collateral.
> Simulate deals in actor code

- actors/builtin/market/cbor_gen.go
- actors/builtin/market/market_actor.go
- actors/builtin/market/market_test.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- gen/gen.go
As pre-work to batching sector pre-commits (#1241), this PR changes the market actor's `VerifyDealsForActivation` to accept deal information for multiple sectors in a single call.
Along the way, I looked to solve #981. I removed the fake sector start epoch from the method parameters, but left the check in place (using the current epoch as determined by the market actor). I think it is more helpful to check this here than not to, since this could prevent a miner losing a pre-commit deposit. It can't prevent all cases, but it can stop some.
`VerifyDealsForActivation` is only invoked internally, by the miner actor, so the changed API is expected to have little external impact.
FYI @Stebalien. Closes #981
> Convert market actor VerifyDealsForActivation to batch

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- actors/runtime/types.go
The miner actor fails to check that the target of a reported consensus fault is the miner itself. This PR adds the missing check, and expands tests to cover this and also the case of an invalid fault (already correctly handled in the code).
This issue was reported by @zgfzgf under our responsible disclosure program. Thank you! It cannot be exploited in the network at present since the Lotus node enforces that the fault target is the receiving actor during the `VerifyConsensusFault` syscall (but it shouldn't have to).
> Check consensus fault target is receiving actor

- actors/builtin/market/testing.go
- support/agent/cases_test.go
- support/agent/deal_client_agent.go
- support/agent/math.go
- support/vm/stats.go
In the process of using the agent testing framework to predict the benefits of market actor performance enhancements, I discovered some of its issues and limitations. This PR Addresses those
1. Added a 500 epoch sanity check simulation. The agent testing framework was broken in master. Because the simulations are too slow to run in CI, actor changes are likely to break the simulation without anyone knowing. This ensures anything that obviously breaks the simulation will draw attention.
2. Fixed an issue with the rate iterator that caused it to fire too often (this fixed the issue mentioned above).
3. Fixed an issue where the simulation would fail if a client attempted to make a deal before any miners had been constructed.
4. Add ReadBytes and WriteBytes to per-call stats. This data was …
> various agent testing bug fixes and improvements

- actors/builtin/market/market_actor.go
- actors/builtin/market/market_test.go
The market actor currently requires a deal to be published by the worker address of the deal provider (miner). This change also allows the miner's control addresses, which gives more flexibility to miners. The change is straightforward, and I refactored tests a little to support exercising it.
Closes #1317
> Market actor accepts deals published from miner control addresses

- actors/migration/nv9/market.go
- actors/migration/nv9/test/modify_pending_proposals_test.go
- actors/migration/nv9/test/parallel_migration_test.go
- actors/migration/nv9/top.go
- go.mod
For the upgrade to actors v3 (network version 9) we expect to migrate most actors in order to upgrade H/AMT data structures. This PR copies the full state migration setup from the nv4 migration, but then simplifies it a fair bit.
- Removed handling of balance transfers and power claim recalculations
- Removed some layers of wrapping for migration objects, inputs, and outputs.
> Actor tree traversal for migration nv9

- actors/builtin/verifreg/verified_registry_actor.go
This value doesn't need to be deserialized into verifierCap, it's never used. Just needed in checking the existence of the key.
> Remove deserializing unnecessary value

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/monies.go
- actors/builtin/miner/policy.go
- actors/builtin/multisig/multisig_actor.go
- actors/builtin/multisig/multisig_test.go
- actors/builtin/power/power_actor.go
- actors/builtin/power/power_test.go
- actors/test/multisig_delete_self_test.go
This PR removes almost all handling of network versions that strictly precede actors v3. This was prompted by noise I observed in #1327.
The one path I retained is allowing the creation of new miner actors with an old seal proof type prior to v7, so that we can test how those miners are subsequently handled. This can probably go away after #1329.
> Remove most v2-only code paths

- actors/builtin/market/market_state.go
- actors/builtin/market/policy.go
- actors/builtin/miner/deadline_state.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/partition_state.go
@ZenGround0 's benchmarks indicate that the best bitwidth for `miner.Sectors` is 5. I think they accidentally wrote 6 in #1328, which was easy to miss.
I also moved the constants consistently into the `_state.go` files, rather than `policy.go`.
> Change miner.Sectors AMT bitwidth to 5. Move constants to state files.

- actors/builtin/miner/bitfield_queue.go
- actors/builtin/miner/bitfield_queue_test.go
Given that we're working with pre-quantized epochs, we might end up adding the same epoch to the `updatedEpochs` list multiple times. This patch fixes this by iterating twice.
Technically, we could avoid the second map iteration by adding an "is epoch in quantizedValues" check to the first loop, but doing this in two steps makes this easier to reason about.
This patch also tests an edge-case caught by mutation testing.
> avoid processing epochs multiple times in bitfield queue

- actors/migration/nv9/init.go
- actors/migration/nv9/market.go
- actors/migration/nv9/miner.go
- actors/migration/nv9/multisig.go
- actors/migration/nv9/paych.go
- actors/migration/nv9/power.go
- actors/migration/nv9/top.go
- actors/migration/nv9/verifreg.go
This is a cosmetic PR, no functional change required.
- Changed naming so that migration of a single actor is "actor migration" rather than "state migration" (which is the top-level thing)
- Distinguished between the migration job (incl the function to be called) from the functional input/result. The job only exists to support parallelism.
- Un-exported and moved the internal things to the bottom of `top.go`.
> Rename and re-arrange private migration inputs

- actors/migration/nv9/test/modify_pending_proposals_test.go
- actors/migration/nv9/test/parallel_migration_test.go
- actors/migration/nv9/test/util_test.go
- actors/migration/nv9/top.go
- actors/migration/nv9/util.go
Adds a log callback to the migration entry point in order to log progress for the operator.
Add configuration for the internal queue sizes. These were previously zero, i.e. rendezvous points. The lack of buffering struck me as likely to be poor for throughput. From a rather unscientific test of migration 500k account actors, buffer sizes of 1000 and 10 improve throughput by ~15-20%. The impact will probably be lower with more complex actors.
This is preparation for #1285.
> Add logging and non-zero queue capacity to parallel migrations.

- actors/migration/nv7/test/correct_power_accounting_test.go
- actors/test/commit_post_test.go
- actors/test/committed_capacity_scenario_test.go
- actors/test/cron_catches_expiries_scenario_test.go
- actors/test/market_withdrawal_test.go
- actors/test/multisig_delete_self_test.go
- actors/test/power_scenario_test.go
- actors/test/terminate_sectors_scenario_test.go
- support/agent/cases_test.go
- support/agent/sim.go
- support/vm/testing.go
This PR refactors VM and Sim construction to always take the block store (or a blockstore factory) as parameter. This enables injection of a synchronized blockstore when it's needed, avoiding wrappers at other layers.
See also #1342. This version is a bit simpler because the sim is less developed in v2.
I've confirmed that, after this, I can use `vm2.NewVMWithSingletons` to construct the state for the parallel migration test in v3.
> [v2] Inject blockstore into VM and sim.

- actors/test/commit_post_test.go
- actors/test/committed_capacity_scenario_test.go
- actors/test/cron_catches_expiries_scenario_test.go
- actors/test/market_withdrawal_test.go
- actors/test/multisig_delete_self_test.go
- actors/test/power_scenario_test.go
- actors/test/terminate_sectors_scenario_test.go
- actors/util/adt/store.go
- support/agent/cases_test.go
- support/agent/sim.go
- support/ipld/store.go
- support/vm/testing.go
This PR refactors VM and Sim construction to always take the block store (or a blockstore factory) as parameter. This enables injection of a synchronized blockstore when it's needed, avoiding wrappers at other layers.
The existing `TestParallelMigrationCalls` works around this by constructing state manually rather than using the VM (copy-paste from `NewVMWithSingletons`). In order to use this, we need to make a similar change on the `v2` release branch, which I will follow-up with.
I needed this for profiling #1338, the test for which I could not check in for lack of the necessary changes in `v2`.
> Inject block store into VM and sim

- actors/migration/nv9/test/modify_pending_proposals_test.go
- actors/migration/nv9/test/parallel_migration_test.go
- go.mod
- go.sum
Injects a sync blockstore into the VM (since #1343), thus allowing `TestParallelMigrationCalls` to use the `NewVMWithSingletons` method to construct state. Migration tests should generally use a sync blockstore since the migration method is now concurrent even with `MaxWorkers` set to `1` (#1338).
TODO:
> Use sync blockstores for migration tests

- actors/migration/nv9/init.go
- actors/migration/nv9/market.go
- actors/migration/nv9/miner.go
- actors/migration/nv9/multisig.go
- actors/migration/nv9/paych.go
- actors/migration/nv9/power.go
- actors/migration/nv9/test/modify_pending_proposals_test.go
- actors/migration/nv9/test/parallel_migration_test.go
- actors/migration/nv9/top.go
- actors/migration/nv9/util.go
- actors/migration/nv9/verifreg.go
The design proposed here is a hierarchical cache.  The `MigrationCache` stores all per actor address `MigrationAddressCache`s.  Each `MigrationAddressCache` maps cids to cids.  Neither cache needs to be threadsafe for use in a single migration.  Caches should only be used in one migration at a time -- the premigration should finish completely before using a populated cache in another migration.  If this is a problem for lotus integration caches can be made threadsafe or we can revisit this design.
The toplevel migration reads and writes back from address cache.  This PR tweaks the actorMigration interface to avoid making every actor migrator do its own caching.
TODO
~test with two migrations in serial.~
~partial sectors amt caching~
> Add caching for premigration

- support/mock/mockrt.go
> test: add missing verification for expectVerifyPoSt in mockrt.Verify()

- actors/builtin/miner/cbor_gen.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_state_test.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/testing.go
- actors/builtin/power/cbor_gen.go
- actors/builtin/power/power_actor.go
- actors/builtin/power/power_state.go
- actors/builtin/power/power_test.go
- actors/builtin/power/testing.go
- actors/builtin/sector.go
- actors/migration/nv9/miner.go
- actors/migration/nv9/power.go
- actors/migration/nv9/test/modify_pending_proposals_test.go
- actors/states/check.go
- actors/states/election_test.go
- actors/test/commit_post_test.go
- actors/test/committed_capacity_scenario_test.go
- actors/test/cron_catches_expiries_scenario_test.go
- actors/test/power_scenario_test.go
- actors/test/terminate_sectors_scenario_test.go
- gen/gen.go
- support/agent/deal_client_agent.go
- support/agent/miner_generator.go
The seal proof type isn't the right thing to store in miner state. Many miners have sectors committed with two different seal proof types (but sharing a common Window/Winning PoSt proof type). This PR replaces the seal proof type with the Window/Winning PoSt proof types. It was basically only used for looking up those PoSt proof types anyway.
Reviewers: start with the miner state and actor, then power state and actor. Most of the rest is just noise.
Notes:
- Actors does not use WinningPoSt. I've opted to store it for presumed convenience for nodes, but we could drop if if there were a reliable Window -> Winning PoSt mapping (currently very simple), and save some noise
- I thus selected the Window PoSt proof type for the power claim and consensus minimum power calculation
- There were some …
> Replace miner on-chain seal proof type with window/winning PoSt proof types

- actors/builtin/miner/deadline_state.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/testing.go
- actors/migration/nv10/miner.go
We check:
* There are live sectors (the obvious test).
* There are no proven partitions (shouldn't be possible, but might as well check).
* The partitions haven't changed since last time (dead for at least one proving period).
* There are no optimistic proofs in the snapshot (dead for at least one proving period).
This means all "dead" partitions should be "normalized" (partitions = partitionsSnapshot, etc.). If, for example, a miner decides to "compact" a dead partition, the deadline cron will run for that partition exactly once in order to re-normalize it.
This change also fixes any incorrect PartitionsPoSted bitfields during the state upgrade.
fixes #1348
> Make sure the deadline is _really_ dead before skipping it during the deadline cron.

- actors/builtin/miner/policy.go
This way, we can modify it from lotus when testing.
This change also marks it as PARAM_SPEC instead of PARAM_TODO.
> make the dispute window a variable

- actors/migration/nv10/top.go
- actors/migration/nv10/util.go
This makes it easier to abstract over the migration cache in lotus without directly referring to _this_ implementation.
> remove the newtype from the migration cache

- actors/migration/nv10/util.go
- actors/migration/nv10/util_test.go
This lets us:
1. Clone the cache before pre-migrating.
2. Update the original cache when done pre-migrating.
Otherwise, if we fail when pre-migrating, we may give a cache to the final migration that references blocks that were never actually written to disk.
(also, switch to referencing the cache by pointer)
> migration: add methods to the cache to clone/update

- actors/migration/nv10/verifreg.go
Don't replace verified clients with verifies. Luckily, migration verification logic catches this case.
> fix verified clients migration

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/policy.go
- go.mod
- go.sum
Specifically, this fixes an issue where we could submit a window post for many (i.e., more than 10) partitions in a single window post for 2k sectors. This would lead to proof sizes over 1920 bytes (the old max).
Now, we _accurately_ compute the proof size limits from actual known constants.
Depends on https://github.com/filecoin-project/go-state-types/pull/23.
> fix: use accurate proof size limits

- actors/migration/nv10/test/modify_pending_proposals_test.go
- actors/migration/nv10/test/parallel_migration_test.go
- actors/migration/nv10/util.go
- actors/states/check.go
- actors/util/adt/store.go
- go.mod
- go.sum
- support/agent/cases_test.go
- support/agent/miner_agent.go
- support/agent/miner_generator.go
- support/agent/miner_state.go
- support/agent/sim.go
- support/vm/invocation_context.go
- support/vm/stats.go
- support/vm/vm.go
Use the new simulation framework to 1) generate realistic entropy within a state for migrating 2) continue simulating after migration to demonstrate common case network operations continue working on the migrated state.
> Migration on simulated network

- .circleci/config.yml
- actors/builtin/account/account_test.go
- actors/builtin/cron/cron_test.go
- actors/builtin/init/init_test.go
- actors/builtin/market/market_test.go
- actors/builtin/miner/bitfield_queue_test.go
- actors/builtin/miner/expiration_queue_test.go
- actors/builtin/miner/miner_test.go
- actors/builtin/multisig/multisig_test.go
- actors/builtin/paych/paych_test.go
- actors/builtin/power/power_test.go
- actors/builtin/reward/reward_test.go
- actors/builtin/system/system_test.go
- actors/builtin/verifreg/verified_registry_test.go
- actors/util/adt/array_test.go
- actors/util/adt/balancetable_test.go
- support/mock/builder.go
- support/mock/mockrt_state_test.go
Otherwise, reusing the builder can have strange side-effects when running multiple tests.
> test: remove side-effects from runtime builder

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/policy.go
- actors/builtin/sector.go
This PR is to change the sector extension disability to the sector maximum lifetime limitation, currently the change just reflect on the V1 proof-type sectors as per the proposal in https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0014.md
What's more, this change also simplified the logic of the limitation of sector extension, could apply to further proof types too.
_Note: this PR is to replace #1384  using just one commit to make it cleaner._
> Replace sector extensiblility by lifetime setting

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/policy.go
Fixes #1382 and applies FIP-0011.
Adjust consensus fault reward as described in https://github.com/filecoin-project/FIPs/blob/6db88a7d5cdf26462f130b78d6e05b56e39442ad/FIPS/fip-0011.md.
> feat: Use constant consensus fault reward

- actors/builtin/verifreg/verified_registry_actor.go
- actors/builtin/verifreg/verified_registry_test.go
Implements [FIP-0012](https://github.com/filecoin-project/FIPs/blob/5ab54f271a87b3c759c21dc36948c033f105ac4d/FIPS/fip-0012.md) and fixes #1325.
Thoughts on these changes:
- The mock runtime `addVerifiedClient` function is now overloaded to support an optional `expectedAllowance` arg to be used in the cases where VerifiedClients will now have more than what was initially allotted. This makes the verification of an `expectedAllownace` a concern on the caller rather than letting the function reflect on its internal before/after state to verify correctness. I'd personally prefer the latter to keep the call simple, but there were errors when I attempted to access the runtime map for the "before" state of the Client's DataCap allowance. (An example of that is at …
> feat: Allow VerifiedClient DataCap to be topped up

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_state_test.go
- actors/builtin/miner/miner_test.go
This is broken out (1 of 2) of my work on #1241, batching pre-commits. During implementation I realised the essential similarity between allocating and masking sector numbers, so combined the state manipulation methods.
> Batched miner state manipulations for sector number allocation

- actors/test/commit_post_test.go
- actors/test/committed_capacity_scenario_test.go
- actors/test/common_test.go
- actors/test/cron_catches_expiries_scenario_test.go
- actors/test/market_withdrawal_test.go
- actors/test/multisig_delete_self_test.go
- actors/test/power_scenario_test.go
- actors/test/terminate_sectors_scenario_test.go
- support/agent/cases_test.go
- support/agent/sim.go
- support/vm/invocation_context.go
- support/vm/stats.go
- support/vm/testing.go
- support/vm/vm.go
Now the vm_test package is free for tests *of* the VM.
Inspired by the oddity of the cbor-gen setup in #1408.
> Move VM from package vm_test to vm, because it's not tests.

- actors/builtin/methods.go
- actors/builtin/miner/cbor_gen.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_commitment_test.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_state_test.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/policy.go
- gen/gen.go
Implements a new `PreCommitSectorBatch` method, as specified by [FIP-0008](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0008.md) ([discussion](https://github.com/filecoin-project/FIPs/issues/25))
The non-batched `PreCommitSector` method remains, but should be considered deprecated. The implementation delegates internally to the batched method. This consumes less gas than before this change (due to removal of redundant checks in the batched method) but is slightly less efficient at runtime than a strictly-optimized singleton method could be. I expect it to be removed in the future.
> Implemented PreCommitSectorBatch method (FIP-0008)

- actors/builtin/market/cbor_gen.go
- actors/builtin/market/market_actor.go
- actors/builtin/market/market_test.go
- actors/builtin/methods.go
- actors/builtin/miner/cbor_gen.go
- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_commitment_test.go
- actors/builtin/miner/miner_state.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/policy.go
- actors/builtin/power/policy.go
- actors/builtin/power/power_actor.go
- actors/builtin/power/power_test.go
- actors/runtime/proof/verify.go
- actors/runtime/runtime.go
- actors/test/commit_post_test.go
- actors/test/committed_capacity_scenario_test.go
- actors/test/common_test.go
- actors/test/cron_catches_expiries_scenario_test.go
- actors/test/market_withdrawal_test.go
- actors/test/power_scenario_test.go
- actors/test/terminate_sectors_scenario_test.go
- gen/gen.go
- go.mod
- go.sum
- support/mock/mockrt.go
- support/vm/invocation_context.go
Changes needed for introducing aggregate porep verification into the network.
--edit--
I'm calling final Gas and param estimation out of scope because we'll need to merge this into lotus to start gas rebalancing.  We will do the final parameter setting in another PR.
Closes #1257.
> Aggregate PoRep

- actors/builtin/miner/miner_test.go
1000 is overkill and is making testing significantly longer for no benefit.
> Speed up tests

- actors/builtin/market/market_actor.go
- actors/builtin/market/market_state.go
- actors/builtin/market/market_test.go
- actors/builtin/market/testing.go
- support/mock/mockrt.go
#1411 described a possible problem with the market actor handling termination of sectors after deals expire. I determined it's not a problem, but clarified and cleaned up associated code and tests here. This shows that `OnMinerSectorsTerminate` does not abort if deals have expired. So this PR does not change actor behaviour.
The first commit here adds return values to some of the mock runtime's setter methods, so that a value (like an epoch) can be set and assigned to a local variable in one line: `newValue = rt.SetEpoch(oldValue + delta)`.
Closes #1411.
> Clarify market actor sector termination with expired deals

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_commitment_test.go
- actors/builtin/miner/miner_test.go
- actors/builtin/miner/policy.go
- actors/builtin/power/power_test.go
- actors/builtin/sector.go
> Remove handling of network versions < 11 from actors v5.

- actors/builtin/power/power_test.go
- actors/builtin/sector.go
- actors/states/election_test.go
- support/agent/miner_agent.go
- support/vm/vm.go
**Note: This introduces 3 other commits into the release branch, since Lotus has been pointing to `5b58b773f4fb`** 
Lotus has been unintentionally overwriting this value to 10 TiB for all proof types since mainnet. We might as well reflect this behaviour in the actors code.
> Set ConsensusMinerMinPower to 10 TiB

- actors/builtin/power/power_test.go
- actors/builtin/sector.go
- actors/states/election_test.go
Lotus has been unintentionally overwriting this value to 10 TiB for all proof types since mainnet. We might as well reflect this behaviour in the actors code.
> Set ConsensusMinerMinPower to 10 TiB for all PoStProofPolicies

- actors/builtin/miner/miner_test.go
- actors/builtin/miner/policy.go
This number bounds the amount of memory used or state loaded in a number of operations
such as declaring faults. A critical need is to limit the number of sectors that may
be addressed by a single WindowPoSt sumbission to ensure it can be safely disputed
later if fraudulent.
25000 sectors permits submitting (and disputing) up to 10 partitions at once
for both 32GiB (25,000/2,349 ~= 10.6) and 64GiB (25,000/2,300 ~= 10.8) sectors.
Empirically, disputing 10 partitions fits within the block gas limit >= 3 times over.
Closes #1415
> Raise AddressedSectorsMax from 10,000 to 25,000.

- actors/test/commit_post_test.go
- go.mod
- go.sum
- support/vm/testing.go
Adds a scenario test that measures the gas cost of PreCommitSectorBatch for various batch sizes. When pre-committing 1000 sectors, at the maximum batch size, the per-sector cost is reduced to 15% vs batch size of 1 (so 6.5x improvement). With smaller sector counts the relative improvement of large batches is even better (because the HAMT stays smaller).
```
Sector count	1,000
Batch size	IPLD cost	Calls cost	Total per sector	Total per batch
1	9,670,098,646	29,233,000	9,699,331	9,699,331
2	5,754,837,950	14,616,500	5,769,454	11,538,908
4	3,735,873,808	7,308,250	3,743,182	14,972,728
8	2,672,493,076	3,654,125	2,676,147	21,409,176
16	2,002,461,804	1,841,679	2,004,303	32,068,848
32	1,487,183,156	935,456	1,488,118	47,619,776
```
Note that this underestimates the improvement to the current mainnet …
> Scenario tests measuring pre-commit gas cost, by batch size.

- actors/builtin/market/market_actor.go
- actors/builtin/market/market_test.go
Easy improvement for #1435 
Tests are unhappy due to the change in runtime calls
>  Modify randomness logic for PublishStorageDeals

- go.mod
This tag should have been two commits further and is missing an important fix.
> chore(mod): retract v5.0.0

- go.mod
- go.sum
go-state-types is changing (https://github.com/filecoin-project/go-state-types/pull/30) to help fix this: https://github.com/filecoin-project/lotus/issues/6652
Actors v5 doesn't actually use the rt.NetworkVersion syscall since all version checking was cleaned up and subsumed in v5 code so this really shouldn't change behavior.
> Bump go state types

- go.mod
- go.sum
The lotus api doesn't yet have a good model for breaking changes. This PR temporarily reverts the network version change in the go-state-types dependency.
> go state types version revert

- actors/builtin/power/power_actor.go
- actors/builtin/power/power_test.go
While aborts from processBatchProofVerifies are all believed to be the result of programmer error or individual validator system error aborting from this code presents unnecessary risk if this is wrong.  This PR changes these aborts to errors which are then logged and ignored from top level power cron.
The impact is that now in case of programmer error a batch of seal proofs will fail to validate and propagate power to storage providers instead of aborting power cron and either halting the chain or taking out 1/60th of sps from deadline cron.
In the worst case where programmer error is global all prove commits (not prove commit aggregates) would be dropped until programmer error fixed.  In a more plausible state where programmer error is related to contents of the validation batch prove …
> Defensive programming: harden power actor against seal verify failures

- actors/builtin/market/market_actor.go
#1516
An error message was left in after another PR, but it shouldn’t have been. I opened vim and went to the line and pressed the D key two times 😅
> fixing 1516 (oneliner)

- actors/migration/nv15/miner.go
- actors/migration/nv15/top.go
As noted in #1514, a much more intelligent migration will be needed to migrate all the sectors in time. This is just the vanilla migration.
> Add an nv15 miner migration

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
This PR adds logs for when miner state balances change as requested in #1500. There were some spots where i wasn’t sure if the functions in miner_state.go were returning the right value, so i flagged those, and also found one spot where the wrong thing was being logged and fixed it.
This PR came from my IPad so sorry in advance if there’s anything wonky... tried to check diffs over carefully
> added logs for when miner state changes

- Makefile
The echoing of the 'if' block can be confusing because the body contains 'exit 1', which looks like a failure, even though the exit is not executed.
Clean build output now looks like:
```
go test -race ./actors/migration/nv15/test
ok  	github.com/filecoin-project/specs-actors/v7/actors/migration/nv15/test	(cached)
go mod tidy
rm -rf test-vectors/determinism
SPECS_ACTORS_DETERMINISM="../../test-vectors/determinism" go test ./actors/test -count=1
ok  	github.com/filecoin-project/specs-actors/v7/actors/test	110.041s
go build ./test-vectors/tools/digest
```
> Suppress echoing of command when comparing test vector digest.

- actors/builtin/miner/miner_actor.go
- actors/builtin/miner/miner_state.go
No functional change, the removed code was unreachable.
> Remove vestiges of CC upgrade by replacement

- actors/migration/nv15/miner.go
- actors/migration/nv15/top.go
- go.mod
The special Sectors migrating logic is as follows:
- For each miner, if the Head CID is found in the cache, use the cached value (same as any other actor)
- If not load the current state, do the quick steps like migrating MinerInfo
- Check the cache for the sectors AMT root -- if found, use the cached value and return back to miner migration
- Note that this step will cover many hundreds of thousands of "empty" miners in the state tree
- If not found, check the cache to see if a previous sectors AMT has been cached **for this miner**. If not found, manually migrate all sectors, and insert the incoming and outgoing AMTs into the cache (specific to the miner)
- If the cache does have a previous sectors AMT cached for this miner, load it and its corresponding migrated AMT. Diff the previous …
> NV15: Speed up the migration

- actors/builtin/market/market_actor.go
- actors/builtin/market/market_state.go
- actors/builtin/market/testing.go
- actors/builtin/market/types.go
- actors/migration/nv16/market.go
- actors/migration/nv16/test/deal_label_migration_test.go
- actors/migration/nv16/top.go
- Copy over reverted nv14 change
- Fix up migration to only change non utf8 string labels to bytes
- Try to make things faster under the assumption that very few (probably no) labels will need to be migrated 
- change test to cover both utf8 and non-utf8 labels
> FIP 0027 Migration

- actors/builtin/market/deal.go
- actors/builtin/market/deal_test.go
We only marshal DealLabels that are of type string -- we can add support for byte types later.
> FIP-0027: Add JSON un/marshaler for DealLabel
